// Alemania — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "alemania";
const countryName = "Alemania";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/alemania.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "alemania-munich",
      name: "Munich",
      coordinates: {"lat": 48.13743, "lng": 11.57549},
      isCapital: false,
      universityCount: 22,
      statistics: { population: 1505005 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-freiburg",
      name: "Freiburg",
      coordinates: {"lat": 47.9959, "lng": 7.85222},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 237460 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-stuttgart",
      name: "Stuttgart",
      coordinates: {"lat": 48.78232, "lng": 9.17702},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 612663 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dresden",
      name: "Dresden",
      coordinates: {"lat": 51.05089, "lng": 13.73832},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 564904 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-potsdam",
      name: "Potsdam",
      coordinates: {"lat": 52.39886, "lng": 13.06566},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 184754 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-frankfurt-am-main",
      name: "Frankfurt am Main",
      coordinates: {"lat": 50.11552, "lng": 8.68417},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 650000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-mitte",
      name: "Mitte",
      coordinates: {"lat": 52.52003, "lng": 13.40489},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 102338 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-karlsruhe",
      name: "Karlsruhe",
      coordinates: {"lat": 49.00937, "lng": 8.40444},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 283799 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-munster-2867543",
      name: "Münster",
      coordinates: {"lat": 51.96236, "lng": 7.62571},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 308258 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-heidelberg",
      name: "Heidelberg",
      coordinates: {"lat": 49.40768, "lng": 8.69079},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 143345 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gottingen",
      name: "Göttingen",
      coordinates: {"lat": 51.53443, "lng": 9.93228},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 122149 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-querenburg",
      name: "Querenburg",
      coordinates: {"lat": 51.45218, "lng": 7.26628},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 21294 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-moabit",
      name: "Moabit",
      coordinates: {"lat": 52.52635, "lng": 13.33903},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 81021 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-mannheim",
      name: "Mannheim",
      coordinates: {"lat": 49.4891, "lng": 8.46694},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 307960 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gie-en",
      name: "Gießen",
      coordinates: {"lat": 50.58727, "lng": 8.67554},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 89179 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-saarbrucken",
      name: "Saarbrücken",
      coordinates: {"lat": 49.23262, "lng": 7.00982},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 182971 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-regensburg",
      name: "Regensburg",
      coordinates: {"lat": 49.01513, "lng": 12.10161},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 151389 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-leipzig",
      name: "Leipzig",
      coordinates: {"lat": 51.33962, "lng": 12.37129},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 504971 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-kiel",
      name: "Kiel",
      coordinates: {"lat": 54.32133, "lng": 10.13489},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 252668 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bremen",
      name: "Bremen",
      coordinates: {"lat": 53.07582, "lng": 8.80717},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 546501 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bonn",
      name: "Bonn",
      coordinates: {"lat": 50.73438, "lng": 7.09549},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 330579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-tubingen",
      name: "Tübingen",
      coordinates: {"lat": 48.52266, "lng": 9.05222},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 92322 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-paderborn",
      name: "Paderborn",
      coordinates: {"lat": 51.71905, "lng": 8.75439},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 142161 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-marburg-an-der-lahn",
      name: "Marburg an der Lahn",
      coordinates: {"lat": 50.80904, "lng": 8.77069},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 78895 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-mainz",
      name: "Mainz",
      coordinates: {"lat": 49.98185, "lng": 8.28008},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 222889 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bielefeld",
      name: "Bielefeld",
      coordinates: {"lat": 52.03333, "lng": 8.53333},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 331906 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neustadt-sud",
      name: "Neustadt/Süd",
      coordinates: {"lat": 50.92509, "lng": 6.94762},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 37939 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-trier",
      name: "Trier",
      coordinates: {"lat": 49.75565, "lng": 6.63935},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 100129 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-schwabisch-gmund",
      name: "Schwäbisch Gmünd",
      coordinates: {"lat": 48.79947, "lng": 9.79809},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 61216 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-oberschoneweide",
      name: "Oberschöneweide",
      coordinates: {"lat": 52.46106, "lng": 13.52108},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 23638 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-koblenz",
      name: "Koblenz",
      coordinates: {"lat": 50.35357, "lng": 7.57883},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 107319 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-kaiserslautern",
      name: "Kaiserslautern",
      coordinates: {"lat": 49.443, "lng": 7.77161},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 98732 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gorlitz",
      name: "Görlitz",
      coordinates: {"lat": 51.15518, "lng": 14.98853},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 57751 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-darmstadt",
      name: "Darmstadt",
      coordinates: {"lat": 49.87167, "lng": 8.65027},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 167029 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-augsburg",
      name: "Augsburg",
      coordinates: {"lat": 48.37154, "lng": 10.89851},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 301105 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wurzburg",
      name: "Würzburg",
      coordinates: {"lat": 49.79391, "lng": 9.95121},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 133731 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-weingarten",
      name: "Weingarten",
      coordinates: {"lat": 47.81009, "lng": 9.63863},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 23802 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-villingen-schwenningen",
      name: "Villingen-Schwenningen",
      coordinates: {"lat": 48.06226, "lng": 8.49358},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 81770 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-rottenburg",
      name: "Rottenburg",
      coordinates: {"lat": 48.47629, "lng": 8.93528},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 42721 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-nuremberg",
      name: "Nuremberg",
      coordinates: {"lat": 49.45421, "lng": 11.07752},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 515543 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-lubeck",
      name: "Lübeck",
      coordinates: {"lat": 53.86893, "lng": 10.68729},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 212207 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-konigs-wusterhausen",
      name: "Königs Wusterhausen",
      coordinates: {"lat": 52.30141, "lng": 13.633},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 32513 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-karlshorst",
      name: "Karlshorst",
      coordinates: {"lat": 52.48419, "lng": 13.53185},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 28206 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hamm",
      name: "Hamm",
      coordinates: {"lat": 51.68033, "lng": 7.82089},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 178967 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-flensburg",
      name: "Flensburg",
      coordinates: {"lat": 54.78805, "lng": 9.43722},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 85838 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-erfurt",
      name: "Erfurt",
      coordinates: {"lat": 50.97734, "lng": 11.03536},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 218793 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dotzheim",
      name: "Dotzheim",
      coordinates: {"lat": 50.07438, "lng": 8.19503},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 27557 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bruhl",
      name: "Brühl",
      coordinates: {"lat": 50.82928, "lng": 6.90499},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 44137 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-braunschweig",
      name: "Braunschweig",
      coordinates: {"lat": 52.26594, "lng": 10.52673},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 244715 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bochum",
      name: "Bochum",
      coordinates: {"lat": 51.48165, "lng": 7.21648},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 385729 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-aachen",
      name: "Aachen",
      coordinates: {"lat": 50.77664, "lng": 6.08342},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 265208 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wuppertal",
      name: "Wuppertal",
      coordinates: {"lat": 51.25627, "lng": 7.14816},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 360797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wedding",
      name: "Wedding",
      coordinates: {"lat": 52.54734, "lng": 13.35594},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 85275 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-stralsund",
      name: "Stralsund",
      coordinates: {"lat": 54.30911, "lng": 13.0818},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 58976 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-reutlingen",
      name: "Reutlingen",
      coordinates: {"lat": 48.49144, "lng": 9.20427},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 112627 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-radebeul",
      name: "Radebeul",
      coordinates: {"lat": 51.10654, "lng": 13.66047},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32979 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-osnabruck",
      name: "Osnabrück",
      coordinates: {"lat": 52.27264, "lng": 8.0498},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 166462 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-oldenburg",
      name: "Oldenburg",
      coordinates: {"lat": 53.14039, "lng": 8.21479},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 159218 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neuburg-an-der-donau",
      name: "Neuburg an der Donau",
      coordinates: {"lat": 48.73218, "lng": 11.18709},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 28370 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-mulheim",
      name: "Mülheim",
      coordinates: {"lat": 51.43218, "lng": 6.87967},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 173050 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-misburg",
      name: "Misburg",
      coordinates: {"lat": 52.39006, "lng": 9.85199},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 26114 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ludwigsburg",
      name: "Ludwigsburg",
      coordinates: {"lat": 48.89731, "lng": 9.19161},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 87603 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-jena",
      name: "Jena",
      coordinates: {"lat": 50.92878, "lng": 11.5899},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 104712 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-idstein",
      name: "Idstein",
      coordinates: {"lat": 50.21773, "lng": 8.26679},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 25736 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hildesheim",
      name: "Hildesheim",
      coordinates: {"lat": 52.15077, "lng": 9.95112},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 103052 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hamburg",
      name: "Hamburg",
      coordinates: {"lat": 53.55073, "lng": 9.99302},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 1973896 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-halle-saale",
      name: "Halle (Saale)",
      coordinates: {"lat": 51.48158, "lng": 11.97947},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 237865 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-fulda",
      name: "Fulda",
      coordinates: {"lat": 50.55162, "lng": 9.67518},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 63760 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-friedrichshain",
      name: "Friedrichshain",
      coordinates: {"lat": 52.51559, "lng": 13.45482},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 117829 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-freising",
      name: "Freising",
      coordinates: {"lat": 48.40351, "lng": 11.74876},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 42570 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-eberswalde",
      name: "Eberswalde",
      coordinates: {"lat": 52.83492, "lng": 13.81951},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 41980 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dahlem",
      name: "Dahlem",
      coordinates: {"lat": 52.4581, "lng": 13.28702},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 16916 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-blasewitz",
      name: "Blasewitz",
      coordinates: {"lat": 51.05305, "lng": 13.79831},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 24863 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bingen-am-rhein",
      name: "Bingen am Rhein",
      coordinates: {"lat": 49.96675, "lng": 7.8992},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 26339 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-amberg",
      name: "Amberg",
      coordinates: {"lat": 49.44287, "lng": 11.86267},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 44737 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-altstadt-nord",
      name: "Altstadt Nord",
      coordinates: {"lat": 50.93893, "lng": 6.95752},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 17922 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-eselsberg",
      name: "Eselsberg",
      coordinates: {"lat": 48.40978, "lng": 9.95138},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 19075 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-zehlendorf",
      name: "Zehlendorf",
      coordinates: {"lat": 52.43333, "lng": 13.25},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 54328 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-winterhude",
      name: "Winterhude",
      coordinates: {"lat": 53.59368, "lng": 10.01123},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56382 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wilhelmshaven",
      name: "Wilhelmshaven",
      coordinates: {"lat": 53.5476, "lng": 8.10395},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 84393 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-vechta",
      name: "Vechta",
      coordinates: {"lat": 52.73064, "lng": 8.28968},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 29729 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-rotherbaum",
      name: "Rotherbaum",
      coordinates: {"lat": 53.56707, "lng": 9.98097},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 17114 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-luneburg",
      name: "Lüneburg",
      coordinates: {"lat": 53.25122, "lng": 10.41548},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 71260 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ludwigshafen-am-rhein",
      name: "Ludwigshafen am Rhein",
      coordinates: {"lat": 49.48121, "lng": 8.44641},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 163196 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-lorrach",
      name: "Lörrach",
      coordinates: {"lat": 47.61497, "lng": 7.66457},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 47002 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-idar-oberstein",
      name: "Idar-Oberstein",
      coordinates: {"lat": 49.71443, "lng": 7.30776},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 29158 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-heilbronn",
      name: "Heilbronn",
      coordinates: {"lat": 49.13995, "lng": 9.22054},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 120733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hagen",
      name: "Hagen",
      coordinates: {"lat": 51.36081, "lng": 7.47168},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 198972 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gonsenheim",
      name: "Gonsenheim",
      coordinates: {"lat": 50.0017, "lng": 8.19653},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 25000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-furth",
      name: "Fürth",
      coordinates: {"lat": 49.47593, "lng": 10.98856},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 132036 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-freiberg",
      name: "Freiberg",
      coordinates: {"lat": 50.91089, "lng": 13.33881},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 43670 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-erlangen",
      name: "Erlangen",
      coordinates: {"lat": 49.59099, "lng": 11.00783},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 102675 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-emden",
      name: "Emden",
      coordinates: {"lat": 53.36592, "lng": 7.20846},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 51526 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-eggenstein-leopoldshafen",
      name: "Eggenstein-Leopoldshafen",
      coordinates: {"lat": 49.09006, "lng": 8.39879},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15189 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dorstfeld",
      name: "Dorstfeld",
      coordinates: {"lat": 51.50135, "lng": 7.41085},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 27655 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dieburg",
      name: "Dieburg",
      coordinates: {"lat": 49.89738, "lng": 8.84613},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15168 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-detmold",
      name: "Detmold",
      coordinates: {"lat": 51.93855, "lng": 8.87318},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 73680 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-deggendorf",
      name: "Deggendorf",
      coordinates: {"lat": 48.84085, "lng": 12.96068},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 31081 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bendorf",
      name: "Bendorf",
      coordinates: {"lat": 50.42289, "lng": 7.57924},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 17495 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bayreuth",
      name: "Bayreuth",
      coordinates: {"lat": 49.94782, "lng": 11.57893},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 72940 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ansbach",
      name: "Ansbach",
      coordinates: {"lat": 49.30481, "lng": 10.5931},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 31839 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-altstadt-sud",
      name: "Altstadt Sud",
      coordinates: {"lat": 50.93331, "lng": 6.95954},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 27515 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-treptow",
      name: "Treptow",
      coordinates: {"lat": 52.49376, "lng": 13.44469},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neustadt-nord",
      name: "Neustadt/Nord",
      coordinates: {"lat": 50.949, "lng": 6.9479},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 28146 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-worms",
      name: "Worms",
      coordinates: {"lat": 49.63278, "lng": 8.35916},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 81099 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wolfenbuttel",
      name: "Wolfenbüttel",
      coordinates: {"lat": 52.16442, "lng": 10.54095},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 54740 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-witten",
      name: "Witten",
      coordinates: {"lat": 51.44362, "lng": 7.35258},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 91808 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wismar",
      name: "Wismar",
      coordinates: {"lat": 53.89218, "lng": 11.45563},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 45255 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wilnsdorf",
      name: "Wilnsdorf",
      coordinates: {"lat": 50.81667, "lng": 8.1},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21505 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wersten",
      name: "Wersten",
      coordinates: {"lat": 51.18459, "lng": 6.81249},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27151 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-weimar",
      name: "Weimar",
      coordinates: {"lat": 50.9803, "lng": 11.32903},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 64727 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wei-ensee",
      name: "Weißensee",
      coordinates: {"lat": 52.55632, "lng": 13.46649},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 47693 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wattenscheid",
      name: "Wattenscheid",
      coordinates: {"lat": 51.48057, "lng": 7.14251},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 73965 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-velbert",
      name: "Velbert",
      coordinates: {"lat": 51.33537, "lng": 7.04348},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 87669 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-vegesack",
      name: "Vegesack",
      coordinates: {"lat": 53.17923, "lng": 8.62228},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 34757 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-unterhaching",
      name: "Unterhaching",
      coordinates: {"lat": 48.06598, "lng": 11.61564},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20852 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ulm",
      name: "Ulm",
      coordinates: {"lat": 48.39841, "lng": 9.99155},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 120451 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-speyer",
      name: "Speyer",
      coordinates: {"lat": 49.32083, "lng": 8.43111},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 50343 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-schwetzingen",
      name: "Schwetzingen",
      coordinates: {"lat": 49.38217, "lng": 8.5823},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22593 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-schoneberg",
      name: "Schöneberg",
      coordinates: {"lat": 52.49801, "lng": 13.3443},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 122658 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-sankt-augustin",
      name: "Sankt Augustin",
      coordinates: {"lat": 50.77538, "lng": 7.197},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56094 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-rostock",
      name: "Rostock",
      coordinates: {"lat": 54.0887, "lng": 12.14049},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 198293 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-rosenheim",
      name: "Rosenheim",
      coordinates: {"lat": 47.85637, "lng": 12.12247},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 60167 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-rissen",
      name: "Rissen",
      coordinates: {"lat": 53.58306, "lng": 9.75708},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16051 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ravensburg",
      name: "Ravensburg",
      coordinates: {"lat": 47.78198, "lng": 9.61062},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48825 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-pfungstadt",
      name: "Pfungstadt",
      coordinates: {"lat": 49.80557, "lng": 8.60307},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25415 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-pforzheim",
      name: "Pforzheim",
      coordinates: {"lat": 48.88436, "lng": 8.69892},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 119313 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-penzberg",
      name: "Penzberg",
      coordinates: {"lat": 47.75293, "lng": 11.377},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16079 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-passau",
      name: "Passau",
      coordinates: {"lat": 48.5665, "lng": 13.43122},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50560 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-pankow",
      name: "Pankow",
      coordinates: {"lat": 52.56926, "lng": 13.40186},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 65375 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-oyten",
      name: "Oyten",
      coordinates: {"lat": 53.05498, "lng": 9.01995},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15286 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-offenburg",
      name: "Offenburg",
      coordinates: {"lat": 48.47377, "lng": 7.94495},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 59238 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-offenbach",
      name: "Offenbach",
      coordinates: {"lat": 50.10061, "lng": 8.76647},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 119192 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-nurtingen",
      name: "Nürtingen",
      coordinates: {"lat": 48.62565, "lng": 9.34203},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 40210 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-niederschonhausen",
      name: "Niederschönhausen",
      coordinates: {"lat": 52.58483, "lng": 13.40272},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32037 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neu-ulm",
      name: "Neu-Ulm",
      coordinates: {"lat": 48.39279, "lng": 10.01112},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 51389 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neustadt-an-der-weinstra-e",
      name: "Neustadt an der Weinstraße",
      coordinates: {"lat": 49.35009, "lng": 8.13886},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 53984 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neuruppin",
      name: "Neuruppin",
      coordinates: {"lat": 52.92815, "lng": 12.80311},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31901 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neukolln",
      name: "Neukölln",
      coordinates: {"lat": 52.47719, "lng": 13.43126},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 164636 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neubrandenburg",
      name: "Neubrandenburg",
      coordinates: {"lat": 53.55735, "lng": 13.26105},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 68082 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-munster-2867542",
      name: "Munster",
      coordinates: {"lat": 52.98538, "lng": 10.08993},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17746 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-mittweida",
      name: "Mittweida",
      coordinates: {"lat": 50.98622, "lng": 12.97537},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16619 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-melle",
      name: "Melle",
      coordinates: {"lat": 52.20197, "lng": 8.33826},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 46436 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-meissen",
      name: "Meissen",
      coordinates: {"lat": 51.16158, "lng": 13.4737},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28492 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-linden",
      name: "Linden",
      coordinates: {"lat": 52.36449, "lng": 9.71157},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 38284 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-leuben",
      name: "Leuben",
      coordinates: {"lat": 51.01122, "lng": 13.82029},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 38353 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-lemgo",
      name: "Lemgo",
      coordinates: {"lat": 52.02786, "lng": 8.89901},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 41943 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-landshut",
      name: "Landshut",
      coordinates: {"lat": 48.52961, "lng": 12.16179},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 71863 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-laatzen",
      name: "Laatzen",
      coordinates: {"lat": 52.31506, "lng": 9.79739},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 41838 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-konstanz",
      name: "Konstanz",
      coordinates: {"lat": 47.66033, "lng": 9.17582},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 81275 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-kleve",
      name: "Kleve",
      coordinates: {"lat": 51.78826, "lng": 6.13865},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 49072 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-kempten-allgau",
      name: "Kempten (Allgäu)",
      coordinates: {"lat": 47.72674, "lng": 10.31389},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 61399 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-kehl",
      name: "Kehl",
      coordinates: {"lat": 48.57297, "lng": 7.81523},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39584 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ingolstadt",
      name: "Ingolstadt",
      coordinates: {"lat": 48.76508, "lng": 11.42372},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 120658 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hoxter",
      name: "Höxter",
      coordinates: {"lat": 51.77501, "lng": 9.38155},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32713 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hof",
      name: "Hof",
      coordinates: {"lat": 50.31297, "lng": 11.91261},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 49239 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-herford",
      name: "Herford",
      coordinates: {"lat": 52.11457, "lng": 8.67343},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 64879 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hellersdorf",
      name: "Hellersdorf",
      coordinates: {"lat": 52.53319, "lng": 13.6088},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84103 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-heide",
      name: "Heide",
      coordinates: {"lat": 54.19562, "lng": 9.09742},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20599 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hattersheim",
      name: "Hattersheim",
      coordinates: {"lat": 50.06906, "lng": 8.48632},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25035 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-harburg",
      name: "Harburg",
      coordinates: {"lat": 53.46057, "lng": 9.98388},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 169221 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hameln",
      name: "Hameln",
      coordinates: {"lat": 52.10397, "lng": 9.35623},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 58666 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-marienthal",
      name: "Marienthal",
      coordinates: {"lat": 53.56667, "lng": 10.08333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 287101 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hamburg-mitte",
      name: "Hamburg-Mitte",
      coordinates: {"lat": 53.55, "lng": 10.01667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 301231 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gustrow",
      name: "Güstrow",
      coordinates: {"lat": 53.7972, "lng": 12.17337},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31217 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-universitats-und-hansestadt-greifswald",
      name: "Universitäts- und Hansestadt Greifswald",
      coordinates: {"lat": 54.08905, "lng": 13.40244},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 52731 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gotha",
      name: "Gotha",
      coordinates: {"lat": 50.94823, "lng": 10.70193},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 46615 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-goppingen",
      name: "Göppingen",
      coordinates: {"lat": 48.70354, "lng": 9.65209},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 58040 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gesundbrunnen",
      name: "Gesundbrunnen",
      coordinates: {"lat": 52.55035, "lng": 13.39139},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 93862 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gerlingen",
      name: "Gerlingen",
      coordinates: {"lat": 48.79954, "lng": 9.06316},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19050 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gera",
      name: "Gera",
      coordinates: {"lat": 50.88029, "lng": 12.08187},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 104659 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-garching",
      name: "Garching",
      coordinates: {"lat": 48.24896, "lng": 11.65101},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17656 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-friedenau",
      name: "Friedenau",
      coordinates: {"lat": 52.47133, "lng": 13.32813},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27998 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-fischeln",
      name: "Fischeln",
      coordinates: {"lat": 51.30353, "lng": 6.58836},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 26030 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-falkensee",
      name: "Falkensee",
      coordinates: {"lat": 52.56014, "lng": 13.0927},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 37468 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-esslingen",
      name: "Esslingen",
      coordinates: {"lat": 48.73961, "lng": 9.30473},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 92390 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-elmshorn",
      name: "Elmshorn",
      coordinates: {"lat": 53.74912, "lng": 9.66176},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48703 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dusseldorf",
      name: "Düsseldorf",
      coordinates: {"lat": 51.22319, "lng": 6.77927},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 618685 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dillenburg",
      name: "Dillenburg",
      coordinates: {"lat": 50.74114, "lng": 8.28699},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22974 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-cottbus",
      name: "Cottbus",
      coordinates: {"lat": 51.75769, "lng": 14.32888},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84754 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-coburg",
      name: "Coburg",
      coordinates: {"lat": 50.25937, "lng": 10.96384},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 41901 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-chemnitz",
      name: "Chemnitz",
      coordinates: {"lat": 50.8357, "lng": 12.92922},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 247220 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-charlottenburg",
      name: "Charlottenburg",
      coordinates: {"lat": 52.51667, "lng": 13.28333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 129359 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-calw",
      name: "Calw",
      coordinates: {"lat": 48.71419, "lng": 8.74031},
      isCapital: false,
      universityCount: 0,
      statistics: { population: 23740 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-buxtehude",
      name: "Buxtehude",
      coordinates: {"lat": 53.46994, "lng": 9.68968},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 38192 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-burg-bei-magdeburg",
      name: "Burg bei Magdeburg",
      coordinates: {"lat": 52.27152, "lng": 11.85493},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24958 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-buer",
      name: "Buer",
      coordinates: {"lat": 51.5774, "lng": 7.0518},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32919 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bremerhaven",
      name: "Bremerhaven",
      coordinates: {"lat": 53.55357, "lng": 8.57553},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 118610 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-biberach-an-der-ri",
      name: "Biberach an der Riß",
      coordinates: {"lat": 48.09345, "lng": 9.79053},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32333 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bernburg",
      name: "Bernburg",
      coordinates: {"lat": 51.79464, "lng": 11.7401},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32113 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-baunatal",
      name: "Baunatal",
      coordinates: {"lat": 51.25182, "lng": 9.40747},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27929 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bamberg",
      name: "Bamberg",
      coordinates: {"lat": 49.89873, "lng": 10.90067},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 70047 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bad-homburg-vor-der-hohe",
      name: "Bad Homburg vor der Höhe",
      coordinates: {"lat": 50.22683, "lng": 8.61816},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 51859 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bad-hersfeld",
      name: "Bad Hersfeld",
      coordinates: {"lat": 50.87197, "lng": 9.70891},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 30725 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-aschaffenburg",
      name: "Aschaffenburg",
      coordinates: {"lat": 49.97704, "lng": 9.15214},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 68551 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-aalen",
      name: "Aalen",
      coordinates: {"lat": 48.83777, "lng": 10.0933},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 67085 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-sudstadt",
      name: "Südstadt",
      coordinates: {"lat": 52.35967, "lng": 9.7508},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 40557 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bilderstockchen",
      name: "Bilderstöckchen",
      coordinates: {"lat": 50.96983, "lng": 6.92997},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15430 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-stuttgart-ost",
      name: "Stuttgart-Ost",
      coordinates: {"lat": 48.78363, "lng": 9.21032},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 47500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dusseldorf-pempelfort",
      name: "Düsseldorf-Pempelfort",
      coordinates: {"lat": 51.23812, "lng": 6.78678},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28941 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-nordstadt",
      name: "Nordstadt",
      coordinates: {"lat": 52.38561, "lng": 9.71586},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17429 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-petershausen-west",
      name: "Petershausen-West",
      coordinates: {"lat": 47.67411, "lng": 9.17787},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16021 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Germany",
  capital: "Berlin",
  currency: "EUR",
  language: "alemán",
  continent: "Europa",
  population: 83491249,
  cities,
  // Las universidades no van aqui: viven en ./universities/alemania.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 321,
  aliases: ["alemania", "germany"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
