// Alemania — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "alemania";
const countryName = "Alemania";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/alemania.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "alemania-mitte",
      name: "Mitte",
      coordinates: {"lat": 52.52003, "lng": 13.40489},
      isCapital: false,
      universityCount: 21,
      statistics: { population: 102338 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-munich",
      name: "Munich",
      coordinates: {"lat": 48.13743, "lng": 11.57549},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 1505005 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-potsdam",
      name: "Potsdam",
      coordinates: {"lat": 52.39886, "lng": 13.06566},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 184754 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-stuttgart",
      name: "Stuttgart",
      coordinates: {"lat": 48.78232, "lng": 9.17702},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 612663 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-leipzig",
      name: "Leipzig",
      coordinates: {"lat": 51.33962, "lng": 12.37129},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 504971 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-karlsruhe",
      name: "Karlsruhe",
      coordinates: {"lat": 49.00937, "lng": 8.40444},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 283799 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-munster",
      name: "Münster",
      coordinates: {"lat": 51.96236, "lng": 7.62571},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 308258 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-kiel",
      name: "Kiel",
      coordinates: {"lat": 54.32133, "lng": 10.13489},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 252668 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-freiburg",
      name: "Freiburg",
      coordinates: {"lat": 47.9959, "lng": 7.85222},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 237460 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-saarbrucken",
      name: "Saarbrücken",
      coordinates: {"lat": 49.23262, "lng": 7.00982},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 182971 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-mannheim",
      name: "Mannheim",
      coordinates: {"lat": 49.4891, "lng": 8.46694},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 307960 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-heidelberg",
      name: "Heidelberg",
      coordinates: {"lat": 49.40768, "lng": 8.69079},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 143345 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-frankfurt-am-main",
      name: "Frankfurt am Main",
      coordinates: {"lat": 50.11552, "lng": 8.68417},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 650000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dresden",
      name: "Dresden",
      coordinates: {"lat": 51.05089, "lng": 13.73832},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 564904 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-regensburg",
      name: "Regensburg",
      coordinates: {"lat": 49.01513, "lng": 12.10161},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 151389 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-moabit",
      name: "Moabit",
      coordinates: {"lat": 52.52635, "lng": 13.33903},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 81021 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hamburg",
      name: "Hamburg",
      coordinates: {"lat": 53.55073, "lng": 9.99302},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1973896 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gottingen",
      name: "Göttingen",
      coordinates: {"lat": 51.53443, "lng": 9.93228},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 122149 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bremen",
      name: "Bremen",
      coordinates: {"lat": 53.07582, "lng": 8.80717},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 546501 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bonn",
      name: "Bonn",
      coordinates: {"lat": 50.73438, "lng": 7.09549},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 330579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-altstadt-nord",
      name: "Altstadt Nord",
      coordinates: {"lat": 50.93893, "lng": 6.95752},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 17922 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wurzburg",
      name: "Würzburg",
      coordinates: {"lat": 49.79391, "lng": 9.95121},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 133731 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-querenburg",
      name: "Querenburg",
      coordinates: {"lat": 51.45218, "lng": 7.26628},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 21294 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-paderborn",
      name: "Paderborn",
      coordinates: {"lat": 51.71905, "lng": 8.75439},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 142161 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neuburg-an-der-donau",
      name: "Neuburg an der Donau",
      coordinates: {"lat": 48.73218, "lng": 11.18709},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 28370 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-mainz",
      name: "Mainz",
      coordinates: {"lat": 49.98185, "lng": 8.28008},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 222889 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-tubingen",
      name: "Tübingen",
      coordinates: {"lat": 48.52266, "lng": 9.05222},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 92322 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-trier",
      name: "Trier",
      coordinates: {"lat": 49.75565, "lng": 6.63935},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 100129 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-stralsund",
      name: "Stralsund",
      coordinates: {"lat": 54.30911, "lng": 13.0818},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 58976 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-nuremberg",
      name: "Nuremberg",
      coordinates: {"lat": 49.45421, "lng": 11.07752},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 515543 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-marburg-an-der-lahn",
      name: "Marburg an der Lahn",
      coordinates: {"lat": 50.80904, "lng": 8.77069},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 78895 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ludwigsburg",
      name: "Ludwigsburg",
      coordinates: {"lat": 48.89731, "lng": 9.19161},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 87603 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-lubeck",
      name: "Lübeck",
      coordinates: {"lat": 53.86893, "lng": 10.68729},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 212207 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hildesheim",
      name: "Hildesheim",
      coordinates: {"lat": 52.15077, "lng": 9.95112},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 103052 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-flensburg",
      name: "Flensburg",
      coordinates: {"lat": 54.78805, "lng": 9.43722},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 85838 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-erfurt",
      name: "Erfurt",
      coordinates: {"lat": 50.97734, "lng": 11.03536},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 218793 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-blasewitz",
      name: "Blasewitz",
      coordinates: {"lat": 51.05305, "lng": 13.79831},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 24863 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bielefeld",
      name: "Bielefeld",
      coordinates: {"lat": 52.03333, "lng": 8.53333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 331906 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-augsburg",
      name: "Augsburg",
      coordinates: {"lat": 48.37154, "lng": 10.89851},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 301105 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-aachen",
      name: "Aachen",
      coordinates: {"lat": 50.77664, "lng": 6.08342},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 265208 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wuppertal",
      name: "Wuppertal",
      coordinates: {"lat": 51.25627, "lng": 7.14816},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 360797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-winterhude",
      name: "Winterhude",
      coordinates: {"lat": 53.59368, "lng": 10.01123},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56382 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wilhelmshaven",
      name: "Wilhelmshaven",
      coordinates: {"lat": 53.5476, "lng": 8.10395},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84393 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-vechta",
      name: "Vechta",
      coordinates: {"lat": 52.73064, "lng": 8.28968},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 29729 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-schoneberg",
      name: "Schöneberg",
      coordinates: {"lat": 52.49801, "lng": 13.3443},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 122658 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-rottenburg",
      name: "Rottenburg",
      coordinates: {"lat": 48.47629, "lng": 8.93528},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 42721 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-reutlingen",
      name: "Reutlingen",
      coordinates: {"lat": 48.49144, "lng": 9.20427},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 112627 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-osnabruck",
      name: "Osnabrück",
      coordinates: {"lat": 52.27264, "lng": 8.0498},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 166462 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-oldenburg",
      name: "Oldenburg",
      coordinates: {"lat": 53.14039, "lng": 8.21479},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 159218 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-magdeburg",
      name: "Magdeburg",
      coordinates: {"lat": 52.13129, "lng": 11.63189},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 244329 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ludwigshafen-am-rhein",
      name: "Ludwigshafen am Rhein",
      coordinates: {"lat": 49.48121, "lng": 8.44641},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 163196 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-konigs-wusterhausen",
      name: "Königs Wusterhausen",
      coordinates: {"lat": 52.30141, "lng": 13.633},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 32513 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-koblenz",
      name: "Koblenz",
      coordinates: {"lat": 50.35357, "lng": 7.57883},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 107319 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-kaiserslautern",
      name: "Kaiserslautern",
      coordinates: {"lat": 49.443, "lng": 7.77161},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 98732 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-idar-oberstein",
      name: "Idar-Oberstein",
      coordinates: {"lat": 49.71443, "lng": 7.30776},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 29158 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-heilbronn",
      name: "Heilbronn",
      coordinates: {"lat": 49.13995, "lng": 9.22054},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 120733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gie-en",
      name: "Gießen",
      coordinates: {"lat": 50.58727, "lng": 8.67554},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 89179 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-fulda",
      name: "Fulda",
      coordinates: {"lat": 50.55162, "lng": 9.67518},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 63760 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-freising",
      name: "Freising",
      coordinates: {"lat": 48.40351, "lng": 11.74876},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 42570 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-essen",
      name: "Essen",
      coordinates: {"lat": 51.45657, "lng": 7.01228},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 593085 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-darmstadt",
      name: "Darmstadt",
      coordinates: {"lat": 49.87167, "lng": 8.65027},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 167029 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-cottbus",
      name: "Cottbus",
      coordinates: {"lat": 51.75769, "lng": 14.32888},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 84754 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-braunschweig",
      name: "Braunschweig",
      coordinates: {"lat": 52.26594, "lng": 10.52673},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 244715 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bamberg",
      name: "Bamberg",
      coordinates: {"lat": 49.89873, "lng": 10.90067},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 70047 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-amberg",
      name: "Amberg",
      coordinates: {"lat": 49.44287, "lng": 11.86267},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 44737 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neustadt-sud",
      name: "Neustadt/Süd",
      coordinates: {"lat": 50.92509, "lng": 6.94762},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 37939 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-zwickau",
      name: "Zwickau",
      coordinates: {"lat": 50.72724, "lng": 12.48839},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 98796 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-zittau",
      name: "Zittau",
      coordinates: {"lat": 50.89772, "lng": 14.80764},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25286 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-zehlendorf",
      name: "Zehlendorf",
      coordinates: {"lat": 52.43333, "lng": 13.25},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 54328 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-weingarten",
      name: "Weingarten",
      coordinates: {"lat": 47.81009, "lng": 9.63863},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23802 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-weimar",
      name: "Weimar",
      coordinates: {"lat": 50.9803, "lng": 11.32903},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 64727 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wei-ensee",
      name: "Weißensee",
      coordinates: {"lat": 52.55632, "lng": 13.46649},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 47693 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-wedding",
      name: "Wedding",
      coordinates: {"lat": 52.54734, "lng": 13.35594},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 85275 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-villingen-schwenningen",
      name: "Villingen-Schwenningen",
      coordinates: {"lat": 48.06226, "lng": 8.49358},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 81770 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-vegesack",
      name: "Vegesack",
      coordinates: {"lat": 53.17923, "lng": 8.62228},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 34757 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ulm",
      name: "Ulm",
      coordinates: {"lat": 48.39841, "lng": 9.99155},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 120451 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-uelzen",
      name: "Uelzen",
      coordinates: {"lat": 52.96449, "lng": 10.56704},
      isCapital: false,
      universityCount: 0,
      statistics: { population: 34996 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-speyer",
      name: "Speyer",
      coordinates: {"lat": 49.32083, "lng": 8.43111},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 50343 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-schwabisch-gmund",
      name: "Schwäbisch Gmünd",
      coordinates: {"lat": 48.79947, "lng": 9.79809},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 61216 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-radebeul",
      name: "Radebeul",
      coordinates: {"lat": 51.10654, "lng": 13.66047},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 32979 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-passau",
      name: "Passau",
      coordinates: {"lat": 48.5665, "lng": 13.43122},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50560 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-pankow",
      name: "Pankow",
      coordinates: {"lat": 52.56926, "lng": 13.40186},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 65375 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-misburg",
      name: "Misburg",
      coordinates: {"lat": 52.39006, "lng": 9.85199},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 26114 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-luneburg",
      name: "Lüneburg",
      coordinates: {"lat": 53.25122, "lng": 10.41548},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 71260 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-lorrach",
      name: "Lörrach",
      coordinates: {"lat": 47.61497, "lng": 7.66457},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 47002 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-konstanz",
      name: "Konstanz",
      coordinates: {"lat": 47.66033, "lng": 9.17582},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 81275 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-jena",
      name: "Jena",
      coordinates: {"lat": 50.92878, "lng": 11.5899},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 104712 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hamm",
      name: "Hamm",
      coordinates: {"lat": 51.68033, "lng": 7.82089},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 178967 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-marienthal",
      name: "Marienthal",
      coordinates: {"lat": 53.56667, "lng": 10.08333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 287101 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hamburg-mitte",
      name: "Hamburg-Mitte",
      coordinates: {"lat": 53.55, "lng": 10.01667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 301231 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-halle-saale",
      name: "Halle (Saale)",
      coordinates: {"lat": 51.48158, "lng": 11.97947},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 237865 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-hagen",
      name: "Hagen",
      coordinates: {"lat": 51.36081, "lng": 7.47168},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 198972 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gustrow",
      name: "Güstrow",
      coordinates: {"lat": 53.7972, "lng": 12.17337},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31217 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gorlitz",
      name: "Görlitz",
      coordinates: {"lat": 51.15518, "lng": 14.98853},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 57751 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gonsenheim",
      name: "Gonsenheim",
      coordinates: {"lat": 50.0017, "lng": 8.19653},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-gera",
      name: "Gera",
      coordinates: {"lat": 50.88029, "lng": 12.08187},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 104659 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-furth",
      name: "Fürth",
      coordinates: {"lat": 49.47593, "lng": 10.98856},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 132036 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-frankfurt-oder",
      name: "Frankfurt (Oder)",
      coordinates: {"lat": 52.34714, "lng": 14.55062},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 57107 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-emden",
      name: "Emden",
      coordinates: {"lat": 53.36592, "lng": 7.20846},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 51526 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dusseldorf",
      name: "Düsseldorf",
      coordinates: {"lat": 51.22319, "lng": 6.77927},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 618685 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dotzheim",
      name: "Dotzheim",
      coordinates: {"lat": 50.07438, "lng": 8.19503},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27557 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dorstfeld",
      name: "Dorstfeld",
      coordinates: {"lat": 51.50135, "lng": 7.41085},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27655 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dieburg",
      name: "Dieburg",
      coordinates: {"lat": 49.89738, "lng": 8.84613},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15168 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-dahlem",
      name: "Dahlem",
      coordinates: {"lat": 52.4581, "lng": 13.28702},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16916 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-coburg",
      name: "Coburg",
      coordinates: {"lat": 50.25937, "lng": 10.96384},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 41901 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-chemnitz",
      name: "Chemnitz",
      coordinates: {"lat": 50.8357, "lng": 12.92922},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 247220 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-calw",
      name: "Calw",
      coordinates: {"lat": 48.71419, "lng": 8.74031},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 23740 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bruhl",
      name: "Brühl",
      coordinates: {"lat": 50.82928, "lng": 6.90499},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 44137 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bremerhaven",
      name: "Bremerhaven",
      coordinates: {"lat": 53.55357, "lng": 8.57553},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 118610 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bochum",
      name: "Bochum",
      coordinates: {"lat": 51.48165, "lng": 7.21648},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 385729 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bingen-am-rhein",
      name: "Bingen am Rhein",
      coordinates: {"lat": 49.96675, "lng": 7.8992},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 26339 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bendorf",
      name: "Bendorf",
      coordinates: {"lat": 50.42289, "lng": 7.57924},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17495 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bayreuth",
      name: "Bayreuth",
      coordinates: {"lat": 49.94782, "lng": 11.57893},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 72940 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bautzen",
      name: "Bautzen",
      coordinates: {"lat": 51.18035, "lng": 14.43494},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 41972 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-bad-hersfeld",
      name: "Bad Hersfeld",
      coordinates: {"lat": 50.87197, "lng": 9.70891},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 30725 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-ansbach",
      name: "Ansbach",
      coordinates: {"lat": 49.30481, "lng": 10.5931},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31839 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-altstadt-sud",
      name: "Altstadt Sud",
      coordinates: {"lat": 50.93331, "lng": 6.95954},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27515 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-treptow",
      name: "Treptow",
      coordinates: {"lat": 52.49376, "lng": 13.44469},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-neustadt-nord",
      name: "Neustadt/Nord",
      coordinates: {"lat": 50.949, "lng": 6.9479},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28146 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "alemania-eselsberg",
      name: "Eselsberg",
      coordinates: {"lat": 48.40978, "lng": 9.95138},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19075 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Germany",
  capital: "Berlin",
  currency: "EUR",
  language: "alemán",
  continent: "Europa",
  population: 83491249,
  cities,
  // Las universidades no van aqui: viven en ./universities/alemania.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 321,
  aliases: ["alemania", "germany"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
