// Bangladés — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "banglades";
const countryName = "Bangladés";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/banglades.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "banglades-chattogram",
      name: "Chattogram",
      coordinates: {"lat": 22.3384, "lng": 91.83168},
      isCapital: false,
      universityCount: 19,
      statistics: { population: 3920222 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-dhanmondi",
      name: "Dhanmondi",
      coordinates: {"lat": 23.74, "lng": 90.385},
      isCapital: false,
      universityCount: 18,
      statistics: { population: 54210 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-kafrul",
      name: "Kafrul",
      coordinates: {"lat": 23.78822, "lng": 90.37359},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 339734 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-bhatara",
      name: "Bhatara",
      coordinates: {"lat": 23.8, "lng": 90.45},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 324300 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-tungi",
      name: "Tungi",
      coordinates: {"lat": 23.89154, "lng": 90.40232},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 337579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-khulna",
      name: "Khulna",
      coordinates: {"lat": 22.80979, "lng": 89.56439},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 1500689 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-sylhet",
      name: "Sylhet",
      coordinates: {"lat": 24.89904, "lng": 91.87198},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 237000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-rajshahi",
      name: "Rajshahi",
      coordinates: {"lat": 24.374, "lng": 88.60114},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 763580 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-comilla",
      name: "Comilla",
      coordinates: {"lat": 23.46186, "lng": 91.18503},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 634654 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-gazipur",
      name: "Gazipur",
      coordinates: {"lat": 23.99844, "lng": 90.42234},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 2674697 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-pallabi",
      name: "Pallabi",
      coordinates: {"lat": 23.825, "lng": 90.37},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 597574 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-paltan",
      name: "Paltan",
      coordinates: {"lat": 23.73625, "lng": 90.41426},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 184492 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-kushtia",
      name: "Kushtia",
      coordinates: {"lat": 23.9028, "lng": 89.11943},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 135724 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-barishal",
      name: "Barishal",
      coordinates: {"lat": 22.70497, "lng": 90.37013},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 202242 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-savar",
      name: "Savar",
      coordinates: {"lat": 23.84858, "lng": 90.25002},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 286008 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-rangpur",
      name: "Rangpur",
      coordinates: {"lat": 25.74664, "lng": 89.25166},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 1031388 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-ramna-maidan",
      name: "Ramna Maidan",
      coordinates: {"lat": 23.73333, "lng": 90.4},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 143677 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-jessore",
      name: "Jessore",
      coordinates: {"lat": 23.16971, "lng": 89.21371},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 243987 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-azimpur",
      name: "Azimpur",
      coordinates: {"lat": 23.7298, "lng": 90.3854},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 96641 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-narayanganj",
      name: "Narayanganj",
      coordinates: {"lat": 23.61352, "lng": 90.50298},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 223622 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-mymensingh",
      name: "Mymensingh",
      coordinates: {"lat": 24.75636, "lng": 90.40646},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 225126 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-pabna",
      name: "Pābna",
      coordinates: {"lat": 24.00644, "lng": 89.2372},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 186781 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-tangail",
      name: "Tangail",
      coordinates: {"lat": 24.24984, "lng": 89.91655},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 180144 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-kishorganj",
      name: "Kishorganj",
      coordinates: {"lat": 24.43944, "lng": 90.78291},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 90690 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-hathazari",
      name: "Hāthazāri",
      coordinates: {"lat": 22.50515, "lng": 91.81339},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 498179 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-mirpur-model-thana",
      name: "Mirpur Model Thana",
      coordinates: {"lat": 23.80931, "lng": 90.36093},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 546503 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-motijheel",
      name: "Motijheel",
      coordinates: {"lat": 23.72772, "lng": 90.41919},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 202308 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-thakurgaon",
      name: "Thākurgaon",
      coordinates: {"lat": 26.03097, "lng": 88.46989},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 71096 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-jamalpur",
      name: "Jamālpur",
      coordinates: {"lat": 24.91965, "lng": 89.94812},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 167900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-shahzadpur",
      name: "Shāhzādpur",
      coordinates: {"lat": 24.17687, "lng": 89.5988},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 102420 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-nageswari",
      name: "Nageswari",
      coordinates: {"lat": 25.96817, "lng": 89.69153},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 49425 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-kaliganj",
      name: "Kālīganj",
      coordinates: {"lat": 23.40964, "lng": 89.13801},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 45631 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-habiganj",
      name: "Habiganj",
      coordinates: {"lat": 24.38044, "lng": 91.41299},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 88760 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-feni",
      name: "Feni",
      coordinates: {"lat": 23.0144, "lng": 91.3966},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84028 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-sarishabari",
      name: "Sarishābāri",
      coordinates: {"lat": 24.75127, "lng": 89.83126},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 81325 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-par-naogaon",
      name: "Pār Naogaon",
      coordinates: {"lat": 24.80418, "lng": 88.94875},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 192464 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-lakshmipur",
      name: "Lakshmīpur",
      coordinates: {"lat": 22.9443, "lng": 90.83005},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 61703 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-faridpur",
      name: "Farīdpur",
      coordinates: {"lat": 23.60612, "lng": 89.84064},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 112187 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-dinajpur",
      name: "Dinajpur",
      coordinates: {"lat": 25.62745, "lng": 88.63779},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 206234 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-cox-s-bazar",
      name: "Cox’s Bāzār",
      coordinates: {"lat": 21.43973, "lng": 92.00955},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 253788 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-rangamati",
      name: "Rangamati",
      coordinates: {"lat": 22.64317, "lng": 92.19186},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 106069 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-brahmanbaria",
      name: "Brāhmanbāria",
      coordinates: {"lat": 23.97464, "lng": 91.11228},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 264326 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-bogra",
      name: "Bogra",
      coordinates: {"lat": 24.85098, "lng": 89.37108},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 210000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-nawabganj",
      name: "Nawābganj",
      coordinates: {"lat": 24.59025, "lng": 88.27444},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 142361 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-bibir-hat",
      name: "Bibir Hat",
      coordinates: {"lat": 22.68347, "lng": 91.79058},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 89030 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-natore",
      name: "Natore",
      coordinates: {"lat": 24.41112, "lng": 88.98673},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 369138 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "banglades-patuakhali",
      name: "Patuakhali",
      coordinates: {"lat": 22.36833, "lng": 90.3458},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 65000 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Bangladesh",
  capital: "Dhaka",
  currency: "BDT",
  language: "bengalí",
  continent: "Asia",
  population: 175686899,
  cities,
  // Las universidades no van aqui: viven en ./universities/banglades.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 83,
  aliases: ["banglades", "bangladesh"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
