// China — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "china";
const countryName = "China";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/china.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "china-beijing",
      name: "Beijing",
      coordinates: {"lat": 39.9075, "lng": 116.39723},
      isCapital: true,
      universityCount: 59,
      statistics: { population: 18960744 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xi-an",
      name: "Xi’an",
      coordinates: {"lat": 34.25833, "lng": 108.92861},
      isCapital: false,
      universityCount: 21,
      statistics: { population: 12952907 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-nanjing",
      name: "Nanjing",
      coordinates: {"lat": 32.06167, "lng": 118.77778},
      isCapital: false,
      universityCount: 22,
      statistics: { population: 9314685 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-tianjin",
      name: "Tianjin",
      coordinates: {"lat": 39.14222, "lng": 117.17667},
      isCapital: false,
      universityCount: 20,
      statistics: { population: 13866009 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-huangpu",
      name: "Huangpu",
      coordinates: {"lat": 31.2378, "lng": 121.4781},
      isCapital: false,
      universityCount: 18,
      statistics: { population: 656200 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-hangzhou",
      name: "Hangzhou",
      coordinates: {"lat": 30.29365, "lng": 120.16142},
      isCapital: false,
      universityCount: 18,
      statistics: { population: 11936010 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-chengdu",
      name: "Chengdu",
      coordinates: {"lat": 30.66667, "lng": 104.06667},
      isCapital: false,
      universityCount: 18,
      statistics: { population: 20937757 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-wuchang",
      name: "Wuchang",
      coordinates: {"lat": 30.54314, "lng": 114.30068},
      isCapital: false,
      universityCount: 17,
      statistics: { population: 1102188 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-guangzhou",
      name: "Guangzhou",
      coordinates: {"lat": 23.11667, "lng": 113.25},
      isCapital: false,
      universityCount: 16,
      statistics: { population: 18676605 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-changchun",
      name: "Changchun",
      coordinates: {"lat": 43.88, "lng": 125.32278},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 9066906 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-shenyang",
      name: "Shenyang",
      coordinates: {"lat": 41.79222, "lng": 123.43278},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 9070093 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-zhengzhou",
      name: "Zhengzhou",
      coordinates: {"lat": 34.75778, "lng": 113.64861},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 12600574 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-kunming",
      name: "Kunming",
      coordinates: {"lat": 25.03889, "lng": 102.71833},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 8460088 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-hefei",
      name: "Hefei",
      coordinates: {"lat": 31.86389, "lng": 117.28083},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 9465881 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-changsha",
      name: "Changsha",
      coordinates: {"lat": 28.19874, "lng": 112.97087},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 3093980 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jinan",
      name: "Jinan",
      coordinates: {"lat": 36.66833, "lng": 116.99722},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 9202432 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-harbin",
      name: "Harbin",
      coordinates: {"lat": 45.75, "lng": 126.65},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 10009854 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-fuzhou",
      name: "Fuzhou",
      coordinates: {"lat": 26.06139, "lng": 119.30611},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 8291268 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-wuhan",
      name: "Wuhan",
      coordinates: {"lat": 30.58333, "lng": 114.26667},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 13739000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-taiyuan",
      name: "Taiyuan",
      coordinates: {"lat": 37.86944, "lng": 112.56028},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 5305061 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-dalian",
      name: "Dalian",
      coordinates: {"lat": 38.91222, "lng": 121.60222},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 7450785 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-nanchang",
      name: "Nanchang",
      coordinates: {"lat": 28.68396, "lng": 115.85306},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 2357839 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-dasha",
      name: "Dasha",
      coordinates: {"lat": 23.11037, "lng": 113.4418},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 116307 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-tongzhou",
      name: "Tongzhou",
      coordinates: {"lat": 39.90395, "lng": 116.66183},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 163326 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-shijiazhuang",
      name: "Shijiazhuang",
      coordinates: {"lat": 38.04139, "lng": 114.47861},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 11235086 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-qingdao",
      name: "Qingdao",
      coordinates: {"lat": 36.06488, "lng": 120.38042},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 7172451 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-guiyang",
      name: "Guiyang",
      coordinates: {"lat": 26.58333, "lng": 106.71667},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 5987018 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-urumqi",
      name: "Ürümqi",
      coordinates: {"lat": 43.80096, "lng": 87.60046},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 4054000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-lanzhou",
      name: "Lanzhou",
      coordinates: {"lat": 36.05701, "lng": 103.83987},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 4359446 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-guilin",
      name: "Guilin",
      coordinates: {"lat": 25.28022, "lng": 110.29639},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1572300 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-chongqing",
      name: "Chongqing",
      coordinates: {"lat": 29.56026, "lng": 106.55771},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 22000000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-baoding",
      name: "Baoding",
      coordinates: {"lat": 38.87288, "lng": 115.46246},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 2739887 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-suzhou",
      name: "Suzhou",
      coordinates: {"lat": 31.30408, "lng": 120.59538},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 6715559 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-hohhot",
      name: "Hohhot",
      coordinates: {"lat": 40.81056, "lng": 111.65222},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 3446100 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xuhui",
      name: "Xuhui",
      coordinates: {"lat": 31.19594, "lng": 121.44709},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1109800 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-ningbo",
      name: "Ningbo",
      coordinates: {"lat": 29.87819, "lng": 121.54945},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 3731203 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-changleng",
      name: "Changleng",
      coordinates: {"lat": 28.7, "lng": 115.81667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 56429 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-changping",
      name: "Changping",
      coordinates: {"lat": 40.21612, "lng": 116.23471},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 93174 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-zhenjiang",
      name: "Zhenjiang",
      coordinates: {"lat": 32.21086, "lng": 119.45508},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 950516 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xiaolingwei",
      name: "Xiaolingwei",
      coordinates: {"lat": 32.03244, "lng": 118.854},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 66031 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xiangtan",
      name: "Xiangtan",
      coordinates: {"lat": 27.85, "lng": 112.9},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 959303 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xiamen",
      name: "Xiamen",
      coordinates: {"lat": 24.47979, "lng": 118.08187},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 4617251 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-wenzhou",
      name: "Wenzhou",
      coordinates: {"lat": 27.99942, "lng": 120.66682},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 2650000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-nanning",
      name: "Nanning",
      coordinates: {"lat": 22.81667, "lng": 108.31667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 8741584 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-gangxia",
      name: "Gangxia",
      coordinates: {"lat": 22.54033, "lng": 114.06136},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 28600 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yantai",
      name: "Yantai",
      coordinates: {"lat": 37.47649, "lng": 121.44081},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 7102100 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xinxiang",
      name: "Xinxiang",
      coordinates: {"lat": 35.19033, "lng": 113.80151},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1047088 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xining",
      name: "Xining",
      coordinates: {"lat": 36.62554, "lng": 101.75739},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 2467965 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-mentougou",
      name: "Mentougou",
      coordinates: {"lat": 39.93819, "lng": 116.09307},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 197772 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jinzhou-1805298",
      name: "Jinzhou",
      coordinates: {"lat": 39.1, "lng": 121.71667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 215386 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jing-an",
      name: "Jing’an",
      coordinates: {"lat": 31.22, "lng": 121.41583},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 936500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-daxing",
      name: "Daxing",
      coordinates: {"lat": 39.74025, "lng": 116.32693},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 104904 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-ganzhou",
      name: "Ganzhou",
      coordinates: {"lat": 25.84664, "lng": 114.9326},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1977253 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-bishan",
      name: "Bishan",
      coordinates: {"lat": 29.59491, "lng": 106.22476},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 204702 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-bengbu",
      name: "Bengbu",
      coordinates: {"lat": 32.94083, "lng": 117.36083},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 972784 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jinzhou-2036427",
      name: "Jinzhou",
      coordinates: {"lat": 41.10778, "lng": 121.14167},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1524362 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jilin",
      name: "Jilin",
      coordinates: {"lat": 43.84652, "lng": 126.5608},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1895865 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jiamusi",
      name: "Jiamusi",
      coordinates: {"lat": 46.79711, "lng": 130.31118},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 549549 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-gaojing",
      name: "Gaojing",
      coordinates: {"lat": 31.32225, "lng": 121.4751},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 127512 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yunlong",
      name: "Yunlong",
      coordinates: {"lat": 34.25281, "lng": 117.25167},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 345393 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-zhanjiang",
      name: "Zhanjiang",
      coordinates: {"lat": 21.23391, "lng": 110.38749},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1400709 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-anyang",
      name: "Anyang",
      coordinates: {"lat": 36.096, "lng": 114.38278},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1146839 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yuci",
      name: "Yuci",
      coordinates: {"lat": 37.68028, "lng": 112.73194},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 235929 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yinchuan",
      name: "Yinchuan",
      coordinates: {"lat": 38.46806, "lng": 106.27306},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 2859074 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yibin",
      name: "Yibin",
      coordinates: {"lat": 28.7593, "lng": 104.63994},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 836340 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yangpu",
      name: "Yangpu",
      coordinates: {"lat": 31.26193, "lng": 121.51904},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1210800 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yangliuqing",
      name: "Yangliuqing",
      coordinates: {"lat": 39.1375, "lng": 116.99972},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 76387 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xinyang",
      name: "Xinyang",
      coordinates: {"lat": 32.12278, "lng": 114.06556},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1416800 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xianyang",
      name: "Xianyang",
      coordinates: {"lat": 34.33778, "lng": 108.70261},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1034081 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xianshuigu",
      name: "Xianshuigu",
      coordinates: {"lat": 38.985, "lng": 117.38278},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 74028 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-wuxi",
      name: "Wuxi",
      coordinates: {"lat": 31.56887, "lng": 120.28857},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 4396835 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-wuhu",
      name: "Wuhu",
      coordinates: {"lat": 31.35259, "lng": 118.42947},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1598165 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yinzhu",
      name: "Yinzhu",
      coordinates: {"lat": 35.87861, "lng": 119.97528},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 75656 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-tangshan",
      name: "Tangshan",
      coordinates: {"lat": 39.64381, "lng": 118.18319},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 3372102 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-tai-an",
      name: "Tai’an",
      coordinates: {"lat": 36.18528, "lng": 117.12},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1735425 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-songjiang",
      name: "Songjiang",
      coordinates: {"lat": 31.03443, "lng": 121.22326},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1973500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-songgang",
      name: "Songgang",
      coordinates: {"lat": 22.77866, "lng": 113.8454},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24201 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-shiqiao",
      name: "Shiqiao",
      coordinates: {"lat": 22.9464, "lng": 113.35769},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 135308 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-shantou",
      name: "Shantou",
      coordinates: {"lat": 23.35489, "lng": 116.67876},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 3838900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-sanya",
      name: "Sanya",
      coordinates: {"lat": 18.25435, "lng": 109.50947},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1031396 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-qiongshan",
      name: "Qiongshan",
      coordinates: {"lat": 20.00864, "lng": 110.35384},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 87657 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-pudong",
      name: "Pudong",
      coordinates: {"lat": 31.23995, "lng": 121.50094},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 5681512 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-mianyang",
      name: "Mianyang",
      coordinates: {"lat": 31.46784, "lng": 104.68168},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1550000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-luoyang-1801792",
      name: "Luoyang",
      coordinates: {"lat": 34.67345, "lng": 112.43684},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1390581 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-luoyang-1801797",
      name: "Luoyang",
      coordinates: {"lat": 24.95938, "lng": 118.683},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 66188 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-linping",
      name: "Linping",
      coordinates: {"lat": 30.4225, "lng": 120.29722},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 78180 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-kaifeng",
      name: "Kaifeng",
      coordinates: {"lat": 34.7986, "lng": 114.30742},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1451741 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jinqiao",
      name: "Jinqiao",
      coordinates: {"lat": 31.27092, "lng": 121.59331},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-jiaozuo",
      name: "Jiaozuo",
      coordinates: {"lat": 35.23925, "lng": 113.23914},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 865413 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-hengyang",
      name: "Hengyang",
      coordinates: {"lat": 26.88946, "lng": 112.61888},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1075516 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-handan",
      name: "Handan",
      coordinates: {"lat": 36.60999, "lng": 114.48764},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1358318 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-dongguan",
      name: "Dongguan",
      coordinates: {"lat": 23.01797, "lng": 113.74866},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 9644871 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-changning",
      name: "Changning",
      coordinates: {"lat": 31.21739, "lng": 121.42105},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 694900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-buhe",
      name: "Buhe",
      coordinates: {"lat": 30.28757, "lng": 112.22979},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 106347 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-songling",
      name: "Songling",
      coordinates: {"lat": 31.1933, "lng": 120.71758},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 77566 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-zhangjiakou",
      name: "Zhangjiakou",
      coordinates: {"lat": 40.78341, "lng": 114.87139},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 692602 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-yanji",
      name: "Yanji",
      coordinates: {"lat": 42.88825, "lng": 129.50241},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 326957 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-qiqihar",
      name: "Qiqihar",
      coordinates: {"lat": 47.33922, "lng": 123.96154},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 882364 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-hulan",
      name: "Hulan",
      coordinates: {"lat": 45.89326, "lng": 126.57836},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 109104 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-huajing",
      name: "Huajing",
      coordinates: {"lat": 31.122, "lng": 121.44925},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 67415 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-xili",
      name: "Xili",
      coordinates: {"lat": 22.58809, "lng": 113.94786},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 40685 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "china-sao-lazaro",
      name: "São Lázaro",
      coordinates: {"lat": 22.1999, "lng": 113.54895},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33100 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "China",
  capital: "Beijing",
  currency: "CNY",
  language: "chino",
  continent: "Asia",
  population: 1406585000,
  cities,
  // Las universidades no van aqui: viven en ./universities/china.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 398,
  aliases: ["china"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
