// Corea del Sur — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "corea-del-sur";
const countryName = "Corea del Sur";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/corea-del-sur.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "corea-del-sur-seoul",
      name: "Seoul",
      coordinates: {"lat": 37.566, "lng": 126.9784},
      isCapital: true,
      universityCount: 49,
      statistics: { population: 10349312 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-daejeon",
      name: "Daejeon",
      coordinates: {"lat": 36.34913, "lng": 127.38493},
      isCapital: false,
      universityCount: 22,
      statistics: { population: 1441203 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-busan",
      name: "Busan",
      coordinates: {"lat": 35.10168, "lng": 129.03004},
      isCapital: false,
      universityCount: 18,
      statistics: { population: 3285147 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-guri-si",
      name: "Guri-si",
      coordinates: {"lat": 37.5986, "lng": 127.1394},
      isCapital: false,
      universityCount: 16,
      statistics: { population: 195236 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-suwon",
      name: "Suwon",
      coordinates: {"lat": 37.29111, "lng": 127.00889},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 1234582 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-siheungdong",
      name: "Siheungdong",
      coordinates: {"lat": 37.45177, "lng": 126.91079},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 128142 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-gwangju",
      name: "Gwangju",
      coordinates: {"lat": 35.15472, "lng": 126.91556},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 1401235 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-gwangmyeong",
      name: "Gwangmyeong",
      coordinates: {"lat": 37.47722, "lng": 126.86639},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 357545 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-cheonan",
      name: "Cheonan",
      coordinates: {"lat": 36.8065, "lng": 127.1522},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 658831 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-daegu",
      name: "Daegu",
      coordinates: {"lat": 35.87028, "lng": 128.59111},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 2365523 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-gyeongsan-si",
      name: "Gyeongsan-si",
      coordinates: {"lat": 35.82333, "lng": 128.73778},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 266951 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-gangneung",
      name: "Gangneung",
      coordinates: {"lat": 37.75266, "lng": 128.87239},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 208161 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-incheon",
      name: "Incheon",
      coordinates: {"lat": 37.45646, "lng": 126.70515},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 3015482 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-chinju",
      name: "Chinju",
      coordinates: {"lat": 35.19278, "lng": 128.08472},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 307242 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-wonju",
      name: "Wŏnju",
      coordinates: {"lat": 37.35139, "lng": 127.94528},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 332849 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-hayang",
      name: "Hayang",
      coordinates: {"lat": 35.91333, "lng": 128.82},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 27236 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-chuncheon",
      name: "Chuncheon",
      coordinates: {"lat": 37.87472, "lng": 127.73417},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 284855 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-jeonju",
      name: "Jeonju",
      coordinates: {"lat": 35.82194, "lng": 127.14889},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 638421 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-cheongju-si",
      name: "Cheongju-si",
      coordinates: {"lat": 36.63722, "lng": 127.48972},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 852147 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-seongnam-si",
      name: "Seongnam-si",
      coordinates: {"lat": 37.43861, "lng": 127.13778},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 914832 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-sejong",
      name: "Sejong",
      coordinates: {"lat": 36.59245, "lng": 127.29223},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 394630 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-yangju",
      name: "Yangju",
      coordinates: {"lat": 37.83311, "lng": 127.06169},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 179923 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-bucheon-si",
      name: "Bucheon-si",
      coordinates: {"lat": 37.49889, "lng": 126.78306},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 850731 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-kimhae",
      name: "Kimhae",
      coordinates: {"lat": 35.23417, "lng": 128.88111},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 531966 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-anyang-si",
      name: "Anyang-si",
      coordinates: {"lat": 37.3925, "lng": 126.92694},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 595644 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-ansan-si",
      name: "Ansan-si",
      coordinates: {"lat": 37.32361, "lng": 126.82194},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 623256 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-hwawon",
      name: "Hwawŏn",
      coordinates: {"lat": 35.80167, "lng": 128.50083},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 64718 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-yeonil",
      name: "Yeonil",
      coordinates: {"lat": 36.00446, "lng": 129.3185},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 34560 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-neietsu",
      name: "Neietsu",
      coordinates: {"lat": 37.18447, "lng": 128.46821},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 25413 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-ulsan",
      name: "Ulsan",
      coordinates: {"lat": 35.53722, "lng": 129.31667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1098421 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-pyeongtaek",
      name: "Pyeongtaek",
      coordinates: {"lat": 36.99472, "lng": 127.08889},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 364694 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-asan",
      name: "Asan",
      coordinates: {"lat": 36.78361, "lng": 127.00417},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 97749 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-nonsan",
      name: "Nonsan",
      coordinates: {"lat": 36.20389, "lng": 127.08472},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 43845 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-naju",
      name: "Naju",
      coordinates: {"lat": 35.0292, "lng": 126.7175},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 42459 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-muan",
      name: "Muan",
      coordinates: {"lat": 34.99014, "lng": 126.47899},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 92009 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-mokpo",
      name: "Mokpo",
      coordinates: {"lat": 34.81282, "lng": 126.39181},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 268402 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-gongju",
      name: "Gongju",
      coordinates: {"lat": 36.45556, "lng": 127.12472},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 72435 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-gijang",
      name: "Gijang",
      coordinates: {"lat": 35.24417, "lng": 129.21389},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 176388 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-ara-dong",
      name: "Ara-dong",
      coordinates: {"lat": 33.46889, "lng": 126.5275},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 40448 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-hanam",
      name: "Hanam",
      coordinates: {"lat": 37.54, "lng": 127.20556},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 254415 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-yeongju",
      name: "Yeongju",
      coordinates: {"lat": 36.82167, "lng": 128.63083},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84625 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-eisen",
      name: "Eisen",
      coordinates: {"lat": 35.9675, "lng": 128.93083},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56006 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-yangsan",
      name: "Yangsan",
      coordinates: {"lat": 35.34199, "lng": 129.03358},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 358074 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-damyang",
      name: "Damyang",
      coordinates: {"lat": 35.31889, "lng": 126.98389},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 44800 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-osan",
      name: "Osan",
      coordinates: {"lat": 37.15222, "lng": 127.07056},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 238788 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-goyang-si",
      name: "Goyang-si",
      coordinates: {"lat": 37.65639, "lng": 126.835},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1061752 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-gimcheon",
      name: "Gimcheon",
      coordinates: {"lat": 36.12176, "lng": 128.11981},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 150000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-hongseong",
      name: "Hongseong",
      coordinates: {"lat": 36.6009, "lng": 126.665},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 89174 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-changwon",
      name: "Changwon",
      coordinates: {"lat": 35.22806, "lng": 128.68111},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1025702 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-jangseong",
      name: "Jangseong",
      coordinates: {"lat": 35.29778, "lng": 126.78444},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 42129 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-anseong",
      name: "Anseong",
      coordinates: {"lat": 37.01083, "lng": 127.27028},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 69255 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-andong",
      name: "Andong",
      coordinates: {"lat": 36.56636, "lng": 128.72275},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 153348 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-yeosu",
      name: "Yeosu",
      coordinates: {"lat": 34.76062, "lng": 127.66215},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 268823 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-pubal",
      name: "Pubal",
      coordinates: {"lat": 37.29167, "lng": 127.50778},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 63026 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "corea-del-sur-naeso",
      name: "Naesŏ",
      coordinates: {"lat": 35.24972, "lng": 128.52},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 80987 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "South Korea",
  capital: "Seoul",
  currency: "KRW",
  language: "coreano",
  continent: "Asia",
  population: 51684564,
  cities,
  // Las universidades no van aqui: viven en ./universities/corea-del-sur.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 244,
  aliases: ["corea-del-sur", "south-korea"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
