// España — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "espana";
const countryName = "España";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/espana.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "espana-alcala-de-henares",
      name: "Alcalá de Henares",
      coordinates: {"lat": 40.48205, "lng": -3.35996},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 193751 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-segovia",
      name: "Segovia",
      coordinates: {"lat": 40.94808, "lng": -4.11839},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 51683 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-valladolid",
      name: "Valladolid",
      coordinates: {"lat": 41.65541, "lng": -4.72353},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 300618 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-delicias",
      name: "Delicias",
      coordinates: {"lat": 41.64928, "lng": -0.90757},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 110520 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-universidad",
      name: "Universidad",
      coordinates: {"lat": 40.42567, "lng": -3.70707},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 32783 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-vallehermoso",
      name: "Vallehermoso",
      coordinates: {"lat": 40.44289, "lng": -3.71124},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 19853 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-valencia",
      name: "Valencia",
      coordinates: {"lat": 39.47391, "lng": -0.37966},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 824340 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-cordoba",
      name: "Córdoba",
      coordinates: {"lat": 37.89155, "lng": -4.77275},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 325708 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-salamanca",
      name: "Salamanca",
      coordinates: {"lat": 40.96882, "lng": -5.66388},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 144825 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-bilbao",
      name: "Bilbao",
      coordinates: {"lat": 43.26271, "lng": -2.92528},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 347342 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-la-bonanova",
      name: "La Bonanova",
      coordinates: {"lat": 41.40585, "lng": 2.13243},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 25761 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-sevilla",
      name: "Sevilla",
      coordinates: {"lat": 37.38283, "lng": -5.97317},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 686741 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-moncada",
      name: "Moncada",
      coordinates: {"lat": 39.54555, "lng": -0.39551},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 21900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-granada",
      name: "Granada",
      coordinates: {"lat": 37.18817, "lng": -3.60667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 233532 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-santander",
      name: "Santander",
      coordinates: {"lat": 43.46589, "lng": -3.80493},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 173635 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-mieres",
      name: "Mieres",
      coordinates: {"lat": 43.25, "lng": -5.76667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 44070 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-iturrama",
      name: "Iturrama",
      coordinates: {"lat": 42.80847, "lng": -1.65825},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 24846 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-ciudad-universitaria",
      name: "Ciudad Universitaria",
      coordinates: {"lat": 40.45595, "lng": -3.73839},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 16364 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-toledo",
      name: "Toledo",
      coordinates: {"lat": 39.8581, "lng": -4.02263},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 86526 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-san-javier",
      name: "San Javier",
      coordinates: {"lat": 37.80626, "lng": -0.83736},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31432 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-orihuela",
      name: "Orihuela",
      coordinates: {"lat": 38.08483, "lng": -0.94401},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 101321 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-malaga",
      name: "Málaga",
      coordinates: {"lat": 36.72016, "lng": -4.42034},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 592346 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-las-palmas-de-gran-canaria",
      name: "Las Palmas de Gran Canaria",
      coordinates: {"lat": 28.10178, "lng": -15.41573},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 383516 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-jerez-de-la-frontera",
      name: "Jerez de la Frontera",
      coordinates: {"lat": 36.68645, "lng": -6.13606},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 212879 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-dos-hermanas",
      name: "Dos Hermanas",
      coordinates: {"lat": 37.28287, "lng": -5.92088},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 122943 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-ciudad-real",
      name: "Ciudad Real",
      coordinates: {"lat": 38.98626, "lng": -3.92907},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 74743 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-castello-de-la-plana",
      name: "Castelló de la Plana",
      coordinates: {"lat": 39.98567, "lng": -0.04935},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 171857 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-cartagena",
      name: "Cartagena",
      coordinates: {"lat": 37.60197, "lng": -0.98397},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 213943 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-almeria",
      name: "Almería",
      coordinates: {"lat": 36.83814, "lng": -2.45974},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 196851 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-zaragoza",
      name: "Zaragoza",
      coordinates: {"lat": 41.65606, "lng": -0.87734},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 686986 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-gasteiz-vitoria",
      name: "Gasteiz / Vitoria",
      coordinates: {"lat": 42.84998, "lng": -2.67268},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 257407 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-villanueva-de-la-canada",
      name: "Villanueva de la Cañada",
      coordinates: {"lat": 40.44689, "lng": -4.00428},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16804 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-tarrega",
      name: "Tàrrega",
      coordinates: {"lat": 41.64704, "lng": 1.13957},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16539 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-tarragona",
      name: "Tarragona",
      coordinates: {"lat": 41.11905, "lng": 1.24544},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 141542 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-pozuelo-de-alarcon",
      name: "Pozuelo de Alarcón",
      coordinates: {"lat": 40.43293, "lng": -3.81338},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 82428 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-palencia",
      name: "Palencia",
      coordinates: {"lat": 42.00955, "lng": -4.52406},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 78629 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-oviedo",
      name: "Oviedo",
      coordinates: {"lat": 43.36029, "lng": -5.84476},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 220027 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-mostoles",
      name: "Móstoles",
      coordinates: {"lat": 40.32234, "lng": -3.86496},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 207095 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-arrasate-mondragon",
      name: "Arrasate / Mondragón",
      coordinates: {"lat": 43.06441, "lng": -2.48977},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22019 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-logrono",
      name: "Logroño",
      coordinates: {"lat": 42.46615, "lng": -2.45115},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 151164 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-lleida",
      name: "Lleida",
      coordinates: {"lat": 41.61674, "lng": 0.62218},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 140797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-leon",
      name: "León",
      coordinates: {"lat": 42.60003, "lng": -5.57032},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 124772 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-leioa",
      name: "Leioa",
      coordinates: {"lat": 43.32686, "lng": -2.98884},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31197 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-leganes",
      name: "Leganés",
      coordinates: {"lat": 40.32718, "lng": -3.7635},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 188425 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-getafe",
      name: "Getafe",
      coordinates: {"lat": 40.30571, "lng": -3.73295},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 187525 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-girona",
      name: "Girona",
      coordinates: {"lat": 41.98311, "lng": 2.82493},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 100266 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-galapagar",
      name: "Galapagar",
      coordinates: {"lat": 40.5783, "lng": -4.00426},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31820 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-burgos",
      name: "Burgos",
      coordinates: {"lat": 42.34106, "lng": -3.70184},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 176418 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-avila",
      name: "Ávila",
      coordinates: {"lat": 40.65724, "lng": -4.69951},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 57657 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-eixample",
      name: "Eixample",
      coordinates: {"lat": 41.38896, "lng": 2.16179},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 266477 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-la-maternitat-i-sant-ramon",
      name: "la Maternitat i Sant Ramon",
      coordinates: {"lat": 41.38125, "lng": 2.11744},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24058 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-justicia",
      name: "Justicia",
      coordinates: {"lat": 40.42366, "lng": -3.69666},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18219 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-embajadores",
      name: "Embajadores",
      coordinates: {"lat": 40.40924, "lng": -3.70246},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 46204 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-arapiles",
      name: "Arapiles",
      coordinates: {"lat": 40.4344, "lng": -3.70803},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24190 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-palacio",
      name: "Palacio",
      coordinates: {"lat": 40.41542, "lng": -3.71407},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23501 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-castilla",
      name: "Castilla",
      coordinates: {"lat": 40.47431, "lng": -3.67972},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17046 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "espana-bellas-vistas",
      name: "Bellas Vistas",
      coordinates: {"lat": 40.45245, "lng": -3.70763},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 29355 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Spain",
  capital: "Madrid",
  currency: "EUR",
  language: "español",
  continent: "Europa",
  population: 49355143,
  cities,
  // Las universidades no van aqui: viven en ./universities/espana.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 96,
  aliases: ["espana", "spain"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
