// Filipinas — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "filipinas";
const countryName = "Filipinas";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/filipinas.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "filipinas-paco",
      name: "Paco",
      coordinates: {"lat": 14.588, "lng": 120.993},
      isCapital: false,
      universityCount: 30,
      statistics: { population: 79839 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-quezon-city",
      name: "Quezon City",
      coordinates: {"lat": 14.6488, "lng": 121.0509},
      isCapital: false,
      universityCount: 17,
      statistics: { population: 3084270 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-iloilo",
      name: "Iloilo",
      coordinates: {"lat": 10.69694, "lng": 122.56444},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 473728 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-davao",
      name: "Davao",
      coordinates: {"lat": 7.07306, "lng": 125.61278},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 1848947 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-cebu-city",
      name: "Cebu City",
      coordinates: {"lat": 10.31672, "lng": 123.89071},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 965332 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-bacolod-city",
      name: "Bacolod City",
      coordinates: {"lat": 10.66667, "lng": 122.95},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 454898 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-san-juan",
      name: "San Juan",
      coordinates: {"lat": 14.6, "lng": 121.0333},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 134312 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-quiapo",
      name: "Quiapo",
      coordinates: {"lat": 14.6, "lng": 120.9833},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 32236 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-zamboanga",
      name: "Zamboanga",
      coordinates: {"lat": 6.91028, "lng": 122.07389},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 1018849 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-roxas-city",
      name: "Roxas City",
      coordinates: {"lat": 11.58528, "lng": 122.75111},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 185236 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-pagadian",
      name: "Pagadian",
      coordinates: {"lat": 7.8257, "lng": 123.437},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 206483 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-naga",
      name: "Naga",
      coordinates: {"lat": 13.61917, "lng": 123.18139},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 174931 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-los-banos",
      name: "Los Baños",
      coordinates: {"lat": 14.17025, "lng": 121.24181},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 117030 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-dumaguete",
      name: "Dumaguete",
      coordinates: {"lat": 9.30646, "lng": 123.30769},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 113541 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-dagupan",
      name: "Dagupan",
      coordinates: {"lat": 16.04313, "lng": 120.33325},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 171271 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-cagayan-de-oro",
      name: "Cagayan de Oro",
      coordinates: {"lat": 8.48222, "lng": 124.64722},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 741617 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-cabuyao",
      name: "Cabuyao",
      coordinates: {"lat": 14.2726, "lng": 121.1262},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 308745 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-tuguegarao",
      name: "Tuguegarao",
      coordinates: {"lat": 17.61577, "lng": 121.72285},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 167297 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-tagbilaran-city",
      name: "Tagbilaran City",
      coordinates: {"lat": 9.65556, "lng": 123.85219},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 86411 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-santa-cruz-1688216",
      name: "Santa Cruz",
      coordinates: {"lat": 14.6, "lng": 120.98333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 126735 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-port-area",
      name: "Port Area",
      coordinates: {"lat": 14.58945, "lng": 120.96698},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 72605 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-pasay",
      name: "Pasay",
      coordinates: {"lat": 14.53748, "lng": 121.00144},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 416522 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-manila",
      name: "Manila",
      coordinates: {"lat": 14.6042, "lng": 120.9822},
      isCapital: true,
      universityCount: 5,
      statistics: { population: 1600000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-lipa-city",
      name: "Lipa City",
      coordinates: {"lat": 13.9411, "lng": 121.1631},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 212287 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-dasmarinas",
      name: "Dasmariñas",
      coordinates: {"lat": 14.32944, "lng": 120.93667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 441876 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-cabanatuan-city",
      name: "Cabanatuan City",
      coordinates: {"lat": 15.48586, "lng": 120.96648},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 343672 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-baguio",
      name: "Baguio",
      coordinates: {"lat": 16.41639, "lng": 120.59306},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 272714 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-vigan",
      name: "Vigan",
      coordinates: {"lat": 17.57472, "lng": 120.38694},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 48545 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-teresa",
      name: "Teresa",
      coordinates: {"lat": 14.5612, "lng": 121.2195},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 34716 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-santa-rosa",
      name: "Santa Rosa",
      coordinates: {"lat": 14.31222, "lng": 121.11139},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 216650 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-passi",
      name: "Passi",
      coordinates: {"lat": 11.10778, "lng": 122.64194},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 42794 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-ozamiz-city",
      name: "Ozamiz City",
      coordinates: {"lat": 8.1481, "lng": 123.8405},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 93082 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-iligan",
      name: "Iligan",
      coordinates: {"lat": 8.2289, "lng": 124.24344},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 342618 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-general-santos",
      name: "General Santos",
      coordinates: {"lat": 6.11278, "lng": 125.17167},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 722059 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-upper-bicutan",
      name: "Upper Bicutan",
      coordinates: {"lat": 14.4996, "lng": 121.0507},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 47397 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-bel-air",
      name: "Bel Air",
      coordinates: {"lat": 14.5594, "lng": 121.0258},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 36007 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-pasig-city",
      name: "Pasig City",
      coordinates: {"lat": 14.58691, "lng": 121.0614},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 853050 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-urdaneta",
      name: "Urdaneta",
      coordinates: {"lat": 15.97611, "lng": 120.57111},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 145935 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-pulong-santa-cruz",
      name: "Pulong Santa Cruz",
      coordinates: {"lat": 14.27324, "lng": 121.07643},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 126844 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-paranaque-city",
      name: "Paranaque City",
      coordinates: {"lat": 14.48156, "lng": 121.01749},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 703245 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-marikina-city",
      name: "Marikina City",
      coordinates: {"lat": 14.6481, "lng": 121.1133},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 471323 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-las-pinas",
      name: "Las Piñas",
      coordinates: {"lat": 14.45056, "lng": 120.98278},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 615549 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-laoag",
      name: "Laoag",
      coordinates: {"lat": 18.1978, "lng": 120.5957},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 112117 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-kalibo",
      name: "Kalibo",
      coordinates: {"lat": 11.7086, "lng": 122.3648},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 93218 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-dipolog",
      name: "Dipolog",
      coordinates: {"lat": 8.56697, "lng": 123.33471},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 93549 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-cotabato",
      name: "Cotabato",
      coordinates: {"lat": 7.22361, "lng": 124.24639},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 383383 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-calamba",
      name: "Calamba",
      coordinates: {"lat": 14.21167, "lng": 121.16528},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 575046 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-batangas",
      name: "Batangas",
      coordinates: {"lat": 13.7567, "lng": 121.0584},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 237370 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-balanga",
      name: "Balanga",
      coordinates: {"lat": 14.67611, "lng": 120.53611},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 72954 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-bagong-pagasa",
      name: "Bagong Pagasa",
      coordinates: {"lat": 14.6627, "lng": 121.0328},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 29389 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-tarlac-city",
      name: "Tarlac City",
      coordinates: {"lat": 15.48017, "lng": 120.59794},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 401892 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-tanjay",
      name: "Tanjay",
      coordinates: {"lat": 9.5162, "lng": 123.158},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84593 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-tacurong",
      name: "Tacurong",
      coordinates: {"lat": 6.6925, "lng": 124.67639},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 116945 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-tacloban",
      name: "Tacloban",
      coordinates: {"lat": 11.24333, "lng": 125.00472},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 259353 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-surallah",
      name: "Surallah",
      coordinates: {"lat": 6.37527, "lng": 124.74521},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 91412 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-silang",
      name: "Silang",
      coordinates: {"lat": 14.21567, "lng": 120.97137},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 119475 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-santiago",
      name: "Santiago",
      coordinates: {"lat": 16.68808, "lng": 121.5487},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 108414 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-santa-cruz-1688253",
      name: "Santa Cruz",
      coordinates: {"lat": 14.2814, "lng": 121.4161},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 108145 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-san-pedro",
      name: "San Pedro",
      coordinates: {"lat": 14.3595, "lng": 121.0473},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 348968 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-san-jose",
      name: "San Jose",
      coordinates: {"lat": 12.35275, "lng": 121.06761},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 143495 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-san-ildefonso",
      name: "San Ildefonso",
      coordinates: {"lat": 15.0809, "lng": 120.941},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 65669 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-puerto-princesa",
      name: "Puerto Princesa",
      coordinates: {"lat": 9.73917, "lng": 118.73528},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 222673 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-patuto",
      name: "Patuto",
      coordinates: {"lat": 14.11667, "lng": 120.96667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 52883 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-olongapo",
      name: "Olongapo",
      coordinates: {"lat": 14.82917, "lng": 120.28278},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 221178 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-midsayap",
      name: "Midsayap",
      coordinates: {"lat": 7.19083, "lng": 124.53028},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 117365 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-marawi-city",
      name: "Marawi City",
      coordinates: {"lat": 8.0034, "lng": 124.28395},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 259993 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-maasin",
      name: "Maasin",
      coordinates: {"lat": 10.13272, "lng": 124.84082},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18313 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-lingayen",
      name: "Lingayen",
      coordinates: {"lat": 16.02182, "lng": 120.23194},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56580 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-legaspi",
      name: "Legaspi",
      coordinates: {"lat": 13.14125, "lng": 123.74073},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 179481 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-la-trinidad",
      name: "La Trinidad",
      coordinates: {"lat": 16.455, "lng": 120.5875},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 142925 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-kidapawan",
      name: "Kidapawan",
      coordinates: {"lat": 7.00833, "lng": 125.08944},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 79652 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-jolo",
      name: "Jolo",
      coordinates: {"lat": 6.05222, "lng": 121.00222},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 101002 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-jasaan",
      name: "Jasaan",
      coordinates: {"lat": 8.65417, "lng": 124.75556},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16435 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-iriga-city",
      name: "Iriga City",
      coordinates: {"lat": 13.4324, "lng": 123.4115},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 115306 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-indang",
      name: "Indang",
      coordinates: {"lat": 14.19528, "lng": 120.87694},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 70092 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-ilagan",
      name: "Ilagan",
      coordinates: {"lat": 17.14854, "lng": 121.88924},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 164020 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-guyong",
      name: "Guyong",
      coordinates: {"lat": 14.8361, "lng": 120.97844},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 155391 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-general-trias",
      name: "General Trias",
      coordinates: {"lat": 14.38694, "lng": 120.88167},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 96022 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-digos",
      name: "Digos",
      coordinates: {"lat": 6.74972, "lng": 125.35722},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 116122 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-del-pilar",
      name: "Del Pilar",
      coordinates: {"lat": 15.03601, "lng": 120.69935},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 37329 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-dapitan",
      name: "Dapitan",
      coordinates: {"lat": 8.6561, "lng": 123.4227},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 87699 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-daet",
      name: "Daet",
      coordinates: {"lat": 14.1122, "lng": 122.9553},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 78142 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-catanauan",
      name: "Catanauan",
      coordinates: {"lat": 13.5926, "lng": 122.3215},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 26804 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-carmona",
      name: "Carmona",
      coordinates: {"lat": 14.3132, "lng": 121.0576},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 112140 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-caloocan",
      name: "Caloocan",
      coordinates: {"lat": 14.64953, "lng": 120.96788},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1712945 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-calauan",
      name: "Calauan",
      coordinates: {"lat": 14.14989, "lng": 121.3152},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 89670 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-butuan",
      name: "Butuan",
      coordinates: {"lat": 8.94917, "lng": 125.54361},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 309709 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-bislig",
      name: "Bislig",
      coordinates: {"lat": 8.21528, "lng": 126.31639},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 99872 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-binan",
      name: "Biñan",
      coordinates: {"lat": 14.34267, "lng": 121.08071},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 300000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-baybay",
      name: "Baybay",
      coordinates: {"lat": 10.6785, "lng": 124.8006},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17668 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-bangued",
      name: "Bangued",
      coordinates: {"lat": 17.60833, "lng": 120.63806},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48331 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-bagong-barrio",
      name: "Bagong Barrio",
      coordinates: {"lat": 14.66638, "lng": 120.99322},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 77490 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-baclaran",
      name: "Baclaran",
      coordinates: {"lat": 14.53194, "lng": 120.99417},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33850 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-angeles-city",
      name: "Angeles City",
      coordinates: {"lat": 15.15, "lng": 120.58333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 483452 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-commonwealth",
      name: "Commonwealth",
      coordinates: {"lat": 14.6969, "lng": 121.08006},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 215034 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-poblacion",
      name: "Poblacion",
      coordinates: {"lat": 14.3787, "lng": 121.025},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 124554 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "filipinas-mandaluyong",
      name: "Mandaluyong",
      coordinates: {"lat": 14.57837, "lng": 121.03522},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 425000 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Philippines",
  capital: "Manila",
  currency: "PHP",
  language: "tagalo",
  continent: "Asia",
  population: 116786962,
  cities,
  // Las universidades no van aqui: viven en ./universities/filipinas.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 118,
  aliases: ["filipinas", "philippines"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
