// Francia — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "francia";
const countryName = "Francia";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/francia.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "francia-paris-05-pantheon",
      name: "Paris 05 Panthéon",
      coordinates: {"lat": 48.8448, "lng": 2.3471},
      isCapital: false,
      universityCount: 20,
      statistics: { population: 55252 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-toulouse",
      name: "Toulouse",
      coordinates: {"lat": 43.60426, "lng": 1.44367},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 511684 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-montpellier",
      name: "Montpellier",
      coordinates: {"lat": 43.61093, "lng": 3.87635},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 248252 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-strasbourg",
      name: "Strasbourg",
      coordinates: {"lat": 48.58392, "lng": 7.74553},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 274845 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-talence",
      name: "Talence",
      coordinates: {"lat": 44.80849, "lng": -0.58915},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 42579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-saint-martin-d-heres",
      name: "Saint-Martin-d'Hères",
      coordinates: {"lat": 45.1787, "lng": 5.76281},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 35528 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-nancy",
      name: "Nancy",
      coordinates: {"lat": 48.68439, "lng": 6.18496},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 105058 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-paris-06-luxembourg",
      name: "Paris 06 Luxembourg",
      coordinates: {"lat": 48.8493, "lng": 2.33},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 40389 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-clermont-ferrand",
      name: "Clermont-Ferrand",
      coordinates: {"lat": 45.77969, "lng": 3.08682},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 147865 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-brest",
      name: "Brest",
      coordinates: {"lat": 48.39029, "lng": -4.48628},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 144899 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-paris",
      name: "Paris",
      coordinates: {"lat": 48.85341, "lng": 2.3488},
      isCapital: true,
      universityCount: 6,
      statistics: { population: 2138551 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-orsay",
      name: "Orsay",
      coordinates: {"lat": 48.69572, "lng": 2.18727},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 17817 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-gare",
      name: "Gare",
      coordinates: {"lat": 48.83337, "lng": 2.37513},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 75580 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-nanterre",
      name: "Nanterre",
      coordinates: {"lat": 48.89198, "lng": 2.20675},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 86719 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-metz",
      name: "Metz",
      coordinates: {"lat": 49.11911, "lng": 6.17269},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 123914 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-cesson-sevigne",
      name: "Cesson-Sévigné",
      coordinates: {"lat": 48.1212, "lng": -1.603},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 16222 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-besancon",
      name: "Besançon",
      coordinates: {"lat": 47.24878, "lng": 6.01815},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 128426 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-angers",
      name: "Angers",
      coordinates: {"lat": 47.47156, "lng": -0.55202},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 168279 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-vand-uvre-les-nancy",
      name: "Vandœuvre-lès-Nancy",
      coordinates: {"lat": 48.66115, "lng": 6.17114},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 31785 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-valenciennes",
      name: "Valenciennes",
      coordinates: {"lat": 50.35909, "lng": 3.52506},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 44821 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-rennes",
      name: "Rennes",
      coordinates: {"lat": 48.11109, "lng": -1.67431},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 227830 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-reims",
      name: "Reims",
      coordinates: {"lat": 49.26526, "lng": 4.02853},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 196565 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-villeneuve-d-ascq",
      name: "Villeneuve-d'Ascq",
      coordinates: {"lat": 50.61669, "lng": 3.16664},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 62400 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-lyon-02",
      name: "Lyon 02",
      coordinates: {"lat": 45.75423, "lng": 4.83089},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 31303 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-marseille-02",
      name: "Marseille 02",
      coordinates: {"lat": 43.29664, "lng": 5.37034},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 25779 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-villeurbanne",
      name: "Villeurbanne",
      coordinates: {"lat": 45.76601, "lng": 4.8795},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 131445 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-pessac",
      name: "Pessac",
      coordinates: {"lat": 44.80565, "lng": -0.6324},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 57944 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-paris-16-passy",
      name: "Paris 16 Passy",
      coordinates: {"lat": 48.8637, "lng": 2.2769},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 159386 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-nice",
      name: "Nice",
      coordinates: {"lat": 43.70313, "lng": 7.26608},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 342669 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-mont-saint-aignan",
      name: "Mont-Saint-Aignan",
      coordinates: {"lat": 49.46307, "lng": 1.09364},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 23078 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-lille",
      name: "Lille",
      coordinates: {"lat": 50.63391, "lng": 3.05512},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 238695 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-douai",
      name: "Douai",
      coordinates: {"lat": 50.37069, "lng": 3.07922},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 46531 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-aix-en-provence",
      name: "Aix-en-Provence",
      coordinates: {"lat": 43.5283, "lng": 5.44973},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 146821 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-versailles",
      name: "Versailles",
      coordinates: {"lat": 48.80359, "lng": 2.13424},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 85416 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-velizy-villacoublay",
      name: "Vélizy-Villacoublay",
      coordinates: {"lat": 48.78198, "lng": 2.19395},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21741 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-paris-15-vaugirard",
      name: "Paris 15 Vaugirard",
      coordinates: {"lat": 48.8412, "lng": 2.3003},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 229713 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-vannes",
      name: "Vannes",
      coordinates: {"lat": 47.65688, "lng": -2.76205},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 54020 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-tarbes",
      name: "Tarbes",
      coordinates: {"lat": 43.23407, "lng": 0.07139},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 52106 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-saint-etienne",
      name: "Saint-Étienne",
      coordinates: {"lat": 45.43389, "lng": 4.39},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 176280 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-saint-denis",
      name: "Saint-Denis",
      coordinates: {"lat": 48.93564, "lng": 2.35387},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 96128 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-pierrefitte-sur-seine",
      name: "Pierrefitte-sur-Seine",
      coordinates: {"lat": 48.96691, "lng": 2.36104},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27914 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-paris-07-palais-bourbon",
      name: "Paris 07 Palais-Bourbon",
      coordinates: {"lat": 48.8565, "lng": 2.321},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48015 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-olivet",
      name: "Olivet",
      coordinates: {"lat": 47.86219, "lng": 1.8991},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22604 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-mulhouse",
      name: "Mulhouse",
      coordinates: {"lat": 47.75205, "lng": 7.32866},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 111430 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-le-mans",
      name: "Le Mans",
      coordinates: {"lat": 48.0021, "lng": 0.20251},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 144515 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-le-havre",
      name: "Le Havre",
      coordinates: {"lat": 49.49346, "lng": 0.10785},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 185972 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-grenoble",
      name: "Grenoble",
      coordinates: {"lat": 45.17869, "lng": 5.71479},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 158552 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-creteil",
      name: "Créteil",
      coordinates: {"lat": 48.79266, "lng": 2.46569},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84833 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-champs-sur-marne",
      name: "Champs-sur-Marne",
      coordinates: {"lat": 48.85, "lng": 2.6},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27776 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-caen",
      name: "Caen",
      coordinates: {"lat": 49.18585, "lng": -0.35912},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 110624 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-boulogne-billancourt",
      name: "Boulogne-Billancourt",
      coordinates: {"lat": 48.83545, "lng": 2.24128},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 108782 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-balma",
      name: "Balma",
      coordinates: {"lat": 43.61111, "lng": 1.49944},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15553 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-amiens",
      name: "Amiens",
      coordinates: {"lat": 49.9, "lng": 2.3},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 143086 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-marseille-01",
      name: "Marseille 01",
      coordinates: {"lat": 43.29814, "lng": 5.38407},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 40919 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-marseille-07",
      name: "Marseille 07",
      coordinates: {"lat": 43.28289, "lng": 5.36021},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 35981 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-cergy-pontoise",
      name: "Cergy-Pontoise",
      coordinates: {"lat": 49.03894, "lng": 2.07805},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 183430 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-picpus",
      name: "Picpus",
      coordinates: {"lat": 48.84258, "lng": 2.40014},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 61920 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "francia-paris-12e-arrondissement",
      name: "Paris 12e Arrondissement",
      coordinates: {"lat": 48.83523, "lng": 2.43505},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 140311 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "France",
  capital: "Paris",
  currency: "EUR",
  language: "francés",
  continent: "Europa",
  population: 68720337,
  cities,
  // Las universidades no van aqui: viven en ./universities/francia.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 294,
  aliases: ["france", "francia"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
