// India — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "india";
const countryName = "India";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/india.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "india-bengaluru",
      name: "Bengaluru",
      coordinates: {"lat": 12.97194, "lng": 77.59369},
      isCapital: false,
      universityCount: 42,
      statistics: { population: 8495492 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jaipur",
      name: "Jaipur",
      coordinates: {"lat": 26.91962, "lng": 75.78781},
      isCapital: false,
      universityCount: 31,
      statistics: { population: 3046163 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hyderabad",
      name: "Hyderabad",
      coordinates: {"lat": 17.38405, "lng": 78.45636},
      isCapital: false,
      universityCount: 30,
      statistics: { population: 6993262 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-new-delhi",
      name: "New Delhi",
      coordinates: {"lat": 28.62137, "lng": 77.2148},
      isCapital: true,
      universityCount: 25,
      statistics: { population: 317797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-lucknow",
      name: "Lucknow",
      coordinates: {"lat": 26.83928, "lng": 80.92313},
      isCapital: false,
      universityCount: 25,
      statistics: { population: 2472011 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-pune",
      name: "Pune",
      coordinates: {"lat": 18.51957, "lng": 73.85535},
      isCapital: false,
      universityCount: 20,
      statistics: { population: 3124458 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bhubaneswar",
      name: "Bhubaneswar",
      coordinates: {"lat": 20.27241, "lng": 85.83385},
      isCapital: false,
      universityCount: 19,
      statistics: { population: 885363 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ahmedabad",
      name: "Ahmedabad",
      coordinates: {"lat": 23.02579, "lng": 72.58727},
      isCapital: false,
      universityCount: 18,
      statistics: { population: 6357693 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ranchi",
      name: "Ranchi",
      coordinates: {"lat": 23.34316, "lng": 85.3094},
      isCapital: false,
      universityCount: 17,
      statistics: { population: 1120374 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-gandhinagar",
      name: "Gandhinagar",
      coordinates: {"lat": 23.21667, "lng": 72.68333},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 292797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dehradun",
      name: "Dehradun",
      coordinates: {"lat": 30.32443, "lng": 78.03392},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 522081 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jabalpur",
      name: "Jabalpur",
      coordinates: {"lat": 23.16697, "lng": 79.95006},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 1081677 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mumbai",
      name: "Mumbai",
      coordinates: {"lat": 19.07283, "lng": 72.88261},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 12691836 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bhopal",
      name: "Bhopal",
      coordinates: {"lat": 23.25469, "lng": 77.40289},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 1798218 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-greater-noida",
      name: "Greater Noida",
      coordinates: {"lat": 28.49615, "lng": 77.53601},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 293908 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kolkata",
      name: "Kolkata",
      coordinates: {"lat": 22.56263, "lng": 88.36304},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 4631392 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-patna",
      name: "Patna",
      coordinates: {"lat": 25.59408, "lng": 85.13563},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 1684297 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-imphal",
      name: "Imphal",
      coordinates: {"lat": 24.80805, "lng": 93.9442},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 277196 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shivaji-nagar",
      name: "Shivaji Nagar",
      coordinates: {"lat": 18.53017, "lng": 73.85263},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 1000000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-udaipur",
      name: "Udaipur",
      coordinates: {"lat": 24.58584, "lng": 73.71346},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 451100 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-thrissur",
      name: "Thrissur",
      coordinates: {"lat": 10.51667, "lng": 76.21667},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 315957 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-guwahati",
      name: "Guwahati",
      coordinates: {"lat": 26.1844, "lng": 91.7458},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 962334 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-prayagraj",
      name: "Prayagraj",
      coordinates: {"lat": 25.44478, "lng": 81.84322},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 1073438 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nagpur",
      name: "Nagpur",
      coordinates: {"lat": 21.14631, "lng": 79.08491},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 2405665 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mysuru",
      name: "Mysuru",
      coordinates: {"lat": 12.29791, "lng": 76.63925},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 920550 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chennai",
      name: "Chennai",
      coordinates: {"lat": 13.08784, "lng": 80.27847},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 4681087 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kalpatta",
      name: "Kalpatta",
      coordinates: {"lat": 11.60871, "lng": 76.08343},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 31580 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-delhi",
      name: "Delhi",
      coordinates: {"lat": 28.65195, "lng": 77.23149},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 11034555 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kolar-13353619",
      name: "Kolar",
      coordinates: {"lat": 23.16478, "lng": 77.41893},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 87882 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-yelahanka",
      name: "Yelahanka",
      coordinates: {"lat": 13.10073, "lng": 77.59632},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 116447 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-thiruvananthapuram",
      name: "Thiruvananthapuram",
      coordinates: {"lat": 8.4855, "lng": 76.94924},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 788271 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rajkot",
      name: "Rājkot",
      coordinates: {"lat": 22.29161, "lng": 70.79322},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 1390640 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-raipur-1258980",
      name: "Raipur",
      coordinates: {"lat": 21.23333, "lng": 81.63333},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 1027264 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jorhat",
      name: "Jorhat",
      coordinates: {"lat": 26.75751, "lng": 94.20306},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 126736 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dam-dam",
      name: "Dam Dam",
      coordinates: {"lat": 22.63341, "lng": 88.42286},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 122719 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sholinganallur",
      name: "Sholinganallur",
      coordinates: {"lat": 12.88996, "lng": 80.23127},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 35602 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rourkela",
      name: "Rourkela",
      coordinates: {"lat": 22.22496, "lng": 84.86414},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 273317 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kanke",
      name: "Kānke",
      coordinates: {"lat": 23.43478, "lng": 85.32059},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 17560 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hubballi",
      name: "Hubballi",
      coordinates: {"lat": 15.34776, "lng": 75.13378},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 943788 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-gwalior",
      name: "Gwalior",
      coordinates: {"lat": 26.22983, "lng": 78.17337},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 1054420 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dharavi",
      name: "Dhārāvi",
      coordinates: {"lat": 19.05, "lng": 72.86667},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 700000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bikaner",
      name: "Bikaner",
      coordinates: {"lat": 28.01762, "lng": 73.31495},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 644406 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-thanesar",
      name: "Thānesar",
      coordinates: {"lat": 29.97323, "lng": 76.83214},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 155152 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-surat",
      name: "Surat",
      coordinates: {"lat": 21.19594, "lng": 72.83023},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 4591246 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-solan",
      name: "Solan",
      coordinates: {"lat": 30.90908, "lng": 77.10869},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 40283 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-roorkee",
      name: "Roorkee",
      coordinates: {"lat": 29.86632, "lng": 77.89118},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 103894 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rohtak",
      name: "Rohtak",
      coordinates: {"lat": 28.89447, "lng": 76.58917},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 374292 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ramnagar",
      name: "Rāmnagar",
      coordinates: {"lat": 25.26907, "lng": 83.02971},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 44277 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jamshedpur",
      name: "Jamshedpur",
      coordinates: {"lat": 22.80278, "lng": 86.18545},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1339438 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-indore",
      name: "Indore",
      coordinates: {"lat": 22.71792, "lng": 75.8333},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1994397 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-gangtok",
      name: "Gangtok",
      coordinates: {"lat": 27.32574, "lng": 88.61216},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 100286 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-cuttack",
      name: "Cuttack",
      coordinates: {"lat": 20.46497, "lng": 85.87927},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 610189 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bolpur",
      name: "Bolpur",
      coordinates: {"lat": 23.66278, "lng": 87.69695},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 70998 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-alandur",
      name: "Alandur",
      coordinates: {"lat": 13.0025, "lng": 80.20611},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 164430 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bagru",
      name: "Bagru",
      coordinates: {"lat": 26.81067, "lng": 75.54702},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 31229 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kundli",
      name: "Kundli",
      coordinates: {"lat": 28.86913, "lng": 77.12061},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 21633 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-warangal",
      name: "Warangal",
      coordinates: {"lat": 18.0, "lng": 79.58333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 704570 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vadodara",
      name: "Vadodara",
      coordinates: {"lat": 22.29941, "lng": 73.20812},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1822221 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-patiala",
      name: "Patiāla",
      coordinates: {"lat": 30.33625, "lng": 76.3922},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 446246 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-north-guwahati",
      name: "North Guwāhāti",
      coordinates: {"lat": 26.19749, "lng": 91.7202},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 17516 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nashik",
      name: "Nashik",
      coordinates: {"lat": 19.99727, "lng": 73.79096},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1486053 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-meerut",
      name: "Meerut",
      coordinates: {"lat": 28.98002, "lng": 77.70636},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1223184 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-medinipur",
      name: "Medinīpur",
      coordinates: {"lat": 22.42114, "lng": 87.32257},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 153349 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-latur",
      name: "Latur",
      coordinates: {"lat": 18.39721, "lng": 76.56784},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 382940 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kukatpally",
      name: "Kukatpally",
      coordinates: {"lat": 17.48486, "lng": 78.41376},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 341709 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kozhikode",
      name: "Kozhikode",
      coordinates: {"lat": 11.24802, "lng": 75.7804},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 550440 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kota",
      name: "Kota",
      coordinates: {"lat": 25.18254, "lng": 75.83907},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1001694 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-khadki",
      name: "Khadki",
      coordinates: {"lat": 18.5635, "lng": 73.85205},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 75654 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kanpur",
      name: "Kanpur",
      coordinates: {"lat": 26.46523, "lng": 80.34975},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 2823249 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-junagadh",
      name: "Jūnāgadh",
      coordinates: {"lat": 21.51966, "lng": 70.45981},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 319462 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hajipur",
      name: "Hājīpur",
      coordinates: {"lat": 25.68544, "lng": 85.20981},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 147688 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-gurugram",
      name: "Gurugram",
      coordinates: {"lat": 28.4601, "lng": 77.02635},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 886519 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-gorakhpur",
      name: "Gorakhpur",
      coordinates: {"lat": 26.76628, "lng": 83.36889},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 674246 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-delhi-cantonment",
      name: "Delhi Cantonment",
      coordinates: {"lat": 28.6, "lng": 77.13333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 110351 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bilaspur",
      name: "Bilāspur",
      coordinates: {"lat": 22.08005, "lng": 82.15543},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 365579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bareilly",
      name: "Bareilly",
      coordinates: {"lat": 28.36678, "lng": 79.43167},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 745435 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-anantapur",
      name: "Anantapur",
      coordinates: {"lat": 14.67784, "lng": 77.60813},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 267161 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mohali",
      name: "Mohali",
      coordinates: {"lat": 30.67995, "lng": 76.72211},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 166864 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-naharlagun",
      name: "Naharlagun",
      coordinates: {"lat": 27.10467, "lng": 93.69518},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 36158 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tighri",
      name: "Tighri",
      coordinates: {"lat": 28.51225, "lng": 77.24083},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 46974 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-saiyad-ul-ajaib",
      name: "Saiyad-ul-ajaib",
      coordinates: {"lat": 28.51923, "lng": 77.20352},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 17914 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-othukkungal",
      name: "Othukkungal",
      coordinates: {"lat": 11.0283, "lng": 76.02903},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 39139 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vizianagaram",
      name: "Vizianagaram",
      coordinates: {"lat": 18.11692, "lng": 83.41148},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 228720 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vepagunta",
      name: "Vepagunta",
      coordinates: {"lat": 17.77844, "lng": 83.21577},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 26881 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-varanasi",
      name: "Varanasi",
      coordinates: {"lat": 25.31668, "lng": 83.01041},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 1164404 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-uppal-kalan",
      name: "Uppal Kalan",
      coordinates: {"lat": 17.40577, "lng": 78.55911},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 118259 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ujjain",
      name: "Ujjain",
      coordinates: {"lat": 23.18239, "lng": 75.77643},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 515215 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tirupati",
      name: "Tirupati",
      coordinates: {"lat": 13.63551, "lng": 79.41989},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 295323 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-srinagar-1255634",
      name: "Srinagar",
      coordinates: {"lat": 34.08565, "lng": 74.80555},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 1206419 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shimla",
      name: "Shimla",
      coordinates: {"lat": 31.10442, "lng": 77.16662},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 173503 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-silchar",
      name: "Silchar",
      coordinates: {"lat": 24.82733, "lng": 92.79787},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 178865 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shillong",
      name: "Shillong",
      coordinates: {"lat": 25.56892, "lng": 91.88313},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 143229 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ratu",
      name: "Rātu",
      coordinates: {"lat": 23.42045, "lng": 85.21459},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 22379 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-pethapur",
      name: "Pethāpur",
      coordinates: {"lat": 23.26307, "lng": 72.67386},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 23497 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-pathanamthitta",
      name: "Pathanāmthitta",
      coordinates: {"lat": 9.26667, "lng": 76.78333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 38285 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-palakkad",
      name: "Palakkad",
      coordinates: {"lat": 10.77319, "lng": 76.65366},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 132728 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nagaon",
      name: "Nagaon",
      coordinates: {"lat": 26.35, "lng": 92.66667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 121628 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-murshidabad",
      name: "Murshidābād",
      coordinates: {"lat": 24.1839, "lng": 88.27171},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 39557 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-moradabad",
      name: "Morādābād",
      coordinates: {"lat": 28.83893, "lng": 78.77684},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 721139 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-manoharpur",
      name: "Manoharpur",
      coordinates: {"lat": 27.29769, "lng": 75.9495},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 28928 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mangaluru",
      name: "Mangaluru",
      coordinates: {"lat": 12.91723, "lng": 74.85603},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 499487 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kurnool",
      name: "Kurnool",
      coordinates: {"lat": 15.82887, "lng": 78.03602},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 460184 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kokrajhar",
      name: "Kokrajhar",
      coordinates: {"lat": 26.40107, "lng": 90.27286},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 34136 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kharakvasla",
      name: "Kharakvasla",
      coordinates: {"lat": 18.43997, "lng": 73.77545},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 78684 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kalka",
      name: "Kālka",
      coordinates: {"lat": 30.83982, "lng": 76.94065},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 34134 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jodhpur",
      name: "Jodhpur",
      coordinates: {"lat": 26.26841, "lng": 73.00594},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 1056191 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jhargram",
      name: "Jhārgrām",
      coordinates: {"lat": 22.45384, "lng": 86.99497},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 57796 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jalpaiguri",
      name: "Jalpāiguri",
      coordinates: {"lat": 26.51667, "lng": 88.73333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 107832 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hisar",
      name: "Hisar",
      coordinates: {"lat": 29.15394, "lng": 75.72294},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 307024 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-haridwar",
      name: "Haridwar",
      coordinates: {"lat": 29.94791, "lng": 78.16025},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 186079 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-durg",
      name: "Durg",
      coordinates: {"lat": 21.19147, "lng": 81.27619},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 268806 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dibrugarh",
      name: "Dibrugarh",
      coordinates: {"lat": 27.47989, "lng": 94.90837},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 145488 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dharamsala",
      name: "Dharamsala",
      coordinates: {"lat": 32.22006, "lng": 76.32013},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 30764 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-darbhanga",
      name: "Darbhanga",
      coordinates: {"lat": 26.15216, "lng": 85.89707},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 296039 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-coimbatore",
      name: "Coimbatore",
      coordinates: {"lat": 11.00555, "lng": 76.96612},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 2136916 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bhagalpur",
      name: "Bhāgalpur",
      coordinates: {"lat": 25.24446, "lng": 86.97183},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 400146 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bankura",
      name: "Bānkura",
      coordinates: {"lat": 23.23241, "lng": 87.0716},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 133966 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-aizawl",
      name: "Aizawl",
      coordinates: {"lat": 23.72894, "lng": 92.71791},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 293416 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-powai",
      name: "Powai",
      coordinates: {"lat": 19.1164, "lng": 72.90471},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 20000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-thodupuzha",
      name: "Thodupuzha",
      coordinates: {"lat": 9.89394, "lng": 76.72216},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 52045 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hashtsal",
      name: "Hashtsāl",
      coordinates: {"lat": 28.63406, "lng": 77.05771},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 176877 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kakkodi",
      name: "Kakkodi",
      coordinates: {"lat": 11.31973, "lng": 75.80146},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 42866 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nandri",
      name: "Nandri",
      coordinates: {"lat": 26.31157, "lng": 73.10087},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 20827 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vallam",
      name: "Vallam",
      coordinates: {"lat": 10.71988, "lng": 79.05981},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 16758 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vaghodia",
      name: "Vāghodia",
      coordinates: {"lat": 22.30505, "lng": 73.40016},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 16604 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-uran",
      name: "Uran",
      coordinates: {"lat": 18.87813, "lng": 72.93924},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 30439 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-udhampur",
      name: "Udhampur",
      coordinates: {"lat": 32.92431, "lng": 75.13573},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 84015 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tiruchirappalli",
      name: "Tiruchirappalli",
      coordinates: {"lat": 10.8155, "lng": 78.69651},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1022518 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tezpur",
      name: "Tezpur",
      coordinates: {"lat": 26.63333, "lng": 92.8},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 75540 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sonipat",
      name: "Sonīpat",
      coordinates: {"lat": 28.99478, "lng": 77.01937},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 289333 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sohna",
      name: "Sohna",
      coordinates: {"lat": 28.24737, "lng": 77.06544},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 36552 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shoranur",
      name: "Shōranūr",
      coordinates: {"lat": 10.76181, "lng": 76.27078},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 43533 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-purnia",
      name: "Purnia",
      coordinates: {"lat": 25.77895, "lng": 87.47422},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 282248 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-piravam",
      name: "Piravam",
      coordinates: {"lat": 9.86667, "lng": 76.5},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 28254 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-perintalmanna",
      name: "Perintalmanna",
      coordinates: {"lat": 10.97724, "lng": 76.22541},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 49723 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-panvel",
      name: "Panvel",
      coordinates: {"lat": 18.98878, "lng": 73.11013},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 195373 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-north-lakhimpur",
      name: "North Lakhimpur",
      coordinates: {"lat": 27.23517, "lng": 94.10357},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 59841 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nedumangad",
      name: "Nedumangād",
      coordinates: {"lat": 8.60267, "lng": 77.00139},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 60161 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mussoorie",
      name: "Mussoorie",
      coordinates: {"lat": 30.45498, "lng": 78.07068},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 25753 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mulki",
      name: "Mūlki",
      coordinates: {"lat": 13.09101, "lng": 74.79353},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 17274 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mhow",
      name: "Mhow",
      coordinates: {"lat": 22.5589, "lng": 75.76543},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 81702 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-medchal",
      name: "Medchal",
      coordinates: {"lat": 17.62972, "lng": 78.48139},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 35611 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-manjeri",
      name: "Manjeri",
      coordinates: {"lat": 11.12018, "lng": 76.11996},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 97102 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-madurai",
      name: "Madurai",
      coordinates: {"lat": 9.919, "lng": 78.11953},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1465625 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-machilipatnam",
      name: "Machilīpatnam",
      coordinates: {"lat": 16.18747, "lng": 81.13888},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 192827 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-krishnanagar",
      name: "Krishnanagar",
      coordinates: {"lat": 23.40576, "lng": 88.49073},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 145926 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kottayam",
      name: "Kottayam",
      coordinates: {"lat": 9.58692, "lng": 76.52132},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 55374 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kohima",
      name: "Kohima",
      coordinates: {"lat": 25.67467, "lng": 94.11099},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 99039 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-koch-bihar",
      name: "Koch Bihār",
      coordinates: {"lat": 26.32539, "lng": 89.44508},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 78737 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-khatra",
      name: "Khātra",
      coordinates: {"lat": 22.97617, "lng": 86.85462},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 16484 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kharagpur",
      name: "Kharagpur",
      coordinates: {"lat": 22.33971, "lng": 87.32501},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 219665 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-katoya",
      name: "Kātoya",
      coordinates: {"lat": 23.64558, "lng": 88.13258},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 78408 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kasaragod",
      name: "Kāsaragod",
      coordinates: {"lat": 12.49838, "lng": 74.98959},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 54172 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-karol-bagh",
      name: "Karol Bāgh",
      coordinates: {"lat": 28.65136, "lng": 77.19072},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 505241 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kandi",
      name: "Kāndi",
      coordinates: {"lat": 23.95946, "lng": 88.04018},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 54848 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kalyani",
      name: "Kalyani",
      coordinates: {"lat": 22.9757, "lng": 88.4337},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 93184 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jatani",
      name: "Jatani",
      coordinates: {"lat": 20.15975, "lng": 85.70742},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 63697 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hadagalli",
      name: "Hadagalli",
      coordinates: {"lat": 15.02048, "lng": 75.93185},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27967 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hamirpur",
      name: "Hamīrpur",
      coordinates: {"lat": 31.68411, "lng": 76.52506},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 19280 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-guntur",
      name: "Guntur",
      coordinates: {"lat": 16.29974, "lng": 80.45729},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 670073 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kalaburagi",
      name: "Kalaburagi",
      coordinates: {"lat": 17.33583, "lng": 76.83757},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 543147 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ghaziabad",
      name: "Ghāziābād",
      coordinates: {"lat": 28.66535, "lng": 77.43915},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1199191 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-erattupetta",
      name: "Erāttupetta",
      coordinates: {"lat": 9.68747, "lng": 76.77891},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 34814 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-egra",
      name: "Egra",
      coordinates: {"lat": 21.89947, "lng": 87.53794},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 32832 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-durgapur",
      name: "Durgapur",
      coordinates: {"lat": 23.51583, "lng": 87.30801},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 518872 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-doddaballapura",
      name: "Doddaballapura",
      coordinates: {"lat": 13.29452, "lng": 77.53777},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 93105 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-diamond-harbour",
      name: "Diamond Harbour",
      coordinates: {"lat": 22.19268, "lng": 88.18951},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 41802 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dhanbad",
      name: "Dhanbad",
      coordinates: {"lat": 23.79759, "lng": 86.42992},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1196214 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-darjiling",
      name: "Dārjiling",
      coordinates: {"lat": 27.03333, "lng": 88.26667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 123797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-medininagar",
      name: "Medininagar",
      coordinates: {"lat": 24.03971, "lng": 84.0658},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 78396 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-clement-town",
      name: "Clement Town",
      coordinates: {"lat": 30.26361, "lng": 78.00862},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 20806 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chapra",
      name: "Chāpra",
      coordinates: {"lat": 25.78031, "lng": 84.74709},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 202352 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-burla",
      name: "Burla",
      coordinates: {"lat": 21.50976, "lng": 83.87259},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 46698 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-brahmapur",
      name: "Brahmapur",
      coordinates: {"lat": 19.31151, "lng": 84.7929},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 356598 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bishnupur",
      name: "Bishnupur",
      coordinates: {"lat": 23.0738, "lng": 87.31991},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 64041 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bihta",
      name: "Bihtā",
      coordinates: {"lat": 25.55885, "lng": 84.87141},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 47549 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-belagavi",
      name: "Belagavi",
      coordinates: {"lat": 15.85212, "lng": 74.50447},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 490045 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-beldanga",
      name: "Beldānga",
      coordinates: {"lat": 23.93428, "lng": 88.26018},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 27489 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-barddhaman",
      name: "Barddhamān",
      coordinates: {"lat": 23.25572, "lng": 87.85691},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 301725 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-barasat",
      name: "Bārāsat",
      coordinates: {"lat": 22.72154, "lng": 88.48198},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 298127 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-asansol",
      name: "Āsansol",
      coordinates: {"lat": 23.68333, "lng": 86.98333},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 504271 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-amli",
      name: "Āmli",
      coordinates: {"lat": 20.28333, "lng": 73.01667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 33369 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-alwar",
      name: "Alwar",
      coordinates: {"lat": 27.56246, "lng": 76.625},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 322568 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-agra",
      name: "Agra",
      coordinates: {"lat": 27.18333, "lng": 78.01667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1430055 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-agartala",
      name: "Agartala",
      coordinates: {"lat": 23.83605, "lng": 91.27939},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 400004 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chakapara",
      name: "Chakapara",
      coordinates: {"lat": 22.63222, "lng": 88.34861},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 27320 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kotivakkam",
      name: "Kotivakkam",
      coordinates: {"lat": 12.97016, "lng": 80.25769},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 20217 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rudrapur",
      name: "Rudrapur",
      coordinates: {"lat": 28.98, "lng": 79.4},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 154554 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-manesar",
      name: "Mānesar",
      coordinates: {"lat": 28.35311, "lng": 76.94036},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 23448 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sahibabad-daulotpur",
      name: "Sāhibābād Daulotpur",
      coordinates: {"lat": 28.74705, "lng": 77.11465},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 54773 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jharoda-mazra-burari",
      name: "Jharoda Mazra Burāri",
      coordinates: {"lat": 28.73014, "lng": 77.20911},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 22878 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chilla-soroda-bangar",
      name: "Chilla Soroda Bāngar",
      coordinates: {"lat": 28.59572, "lng": 77.30189},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 83217 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bangarda",
      name: "Bāngarda",
      coordinates: {"lat": 22.7592, "lng": 75.79536},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15761 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bangarda-chhota",
      name: "Bāngarda Chhota",
      coordinates: {"lat": 22.74354, "lng": 75.81448},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 64213 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-palda",
      name: "Pālda",
      coordinates: {"lat": 22.68004, "lng": 75.89391},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 18697 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kottaikuppam",
      name: "Kottaikuppam",
      coordinates: {"lat": 11.96126, "lng": 79.83923},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 31726 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chumukedima",
      name: "Chumukedima",
      coordinates: {"lat": 25.82483, "lng": 93.77592},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 25885 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kusum-pur",
      name: "Kusum Pur",
      coordinates: {"lat": 28.55472, "lng": 77.1573},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 17028 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bopal",
      name: "Bopal",
      coordinates: {"lat": 23.03341, "lng": 72.46723},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 37635 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jawaharnagar",
      name: "Jawaharnagar",
      coordinates: {"lat": 17.51001, "lng": 78.56562},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 44562 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tumkur",
      name: "Tumkūr",
      coordinates: {"lat": 13.34136, "lng": 77.1022},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 307359 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tindivanam",
      name: "Tindivanam",
      coordinates: {"lat": 12.234, "lng": 79.65551},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 72796 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tevaram",
      name: "Tevāram",
      coordinates: {"lat": 9.89666, "lng": 77.28092},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16079 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tharangambadi",
      name: "Tharangambadi",
      coordinates: {"lat": 11.02764, "lng": 79.85425},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23191 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-taranagar",
      name: "Tārānagar",
      coordinates: {"lat": 28.6686, "lng": 75.03207},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32640 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tamluk",
      name: "Tamlūk",
      coordinates: {"lat": 22.30083, "lng": 87.92593},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48646 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-talwandi-sabo",
      name: "Talwandi Sābo",
      coordinates: {"lat": 29.98379, "lng": 75.08203},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20589 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-taleigao",
      name: "Taleigao",
      coordinates: {"lat": 15.46915, "lng": 73.83285},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17148 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-surendranagar",
      name: "Surendranagar",
      coordinates: {"lat": 22.72706, "lng": 71.64856},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 179628 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sundarnagar",
      name: "Sundarnagar",
      coordinates: {"lat": 31.53523, "lng": 76.905},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25338 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-suluru",
      name: "Sūlūru",
      coordinates: {"lat": 13.7, "lng": 80.01667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 38065 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sriramnagar",
      name: "Srīrāmnagar",
      coordinates: {"lat": 17.26652, "lng": 78.25544},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19550 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-srinagar-1255635",
      name: "Srīnagar",
      coordinates: {"lat": 30.22243, "lng": 78.78341},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20216 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sonamukhi",
      name: "Sonāmukhi",
      coordinates: {"lat": 23.30521, "lng": 87.41336},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28334 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-silao",
      name: "Silao",
      coordinates: {"lat": 25.08358, "lng": 85.42804},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25674 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sibsagar",
      name: "Sibsāgar",
      coordinates: {"lat": 26.98427, "lng": 94.63784},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 62104 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sholapur",
      name: "Sholapur",
      coordinates: {"lat": 17.67152, "lng": 75.91044},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 997281 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shikohabad",
      name: "Shikohābād",
      coordinates: {"lat": 27.108, "lng": 78.58661},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 99678 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shantipur",
      name: "Shāntipur",
      coordinates: {"lat": 23.24723, "lng": 88.43302},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 149983 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shahdol",
      name: "Shahdol",
      coordinates: {"lat": 23.29356, "lng": 81.3619},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 89289 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sarkhej",
      name: "Sarkhej",
      coordinates: {"lat": 22.98297, "lng": 72.50196},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 30341 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sangareddi",
      name: "Sangāreddi",
      coordinates: {"lat": 17.62477, "lng": 78.08669},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 72344 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sambalpur",
      name: "Sambalpur",
      coordinates: {"lat": 21.46527, "lng": 83.97573},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 189366 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-samastipur",
      name: "Samāstipur",
      coordinates: {"lat": 25.86222, "lng": 85.77953},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 67925 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-saharanpur",
      name: "Sahāranpur",
      coordinates: {"lat": 29.9679, "lng": 77.54522},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 484873 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ropar",
      name: "Ropar",
      coordinates: {"lat": 30.96896, "lng": 76.52695},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56038 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rewari",
      name: "Rewāri",
      coordinates: {"lat": 28.199, "lng": 76.6183},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 143021 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rewa",
      name: "Rewa",
      coordinates: {"lat": 24.53256, "lng": 81.29234},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 235654 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rasapudipalem",
      name: "Rasapūdipalem",
      coordinates: {"lat": 17.73308, "lng": 83.31622},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1728128 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-raniganj-1258470",
      name: "Rānīganj",
      coordinates: {"lat": 23.6164, "lng": 87.13061},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 131261 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rampur",
      name: "Rāmpur",
      coordinates: {"lat": 28.81014, "lng": 79.02699},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 296418 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-rajgir",
      name: "Rājgīr",
      coordinates: {"lat": 25.02828, "lng": 85.42079},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 41587 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-raipur-1258967",
      name: "Rāipur",
      coordinates: {"lat": 30.31097, "lng": 78.08979},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27702 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-raigarh",
      name: "Raigarh",
      coordinates: {"lat": 21.89764, "lng": 83.3966},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 150019 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-raiganj",
      name: "Rāiganj",
      coordinates: {"lat": 25.61281, "lng": 88.12449},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 170252 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-raichur",
      name: "Rāichūr",
      coordinates: {"lat": 16.20546, "lng": 77.35567},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 234073 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-purwa",
      name: "Purwā",
      coordinates: {"lat": 26.45756, "lng": 80.77403},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22220 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-puri",
      name: "Puri",
      coordinates: {"lat": 19.79825, "lng": 85.82494},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 200564 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-phagwara",
      name: "Phagwāra",
      coordinates: {"lat": 31.22452, "lng": 75.77387},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 100146 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-pataudi",
      name: "Pataudi",
      coordinates: {"lat": 28.32547, "lng": 76.77858},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20418 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-padmanabhapuram",
      name: "Padmanābhapuram",
      coordinates: {"lat": 8.24462, "lng": 77.32581},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21342 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ongole",
      name: "Ongole",
      coordinates: {"lat": 15.50357, "lng": 80.04454},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 208344 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nilambur",
      name: "Nilambūr",
      coordinates: {"lat": 11.27271, "lng": 76.22571},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 46366 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nellore",
      name: "Nellore",
      coordinates: {"lat": 14.44992, "lng": 79.98697},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 547621 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nawapara",
      name: "Nawāpāra",
      coordinates: {"lat": 20.97173, "lng": 81.85884},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 29315 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-niwai",
      name: "Niwai",
      coordinates: {"lat": 26.36073, "lng": 75.91836},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 37765 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nautanwa",
      name: "Nautanwa",
      coordinates: {"lat": 27.42752, "lng": 83.41789},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32587 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nalhati",
      name: "Nalhāti",
      coordinates: {"lat": 24.29704, "lng": 87.82899},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25878 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nalgonda",
      name: "Nalgonda",
      coordinates: {"lat": 17.05439, "lng": 79.26707},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 154326 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-nalbari",
      name: "Nalbāri",
      coordinates: {"lat": 26.43937, "lng": 91.44041},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27839 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-muzaffarpur",
      name: "Muzaffarpur",
      coordinates: {"lat": 26.12259, "lng": 85.39055},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 354462 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-morar",
      name: "Morār",
      coordinates: {"lat": 26.2264, "lng": 78.22482},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48464 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-memari",
      name: "Memāri",
      coordinates: {"lat": 23.17647, "lng": 88.09749},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 44448 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mavelikara",
      name: "Māvelikara",
      coordinates: {"lat": 9.25929, "lng": 76.55642},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28300 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mathura",
      name: "Mathura",
      coordinates: {"lat": 27.5035, "lng": 77.67215},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 330511 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mandi",
      name: "Mandi",
      coordinates: {"lat": 31.71194, "lng": 76.93273},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28217 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-madhubani",
      name: "Madhubani",
      coordinates: {"lat": 26.35367, "lng": 86.07169},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 75736 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-madhepura",
      name: "Madhepura",
      coordinates: {"lat": 25.92127, "lng": 86.79271},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 54472 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-madgaon",
      name: "Madgaon",
      coordinates: {"lat": 15.27501, "lng": 73.95786},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 87650 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ludhiana",
      name: "Ludhiana",
      coordinates: {"lat": 30.91204, "lng": 75.85379},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1618879 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-leh",
      name: "Leh",
      coordinates: {"lat": 34.16504, "lng": 77.58402},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 37475 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-lawar-khas",
      name: "Lāwar Khās",
      coordinates: {"lat": 29.11091, "lng": 77.77767},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19556 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kuppam",
      name: "Kuppam",
      coordinates: {"lat": 12.74931, "lng": 78.34189},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21963 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-korba",
      name: "Korba",
      coordinates: {"lat": 22.3458, "lng": 82.69633},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 419146 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kolar-1266305",
      name: "Kolār",
      coordinates: {"lat": 13.13768, "lng": 78.12999},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 138462 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kharar",
      name: "Kharar",
      coordinates: {"lat": 30.74632, "lng": 76.64689},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 74460 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chitrakoot-dham",
      name: "Chitrakoot Dham",
      coordinates: {"lat": 25.21473, "lng": 80.91645},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23316 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-karnal",
      name: "Karnāl",
      coordinates: {"lat": 29.69197, "lng": 76.98448},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 302140 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-karhal",
      name: "Karhal",
      coordinates: {"lat": 27.00089, "lng": 78.93935},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 26693 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-karamsad",
      name: "Karamsad",
      coordinates: {"lat": 22.54243, "lng": 72.90392},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 35285 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kamarhati",
      name: "Kāmārhāti",
      coordinates: {"lat": 22.67111, "lng": 88.37472},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 332965 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kalol",
      name: "Kalol",
      coordinates: {"lat": 23.24656, "lng": 72.49508},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 134426 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jalandhar",
      name: "Jalandhar",
      coordinates: {"lat": 31.32556, "lng": 75.57917},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 868929 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jhunjhunun",
      name: "Jhunjhunūn",
      coordinates: {"lat": 28.12559, "lng": 75.39797},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 118473 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jangaon",
      name: "Jangaon",
      coordinates: {"lat": 17.72602, "lng": 79.15236},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 52394 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jamuria",
      name: "Jāmuria",
      coordinates: {"lat": 23.70468, "lng": 87.07872},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 160242 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jammu",
      name: "Jammu",
      coordinates: {"lat": 32.73528, "lng": 74.86167},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 576198 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-malda",
      name: "Malda",
      coordinates: {"lat": 25.00447, "lng": 88.14573},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 170039 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-hazaribagh",
      name: "Hazāribāgh",
      coordinates: {"lat": 23.99241, "lng": 85.36162},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 153595 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-haveri",
      name: "Hāveri",
      coordinates: {"lat": 14.79354, "lng": 75.40448},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 67102 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-howrah",
      name: "Howrah",
      coordinates: {"lat": 22.57688, "lng": 88.31857},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1027672 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-haldwani",
      name: "Haldwani",
      coordinates: {"lat": 29.22254, "lng": 79.5286},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 139497 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-guskhara",
      name: "Guskhara",
      coordinates: {"lat": 23.49276, "lng": 87.73484},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33780 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-guduvancheri",
      name: "Gūduvāncheri",
      coordinates: {"lat": 12.84519, "lng": 80.06055},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 44098 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-gudalur",
      name: "Gudalur",
      coordinates: {"lat": 9.67826, "lng": 77.24951},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 47419 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-golaghat",
      name: "Golāghāt",
      coordinates: {"lat": 26.51167, "lng": 93.95951},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 41989 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ghatsila",
      name: "Ghātsīla",
      coordinates: {"lat": 22.58531, "lng": 86.47682},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 40624 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sri-ganganagar",
      name: "Sri Ganganagar",
      coordinates: {"lat": 29.92009, "lng": 73.87496},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 237780 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-faridabad",
      name: "Faridabad",
      coordinates: {"lat": 28.41124, "lng": 77.31316},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1414050 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-fyzabad",
      name: "Fyzābād",
      coordinates: {"lat": 26.77549, "lng": 82.15018},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 153047 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-doda",
      name: "Doda",
      coordinates: {"lat": 33.14916, "lng": 75.54746},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21605 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dapoli",
      name: "Dāpoli",
      coordinates: {"lat": 17.75927, "lng": 73.18816},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15713 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chhatarpur",
      name: "Chhatarpur",
      coordinates: {"lat": 24.9177, "lng": 79.58871},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 142128 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-chakulia",
      name: "Chākuliā",
      coordinates: {"lat": 22.48301, "lng": 86.71793},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16306 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bongaigaon",
      name: "Bongaigaon",
      coordinates: {"lat": 26.47703, "lng": 90.55815},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 67322 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vijayapura",
      name: "Vijayapura",
      coordinates: {"lat": 16.82442, "lng": 75.71537},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 327427 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bhuj",
      name: "Bhuj",
      coordinates: {"lat": 23.25397, "lng": 69.66928},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 148834 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bhimunipatnam",
      name: "Bhīmunipatnam",
      coordinates: {"lat": 17.89017, "lng": 83.45203},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 55082 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bhawanipatna",
      name: "Bhawānipatna",
      coordinates: {"lat": 19.90717, "lng": 83.16697},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 69045 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-behror",
      name: "Behror",
      coordinates: {"lat": 27.88832, "lng": 76.28108},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 29531 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-barpeta",
      name: "Barpeta",
      coordinates: {"lat": 26.32293, "lng": 91.00632},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48824 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-baranagar",
      name: "Baranagar",
      coordinates: {"lat": 22.64132, "lng": 88.37727},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 260072 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bagula",
      name: "Bagulā",
      coordinates: {"lat": 23.33664, "lng": 88.64109},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20999 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-arang",
      name: "Arang",
      coordinates: {"lat": 21.19639, "lng": 81.96912},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19091 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-arrah",
      name: "Arrah",
      coordinates: {"lat": 25.55629, "lng": 84.66335},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 261430 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-anand",
      name: "Anand",
      coordinates: {"lat": 22.55251, "lng": 72.9552},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 209410 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-amritsar",
      name: "Amritsar",
      coordinates: {"lat": 31.62234, "lng": 74.87534},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1159227 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-amravati",
      name: "Amravati",
      coordinates: {"lat": 20.93333, "lng": 77.75},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 647057 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-amlagora",
      name: "Āmlāgora",
      coordinates: {"lat": 22.84616, "lng": 87.33559},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19038 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ambala",
      name: "Ambāla",
      coordinates: {"lat": 30.36099, "lng": 76.79782},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 195153 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ambad",
      name: "Ambad",
      coordinates: {"lat": 19.61301, "lng": 75.78906},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31553 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-almora",
      name: "Almora",
      coordinates: {"lat": 29.59713, "lng": 79.65911},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32442 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-aligarh",
      name: "Alīgarh",
      coordinates: {"lat": 27.88145, "lng": 78.07464},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 753207 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ajmer",
      name: "Ajmer",
      coordinates: {"lat": 26.4521, "lng": 74.63867},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 542321 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-adur",
      name: "Adūr",
      coordinates: {"lat": 9.15595, "lng": 76.73192},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 29652 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-contai",
      name: "Contai",
      coordinates: {"lat": 21.77985, "lng": 87.74892},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 88702 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dindarpur",
      name: "Dīndārpur",
      coordinates: {"lat": 28.59813, "lng": 76.99161},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 35856 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kompalli",
      name: "Kompalli",
      coordinates: {"lat": 17.54499, "lng": 78.48836},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15575 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-adampur",
      name: "Adampur",
      coordinates: {"lat": 31.43224, "lng": 75.71484},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20922 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tirumeshi",
      name: "Tirumeshi",
      coordinates: {"lat": 13.05339, "lng": 80.05998},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-koppana-agrahara",
      name: "koppana Agrahara",
      coordinates: {"lat": 12.85507, "lng": 77.66707},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20622 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-malkajgiri",
      name: "Malkajgiri",
      coordinates: {"lat": 17.44781, "lng": 78.52633},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 150000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-barpeta-road",
      name: "Barpeta Road",
      coordinates: {"lat": 26.50284, "lng": 90.96937},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 35571 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-serilingampalle",
      name: "Serilingampalle",
      coordinates: {"lat": 17.49313, "lng": 78.30196},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 150525 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bahula",
      name: "Bahula",
      coordinates: {"lat": 23.65176, "lng": 87.16475},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16264 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-shamshabad",
      name: "Shamshabad",
      coordinates: {"lat": 17.25186, "lng": 78.41835},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32583 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-laitumkhrah",
      name: "Laitumkhrah",
      coordinates: {"lat": 25.57067, "lng": 91.89771},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27219 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-barara",
      name: "Barāra",
      coordinates: {"lat": 30.21465, "lng": 77.04025},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21545 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kapas-herd",
      name: "Kāpas Herd",
      coordinates: {"lat": 28.52614, "lng": 77.08396},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 74073 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ali",
      name: "Ali",
      coordinates: {"lat": 28.5161, "lng": 77.30993},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27169 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-wari",
      name: "Wāri",
      coordinates: {"lat": 21.15313, "lng": 79.0076},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 54048 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-raniganj-10524295",
      name: "Rāniganj",
      coordinates: {"lat": 17.42841, "lng": 78.49361},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 217910 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-makronia",
      name: "Makronia",
      coordinates: {"lat": 23.84765, "lng": 78.79903},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23861 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kalamassery",
      name: "Kalamassery",
      coordinates: {"lat": 10.0614, "lng": 76.32631},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 71038 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ravu",
      name: "Rāvu",
      coordinates: {"lat": 22.63727, "lng": 75.81474},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 36055 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-gobindgarh",
      name: "Gobindgarh",
      coordinates: {"lat": 30.67089, "lng": 76.30192},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 82266 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-kotekara",
      name: "Kōtekāra",
      coordinates: {"lat": 12.7929, "lng": 74.87217},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16505 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-ajanur",
      name: "Ajānūr",
      coordinates: {"lat": 12.33614, "lng": 75.09297},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33079 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vadavalli",
      name: "Vadavalli",
      coordinates: {"lat": 11.02472, "lng": 76.8973},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39873 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-puthur",
      name: "Puthūr",
      coordinates: {"lat": 10.4874, "lng": 76.27929},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17430 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vengola-kizhakkumbagam",
      name: "Vengola Kizhakkumbāgam",
      coordinates: {"lat": 10.06374, "lng": 76.47606},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32697 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vattiyurkavu",
      name: "Vattiyūrkāvu",
      coordinates: {"lat": 8.52469, "lng": 76.98886},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 47187 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-pudusseri",
      name: "Pudusseri",
      coordinates: {"lat": 10.75824, "lng": 76.78594},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16629 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tuvagudi",
      name: "Tuvāgudi",
      coordinates: {"lat": 10.74725, "lng": 78.82133},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 38887 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-melmadai",
      name: "Melmadai",
      coordinates: {"lat": 9.92638, "lng": 78.15028},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 43797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-pudukkottai",
      name: "Pudukkottai",
      coordinates: {"lat": 9.93731, "lng": 78.05325},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15769 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-mawlai-mawiong",
      name: "Mawlai-Mawïong",
      coordinates: {"lat": 25.62322, "lng": 91.88175},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 55012 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-keirao-bitra",
      name: "Keirao Bitra",
      coordinates: {"lat": 24.71105, "lng": 93.97461},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-lanka",
      name: "Lanka",
      coordinates: {"lat": 25.92907, "lng": 92.94856},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 36805 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-morampudi",
      name: "Morampudi",
      coordinates: {"lat": 16.98005, "lng": 81.83715},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15346 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-tilda-newra",
      name: "Tilda Newra",
      coordinates: {"lat": 21.55324, "lng": 81.80187},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 36682 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-bhati",
      name: "Bhati",
      coordinates: {"lat": 28.42953, "lng": 77.22569},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18864 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-aya-nagar",
      name: "Aya Nagar",
      coordinates: {"lat": 28.47202, "lng": 77.1327},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33123 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-undera",
      name: "Undera",
      coordinates: {"lat": 22.34835, "lng": 73.13313},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16902 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-jammu-cantonment",
      name: "Jammu Cantonment",
      coordinates: {"lat": 32.70438, "lng": 74.86114},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28396 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-killannur",
      name: "Killannur",
      coordinates: {"lat": 10.59918, "lng": 76.21801},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20339 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-palai",
      name: "Palai",
      coordinates: {"lat": 9.71306, "lng": 76.68331},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22056 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-sreekaryam",
      name: "Sreekaryam",
      coordinates: {"lat": 8.54884, "lng": 76.91716},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23528 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-thenhippalam",
      name: "Thenhippalam",
      coordinates: {"lat": 11.13232, "lng": 75.88224},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32045 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vazhakkala",
      name: "Vazhakkala",
      coordinates: {"lat": 10.01239, "lng": 76.32633},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 51242 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-dehu-road",
      name: "Dehu Road",
      coordinates: {"lat": 18.68211, "lng": 73.73161},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48961 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-lochapada",
      name: "Lochapada",
      coordinates: {"lat": 19.32873, "lng": 84.80065},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16377 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-vidyavihar",
      name: "Vidyavihar",
      coordinates: {"lat": 28.36812, "lng": 75.58398},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15644 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "india-neelagiri",
      name: "Neelagiri",
      coordinates: {"lat": 10.75943, "lng": 79.09337},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16197 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "India",
  capital: "New Delhi",
  currency: "INR",
  language: "inglés",
  continent: "Asia",
  population: 1463865525,
  cities,
  // Las universidades no van aqui: viven en ./universities/india.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 477,
  aliases: ["india"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
