// Indonesia — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "indonesia";
const countryName = "Indonesia";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/indonesia.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "indonesia-jakarta",
      name: "Jakarta",
      coordinates: {"lat": -6.21462, "lng": 106.84513},
      isCapital: true,
      universityCount: 79,
      statistics: { population: 8540121 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-padang",
      name: "Padang",
      coordinates: {"lat": -0.94924, "lng": 100.35427},
      isCapital: false,
      universityCount: 49,
      statistics: { population: 942938 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-medan",
      name: "Medan",
      coordinates: {"lat": 3.58333, "lng": 98.66667},
      isCapital: false,
      universityCount: 48,
      statistics: { population: 2486283 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bandung",
      name: "Bandung",
      coordinates: {"lat": -6.92222, "lng": 107.60694},
      isCapital: false,
      universityCount: 44,
      statistics: { population: 2528163 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-yogyakarta",
      name: "Yogyakarta",
      coordinates: {"lat": -7.80139, "lng": 110.36472},
      isCapital: false,
      universityCount: 36,
      statistics: { population: 375699 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-surabaya",
      name: "Surabaya",
      coordinates: {"lat": -7.24917, "lng": 112.75083},
      isCapital: false,
      universityCount: 37,
      statistics: { population: 3018022 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-makassar",
      name: "Makassar",
      coordinates: {"lat": -5.14861, "lng": 119.43194},
      isCapital: false,
      universityCount: 35,
      statistics: { population: 1474393 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-semarang",
      name: "Semarang",
      coordinates: {"lat": -6.99306, "lng": 110.42083},
      isCapital: false,
      universityCount: 31,
      statistics: { population: 1694740 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-malang",
      name: "Malang",
      coordinates: {"lat": -7.9797, "lng": 112.6304},
      isCapital: false,
      universityCount: 28,
      statistics: { population: 889359 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-palembang",
      name: "Palembang",
      coordinates: {"lat": -2.91673, "lng": 104.7458},
      isCapital: false,
      universityCount: 25,
      statistics: { population: 1801367 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bandar-lampung",
      name: "Bandar Lampung",
      coordinates: {"lat": -5.42917, "lng": 105.26111},
      isCapital: false,
      universityCount: 23,
      statistics: { population: 1166066 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-denpasar",
      name: "Denpasar",
      coordinates: {"lat": -8.65, "lng": 115.21667},
      isCapital: false,
      universityCount: 20,
      statistics: { population: 670210 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-depok-1645524",
      name: "Depok",
      coordinates: {"lat": -6.4, "lng": 106.81861},
      isCapital: false,
      universityCount: 19,
      statistics: { population: 2163635 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-depok-1645518",
      name: "Depok",
      coordinates: {"lat": -7.7625, "lng": 110.43167},
      isCapital: false,
      universityCount: 17,
      statistics: { population: 104527 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-mataram",
      name: "Mataram",
      coordinates: {"lat": -8.58333, "lng": 116.11667},
      isCapital: false,
      universityCount: 17,
      statistics: { population: 441147 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-banjarmasin",
      name: "Banjarmasin",
      coordinates: {"lat": -3.31987, "lng": 114.59075},
      isCapital: false,
      universityCount: 17,
      statistics: { population: 657663 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-surakarta",
      name: "Surakarta",
      coordinates: {"lat": -7.55611, "lng": 110.83167},
      isCapital: false,
      universityCount: 16,
      statistics: { population: 526870 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-samarinda",
      name: "Samarinda",
      coordinates: {"lat": -0.49167, "lng": 117.14583},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 865306 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-gombong",
      name: "Gombong",
      coordinates: {"lat": -7.60722, "lng": 109.51417},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 50950 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pontianak",
      name: "Pontianak",
      coordinates: {"lat": -0.03194, "lng": 109.325},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 686019 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-jember",
      name: "Jember",
      coordinates: {"lat": -8.17211, "lng": 113.69953},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 298585 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bukittinggi",
      name: "Bukittinggi",
      coordinates: {"lat": -0.30907, "lng": 100.37055},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 121028 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-gedangan",
      name: "Gedangan",
      coordinates: {"lat": -7.39083, "lng": 112.72667},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 79230 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kupang",
      name: "Kupang",
      coordinates: {"lat": -10.17083, "lng": 123.60694},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 474801 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-banda-aceh",
      name: "Banda Aceh",
      coordinates: {"lat": 5.54167, "lng": 95.33333},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 267962 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-manado",
      name: "Manado",
      coordinates: {"lat": 1.48218, "lng": 124.84892},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 458582 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cimahi",
      name: "Cimahi",
      coordinates: {"lat": -6.87222, "lng": 107.5425},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 581994 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pekanbaru",
      name: "Pekanbaru",
      coordinates: {"lat": 0.51667, "lng": 101.44167},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 1167599 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pamulang",
      name: "Pamulang",
      coordinates: {"lat": -6.34278, "lng": 106.73833},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 174557 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-ciputat",
      name: "Ciputat",
      coordinates: {"lat": -6.2375, "lng": 106.69556},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 207858 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sunggal",
      name: "Sunggal",
      coordinates: {"lat": 3.5765, "lng": 98.6151},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 157914 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-purwokerto",
      name: "Purwokerto",
      coordinates: {"lat": -7.42139, "lng": 109.23444},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 230235 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-palangkaraya",
      name: "Palangkaraya",
      coordinates: {"lat": -2.20833, "lng": 113.91667},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 318247 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cileunyi",
      name: "Cileunyi",
      coordinates: {"lat": -6.93889, "lng": 107.75278},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 111476 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-balikpapan",
      name: "Balikpapan",
      coordinates: {"lat": -1.26753, "lng": 116.82887},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 695287 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-batam",
      name: "Batam",
      coordinates: {"lat": 1.14937, "lng": 104.02491},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 1296960 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-deli-tua",
      name: "Deli Tua",
      coordinates: {"lat": 3.5078, "lng": 98.6839},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 27940 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tangerang",
      name: "Tangerang",
      coordinates: {"lat": -6.17806, "lng": 106.63},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 1927815 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-serang",
      name: "Serang",
      coordinates: {"lat": -6.11528, "lng": 106.15417},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 735651 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-jambi-city",
      name: "Jambi City",
      coordinates: {"lat": -1.6, "lng": 103.61667},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 635101 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-gamping-lor",
      name: "Gamping Lor",
      coordinates: {"lat": -7.79556, "lng": 110.32639},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 66110 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-solok",
      name: "Solok",
      coordinates: {"lat": -0.8006, "lng": 100.6571},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 73438 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-madiun",
      name: "Madiun",
      coordinates: {"lat": -7.6298, "lng": 111.5239},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 202544 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kediri",
      name: "Kediri",
      coordinates: {"lat": -7.81667, "lng": 112.01667},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 301424 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-gorontalo",
      name: "Gorontalo",
      coordinates: {"lat": 0.5375, "lng": 123.0625},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 205390 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-ambon",
      name: "Ambon",
      coordinates: {"lat": -3.69583, "lng": 128.18333},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 347288 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sorong",
      name: "Sorong",
      coordinates: {"lat": -0.87956, "lng": 131.26104},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 219958 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-payakumbuh",
      name: "Payakumbuh",
      coordinates: {"lat": -0.2159, "lng": 100.6334},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 139576 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bengkulu",
      name: "Bengkulu",
      coordinates: {"lat": -3.80044, "lng": 102.26554},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 397321 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-abepura",
      name: "Abepura",
      coordinates: {"lat": -2.5964, "lng": 140.6324},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 62248 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-padangsidempuan",
      name: "Padangsidempuan",
      coordinates: {"lat": 1.37952, "lng": 99.27146},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 243843 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-ternate",
      name: "Ternate",
      coordinates: {"lat": 0.79065, "lng": 127.38424},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 210836 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-subang",
      name: "Subang",
      coordinates: {"lat": -6.57, "lng": 107.75667},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 137234 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-singaraja",
      name: "Singaraja",
      coordinates: {"lat": -8.112, "lng": 115.08818},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 133784 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-melati",
      name: "Melati",
      coordinates: {"lat": -7.73333, "lng": 110.36667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 67090 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kendari",
      name: "Kendari",
      coordinates: {"lat": -3.9778, "lng": 122.51507},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 351085 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bogor",
      name: "Bogor",
      coordinates: {"lat": -6.59444, "lng": 106.78917},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1078351 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bekasi",
      name: "Bekasi",
      coordinates: {"lat": -6.2349, "lng": 106.9896},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 2648272 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tarutung",
      name: "Tarutung",
      coordinates: {"lat": 2.01467, "lng": 98.96548},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 39500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-rantauprapat",
      name: "Rantauprapat",
      coordinates: {"lat": 2.1, "lng": 99.83333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 103009 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-ungaran",
      name: "Ungaran",
      coordinates: {"lat": -7.13972, "lng": 110.405},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 171378 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-serpong",
      name: "Serpong",
      coordinates: {"lat": -6.31694, "lng": 106.66417},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 80193 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-ponorogo",
      name: "Ponorogo",
      coordinates: {"lat": -7.8685, "lng": 111.462},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 79026 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pangkalpinang",
      name: "Pangkalpinang",
      coordinates: {"lat": -2.12914, "lng": 106.11377},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 226297 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pamekasan",
      name: "Pamekasan",
      coordinates: {"lat": -7.1568, "lng": 113.4746},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 92447 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-palu",
      name: "Palu",
      coordinates: {"lat": -0.90833, "lng": 119.87083},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 389959 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kebomas",
      name: "Kebomas",
      coordinates: {"lat": -7.16667, "lng": 112.6333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 75982 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-curug",
      name: "Curug",
      coordinates: {"lat": -6.26583, "lng": 106.55639},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 191406 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-baubau",
      name: "Baubau",
      coordinates: {"lat": -5.4633, "lng": 122.6024},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 161280 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-south-tangerang",
      name: "South Tangerang",
      coordinates: {"lat": -6.28862, "lng": 106.71789},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1429529 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pematangsiantar",
      name: "Pematangsiantar",
      coordinates: {"lat": 2.9595, "lng": 99.0687},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 279198 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-lhokseumawe",
      name: "Lhokseumawe",
      coordinates: {"lat": 5.1801, "lng": 97.1507},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 200876 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tasikmalaya",
      name: "Tasikmalaya",
      coordinates: {"lat": -7.3274, "lng": 108.2207},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 770839 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pariaman",
      name: "Pariaman",
      coordinates: {"lat": -0.61898, "lng": 100.11997},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 92183 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-parepare",
      name: "Parepare",
      coordinates: {"lat": -4.0135, "lng": 119.6255},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 160309 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pameungpeuk",
      name: "Pameungpeuk",
      coordinates: {"lat": -7.01833, "lng": 107.60389},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 48294 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-palopo",
      name: "Palopo",
      coordinates: {"lat": -2.9925, "lng": 120.19694},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 184961 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-metro",
      name: "Metro",
      coordinates: {"lat": -5.11306, "lng": 105.30667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 182293 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-lamongan",
      name: "Lamongan",
      coordinates: {"lat": -7.11667, "lng": 112.41667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 59224 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-karawang",
      name: "Karawang",
      coordinates: {"lat": -6.30525, "lng": 107.3197},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 307880 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-jombang",
      name: "Jombang",
      coordinates: {"lat": -7.54595, "lng": 112.23307},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 126465 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-colomadu",
      name: "Colomadu",
      coordinates: {"lat": -7.53333, "lng": 110.75},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 26274 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cirebon",
      name: "Cirebon",
      coordinates: {"lat": -6.7063, "lng": 108.557},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 344851 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-blitar",
      name: "Blitar",
      coordinates: {"lat": -8.0983, "lng": 112.1681},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 161204 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tuban-7529299",
      name: "Tuban",
      coordinates: {"lat": -8.7427, "lng": 115.1724},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 22947 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-langsa",
      name: "Langsa",
      coordinates: {"lat": 4.4683, "lng": 97.9683},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 184016 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bireun",
      name: "Bireun",
      coordinates: {"lat": 5.203, "lng": 96.7009},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 47670 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tual",
      name: "Tual",
      coordinates: {"lat": -5.62878, "lng": 132.75229},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 90470 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tegal",
      name: "Tegal",
      coordinates: {"lat": -6.8694, "lng": 109.1402},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 297173 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sukabumi",
      name: "Sukabumi",
      coordinates: {"lat": -6.91806, "lng": 106.92667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 365735 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sidoarjo",
      name: "Sidoarjo",
      coordinates: {"lat": -7.4478, "lng": 112.7183},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 139189 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sewon",
      name: "Sewon",
      coordinates: {"lat": -7.87639, "lng": 110.35889},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 73585 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-selong",
      name: "Selong",
      coordinates: {"lat": -8.6503, "lng": 116.5318},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 92464 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-purwakarta",
      name: "Purwakarta",
      coordinates: {"lat": -6.55694, "lng": 107.44333},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 179233 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-manokwari",
      name: "Manokwari",
      coordinates: {"lat": -0.86291, "lng": 134.06402},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 132300 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-magelang",
      name: "Magelang",
      coordinates: {"lat": -7.47056, "lng": 110.21778},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 128709 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-luwuk",
      name: "Luwuk",
      coordinates: {"lat": -0.9516, "lng": 122.7875},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 47778 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kedungwaru",
      name: "Kedungwaru",
      coordinates: {"lat": -8.06667, "lng": 111.91667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 80257 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-indralaya",
      name: "Indralaya",
      coordinates: {"lat": -3.25249, "lng": 104.67555},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 42498 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-ende",
      name: "Ende",
      coordinates: {"lat": -8.8432, "lng": 121.6623},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 87269 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cileungsir",
      name: "Cileungsir",
      coordinates: {"lat": -6.39472, "lng": 106.95917},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 289833 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cilacap",
      name: "Cilacap",
      coordinates: {"lat": -7.72639, "lng": 109.00944},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 256996 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-banyuwangi",
      name: "Banyuwangi",
      coordinates: {"lat": -8.2325, "lng": 114.35755},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 117558 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-batubulan",
      name: "Batubulan",
      coordinates: {"lat": -8.62379, "lng": 115.26203},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 28131 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-dalung",
      name: "Dalung",
      coordinates: {"lat": -8.62553, "lng": 115.17042},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 30228 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sigli",
      name: "Sigli",
      coordinates: {"lat": 5.3848, "lng": 95.9609},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17504 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-meulaboh",
      name: "Meulaboh",
      coordinates: {"lat": 4.14402, "lng": 96.12664},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 64646 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kisaran",
      name: "Kisaran",
      coordinates: {"lat": 2.9845, "lng": 99.6158},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 141915 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-wonosari",
      name: "Wonosari",
      coordinates: {"lat": -7.96556, "lng": 110.60361},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 87454 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tulungagung",
      name: "Tulungagung",
      coordinates: {"lat": -8.0657, "lng": 111.9025},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 65262 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tuban-1623180",
      name: "Tuban",
      coordinates: {"lat": -6.8976, "lng": 112.0649},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 76242 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tomohon",
      name: "Tomohon",
      coordinates: {"lat": 1.31678, "lng": 124.80379},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27624 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tobelo",
      name: "Tobelo",
      coordinates: {"lat": 1.72837, "lng": 128.00948},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 34150 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tanjung-pinang",
      name: "Tanjung Pinang",
      coordinates: {"lat": 0.91667, "lng": 104.45833},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 227663 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tahuna",
      name: "Tahuna",
      coordinates: {"lat": 3.61099, "lng": 125.4858},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 35307 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-tabanan",
      name: "Tabanan",
      coordinates: {"lat": -8.5413, "lng": 115.12522},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33667 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sumenep",
      name: "Sumenep",
      coordinates: {"lat": -7.01152, "lng": 113.86042},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84656 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sumedang-utara",
      name: "Sumedang Utara",
      coordinates: {"lat": -6.85, "lng": 107.91667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 100000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sumber",
      name: "Sumber",
      coordinates: {"lat": -6.76028, "lng": 108.48306},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 96725 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sumbawa-besar",
      name: "Sumbawa Besar",
      coordinates: {"lat": -8.49317, "lng": 117.42024},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 62753 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-soko",
      name: "Soko",
      coordinates: {"lat": -7.48315, "lng": 112.42704},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25494 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sofifi",
      name: "Sofifi",
      coordinates: {"lat": 0.73729, "lng": 127.5588},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27591 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-singojuruh",
      name: "Singojuruh",
      coordinates: {"lat": -8.31667, "lng": 114.23333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 29418 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-sampang",
      name: "Sampang",
      coordinates: {"lat": -7.1872, "lng": 113.2394},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 53269 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-salatiga",
      name: "Salatiga",
      coordinates: {"lat": -7.33194, "lng": 110.49278},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 198971 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-probolinggo",
      name: "Probolinggo",
      coordinates: {"lat": -7.7543, "lng": 113.2159},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 243746 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-poso",
      name: "Poso",
      coordinates: {"lat": -1.3959, "lng": 120.7524},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 47477 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-pasuruan",
      name: "Pasuruan",
      coordinates: {"lat": -7.6453, "lng": 112.9075},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 213469 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-padangpanjang",
      name: "Padangpanjang",
      coordinates: {"lat": -0.45602, "lng": 100.40521},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 58627 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-nunukan",
      name: "Nunukan",
      coordinates: {"lat": 4.13841, "lng": 117.6507},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 67006 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-muara-bungo",
      name: "Muara Bungo",
      coordinates: {"lat": -1.49018, "lng": 102.1149},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21243 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-maumere",
      name: "Maumere",
      coordinates: {"lat": -8.6199, "lng": 122.2111},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 87720 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-lubuklinggau",
      name: "Lubuklinggau",
      coordinates: {"lat": -3.2945, "lng": 102.8614},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 234166 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-loa-janan",
      name: "Loa Janan",
      coordinates: {"lat": -0.58295, "lng": 117.09503},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 212816 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-lembang",
      name: "Lembang",
      coordinates: {"lat": -6.81167, "lng": 107.6175},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 183130 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-lawang",
      name: "Lawang",
      coordinates: {"lat": -7.8353, "lng": 112.6947},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 112540 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-labuan",
      name: "Labuan",
      coordinates: {"lat": -6.3784, "lng": 105.83},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33576 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kuningan",
      name: "Kuningan",
      coordinates: {"lat": -6.97583, "lng": 108.48306},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 111742 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kraksaan",
      name: "Kraksaan",
      coordinates: {"lat": -7.75845, "lng": 113.39624},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28248 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-jatibarang",
      name: "Jatibarang",
      coordinates: {"lat": -6.47472, "lng": 108.31528},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 73010 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-godean",
      name: "Godean",
      coordinates: {"lat": -7.76972, "lng": 110.29389},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 63164 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-garut",
      name: "Garut",
      coordinates: {"lat": -7.245, "lng": 107.921},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 131809 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-fakfak",
      name: "Fakfak",
      coordinates: {"lat": -2.92481, "lng": 132.29813},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-driyorejo",
      name: "Driyorejo",
      coordinates: {"lat": -7.3659, "lng": 112.6219},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 26827 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-curup",
      name: "Curup",
      coordinates: {"lat": -3.4703, "lng": 102.5207},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 46245 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cikarang",
      name: "Cikarang",
      coordinates: {"lat": -6.26111, "lng": 107.15278},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 106479 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cianjur",
      name: "Cianjur",
      coordinates: {"lat": -6.82222, "lng": 107.13944},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 174587 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-bojonegoro",
      name: "Bojonegoro",
      coordinates: {"lat": -7.1502, "lng": 111.8817},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 86568 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-banjarbaru",
      name: "Banjarbaru",
      coordinates: {"lat": -3.4406, "lng": 114.8365},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 293332 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-baekrajan",
      name: "Baekrajan",
      coordinates: {"lat": -6.7674, "lng": 110.8541},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 57920 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-airmadidi",
      name: "Airmadidi",
      coordinates: {"lat": 1.42804, "lng": 124.97774},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31446 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-cikupa",
      name: "Cikupa",
      coordinates: {"lat": -6.23639, "lng": 106.50833},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 174041 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kartasura",
      name: "Kartasura",
      coordinates: {"lat": -7.55194, "lng": 110.73778},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 88927 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "indonesia-kota-sambas",
      name: "Kota Sambas",
      coordinates: {"lat": 1.36259, "lng": 109.30093},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 57295 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Indonesia",
  capital: "Jakarta",
  currency: "IDR",
  language: "indonesio",
  continent: "Asia",
  population: 285721236,
  cities,
  // Las universidades no van aqui: viven en ./universities/indonesia.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 194,
  aliases: ["indonesia"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
