// Irán — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "iran";
const countryName = "Irán";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/iran.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "iran-tehran",
      name: "Tehran",
      coordinates: {"lat": 35.69439, "lng": 51.42151},
      isCapital: true,
      universityCount: 28,
      statistics: { population: 7153309 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-shahrak-e-qods",
      name: "Shahrak-e Qods",
      coordinates: {"lat": 35.75936, "lng": 51.37601},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 29774 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-mashhad",
      name: "Mashhad",
      coordinates: {"lat": 36.29807, "lng": 59.60567},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 2307177 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-tajrish",
      name: "Tajrīsh",
      coordinates: {"lat": 35.8044, "lng": 51.4256},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 86000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-shiraz",
      name: "Shiraz",
      coordinates: {"lat": 29.61031, "lng": 52.53113},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 1249942 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-orumiyeh",
      name: "Orūmīyeh",
      coordinates: {"lat": 37.55274, "lng": 45.07605},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 577307 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-kerman",
      name: "Kerman",
      coordinates: {"lat": 30.28321, "lng": 57.07879},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 577514 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-kazerun",
      name: "Kāzerūn",
      coordinates: {"lat": 29.61919, "lng": 51.6535},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 112360 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-isfahan",
      name: "Isfahan",
      coordinates: {"lat": 32.65246, "lng": 51.67462},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1547164 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-qom",
      name: "Qom",
      coordinates: {"lat": 34.6401, "lng": 50.8764},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 900000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-kermanshah",
      name: "Kermanshah",
      coordinates: {"lat": 34.31417, "lng": 47.065},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 621100 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-arak",
      name: "Arāk",
      coordinates: {"lat": 34.09493, "lng": 49.69809},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 503647 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-shahrak-e-pardisan",
      name: "Shahrak-e Pardīsān",
      coordinates: {"lat": 34.55734, "lng": 50.80201},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 100000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-andisheh",
      name: "Andīsheh",
      coordinates: {"lat": 35.74708, "lng": 51.27739},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 116062 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-yazd",
      name: "Yazd",
      coordinates: {"lat": 31.89722, "lng": 54.3675},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 477905 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-tabriz",
      name: "Tabriz",
      coordinates: {"lat": 38.08, "lng": 46.2919},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 1424641 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-sari",
      name: "Sari",
      coordinates: {"lat": 36.56332, "lng": 53.06009},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 255396 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-sanandaj",
      name: "Sanandaj",
      coordinates: {"lat": 35.31495, "lng": 46.99883},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 349176 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-sabzevar",
      name: "Sabzevar",
      coordinates: {"lat": 36.2126, "lng": 57.68191},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 243700 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-rasht",
      name: "Rasht",
      coordinates: {"lat": 37.27611, "lng": 49.58862},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 594590 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-qazvin",
      name: "Qazvin",
      coordinates: {"lat": 36.26877, "lng": 50.0041},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 333635 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-hamadan",
      name: "Hamadān",
      coordinates: {"lat": 34.79922, "lng": 48.51456},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 528256 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-gorgan",
      name: "Gorgān",
      coordinates: {"lat": 36.8427, "lng": 54.44391},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 244937 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-bushehr",
      name: "Bushehr",
      coordinates: {"lat": 28.96887, "lng": 50.83657},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 165377 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-birjand",
      name: "Bīrjand",
      coordinates: {"lat": 32.86628, "lng": 59.22114},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 196982 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-ardabil",
      name: "Ardabīl",
      coordinates: {"lat": 38.2498, "lng": 48.2933},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 410753 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-ahvaz",
      name: "Ahvaz",
      coordinates: {"lat": 31.31901, "lng": 48.6842},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 841145 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-vahidiyeh",
      name: "Vaḩīdīyeh",
      coordinates: {"lat": 35.71445, "lng": 51.47086},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 33249 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-morteza-gerd",
      name: "Morteẕá Gerd",
      coordinates: {"lat": 35.6025, "lng": 51.3496},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15506 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-yasuj",
      name: "Yasuj",
      coordinates: {"lat": 30.66824, "lng": 51.58796},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 96786 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-zanjan",
      name: "Zanjan",
      coordinates: {"lat": 36.67642, "lng": 48.49628},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 357471 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-shahr-e-kord",
      name: "Shahr-e Kord",
      coordinates: {"lat": 32.32612, "lng": 50.8572},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 129153 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-semnan",
      name: "Semnan",
      coordinates: {"lat": 35.57691, "lng": 53.39205},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 124826 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-karaj",
      name: "Karaj",
      coordinates: {"lat": 35.83266, "lng": 50.99155},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1448075 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-jahrom",
      name: "Jahrom",
      coordinates: {"lat": 28.5, "lng": 53.5605},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 141634 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-ilam",
      name: "Īlām",
      coordinates: {"lat": 33.6374, "lng": 46.4227},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 140940 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-gonabad",
      name: "Gonābād",
      coordinates: {"lat": 34.35287, "lng": 58.68365},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 43465 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-garmsar",
      name: "Garmsār",
      coordinates: {"lat": 35.21824, "lng": 52.34085},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 48672 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-shahrud",
      name: "Shahrud",
      coordinates: {"lat": 36.41819, "lng": 54.97628},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 165000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-dezful",
      name: "Dezful",
      coordinates: {"lat": 32.38114, "lng": 48.40581},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 264709 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-borujerd",
      name: "Borūjerd",
      coordinates: {"lat": 33.8973, "lng": 48.7516},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 251958 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-bandar-abbas",
      name: "Bandar Abbas",
      coordinates: {"lat": 27.1865, "lng": 56.2808},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 352173 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-babol",
      name: "Bābol",
      coordinates: {"lat": 36.55102, "lng": 52.6786},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 202796 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-amol",
      name: "Āmol",
      coordinates: {"lat": 36.46961, "lng": 52.35072},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 237528 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-mobarakeh",
      name: "Mobārakeh",
      coordinates: {"lat": 32.34612, "lng": 51.50205},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 69449 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-zabol",
      name: "Zābol",
      coordinates: {"lat": 31.0306, "lng": 61.4949},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 121989 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-torbat-e-heydariyeh",
      name: "Torbat-e Ḩeydarīyeh",
      coordinates: {"lat": 35.27401, "lng": 59.21949},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 140019 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-tafresh",
      name: "Tafresh",
      coordinates: {"lat": 34.69307, "lng": 50.01601},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16493 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-rudehen",
      name: "Rūdehen",
      coordinates: {"lat": 35.73338, "lng": 51.90587},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28533 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-quchan",
      name: "Qūchān",
      coordinates: {"lat": 37.106, "lng": 58.50955},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 111752 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-neyshabur",
      name: "Neyshābūr",
      coordinates: {"lat": 36.21329, "lng": 58.79575},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 220929 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-meybod",
      name: "Meybod",
      coordinates: {"lat": 32.25014, "lng": 54.01658},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 51874 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-maragheh",
      name: "Marāgheh",
      coordinates: {"lat": 37.39206, "lng": 46.23909},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 262604 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-lar",
      name: "Lār",
      coordinates: {"lat": 27.68336, "lng": 54.34172},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 62045 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-kish",
      name: "Kīsh",
      coordinates: {"lat": 26.55778, "lng": 54.01944},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39853 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-kashan",
      name: "Kashan",
      coordinates: {"lat": 33.98237, "lng": 51.42769},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 304487 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-fasa",
      name: "Fasā",
      coordinates: {"lat": 28.9383, "lng": 53.6482},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 98061 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-dehaqan",
      name: "Dehāqān",
      coordinates: {"lat": 31.93986, "lng": 51.64731},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17945 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-bojnurd",
      name: "Bojnūrd",
      coordinates: {"lat": 37.47473, "lng": 57.32903},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 192041 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-bandar-e-mahshahr",
      name: "Bandar-e Māhshahr",
      coordinates: {"lat": 30.55655, "lng": 49.18852},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 162797 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-babolsar",
      name: "Bābolsar",
      coordinates: {"lat": 36.69929, "lng": 52.65011},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 48051 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-shahin-shahr",
      name: "Shāhīn Shahr",
      coordinates: {"lat": 32.85788, "lng": 51.5529},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 173329 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-khomeyni-shahr",
      name: "Khomeynī Shahr",
      coordinates: {"lat": 32.6856, "lng": 51.53609},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 277334 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-zahedan",
      name: "Zahedan",
      coordinates: {"lat": 29.4963, "lng": 60.8629},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 551980 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-shahr-e-sadra",
      name: "Shahr-e Ṣadrā",
      coordinates: {"lat": 29.79972, "lng": 52.50215},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 122226 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "iran-jiroft",
      name: "Jīroft",
      coordinates: {"lat": 28.67806, "lng": 57.74056},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 130429 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Iran",
  capital: "Tehran",
  currency: "IRR",
  language: "persa",
  continent: "Asia",
  population: 92417681,
  cities,
  // Las universidades no van aqui: viven en ./universities/iran.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 193,
  aliases: ["iran"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
