// Italia — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "italia";
const countryName = "Italia";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/italia.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "italia-rome",
      name: "Rome",
      coordinates: {"lat": 41.89193, "lng": 12.51133},
      isCapital: true,
      universityCount: 38,
      statistics: { population: 2318895 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-florence",
      name: "Florence",
      coordinates: {"lat": 43.77925, "lng": 11.24626},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 367150 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-milan",
      name: "Milan",
      coordinates: {"lat": 45.46427, "lng": 9.18951},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 1371498 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-esquilino",
      name: "Esquilino",
      coordinates: {"lat": 41.89931, "lng": 12.5139},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 21263 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-verona",
      name: "Verona",
      coordinates: {"lat": 45.43854, "lng": 10.9938},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 258031 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-venice",
      name: "Venice",
      coordinates: {"lat": 45.43713, "lng": 12.33265},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 51298 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-pavia",
      name: "Pavia",
      coordinates: {"lat": 45.19205, "lng": 9.15917},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 65734 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-bologna",
      name: "Bologna",
      coordinates: {"lat": 44.49381, "lng": 11.33875},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 394843 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-genoa",
      name: "Genoa",
      coordinates: {"lat": 44.40478, "lng": 8.94439},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 580097 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-benevento",
      name: "Benevento",
      coordinates: {"lat": 41.1307, "lng": 14.77816},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 58418 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-san-ferdinando",
      name: "San Ferdinando",
      coordinates: {"lat": 40.83342, "lng": 14.24751},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 18404 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-reggio-calabria",
      name: "Reggio Calabria",
      coordinates: {"lat": 38.11047, "lng": 15.66129},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 182455 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-palermo",
      name: "Palermo",
      coordinates: {"lat": 38.1166, "lng": 13.3636},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 648260 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-cagliari",
      name: "Cagliari",
      coordinates: {"lat": 39.23054, "lng": 9.11917},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 149257 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-vicenza",
      name: "Vicenza",
      coordinates: {"lat": 45.54672, "lng": 11.5475},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 111980 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-udine",
      name: "Udine",
      coordinates: {"lat": 46.0693, "lng": 13.23715},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 100170 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-trento",
      name: "Trento",
      coordinates: {"lat": 46.06787, "lng": 11.12108},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 120709 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-perugia",
      name: "Perugia",
      coordinates: {"lat": 43.1122, "lng": 12.38878},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 120137 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-padua",
      name: "Padua",
      coordinates: {"lat": 45.40797, "lng": 11.88586},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 203725 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-modena",
      name: "Modena",
      coordinates: {"lat": 44.64783, "lng": 10.92539},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 184732 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-livorno",
      name: "Livorno",
      coordinates: {"lat": 43.54427, "lng": 10.32615},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 157017 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-brescia",
      name: "Brescia",
      coordinates: {"lat": 45.53558, "lng": 10.21472},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 200423 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-porta-palazzo",
      name: "Porta Palazzo",
      coordinates: {"lat": 45.07669, "lng": 7.68371},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 19000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-casal-de-pazzi",
      name: "Casal de' Pazzi",
      coordinates: {"lat": 41.92884, "lng": 12.56582},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 27206 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-circoiscrizione-i",
      name: "Circoiscrizione I",
      coordinates: {"lat": 45.06639, "lng": 7.6868},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 78523 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-messina",
      name: "Messina",
      coordinates: {"lat": 38.19394, "lng": 15.55256},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 219948 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-trieste",
      name: "Trieste",
      coordinates: {"lat": 45.64953, "lng": 13.77678},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 204338 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-tradate",
      name: "Tradate",
      coordinates: {"lat": 45.70843, "lng": 8.90763},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17154 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-turin",
      name: "Turin",
      coordinates: {"lat": 45.07049, "lng": 7.68682},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 847287 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-siena",
      name: "Siena",
      coordinates: {"lat": 43.31822, "lng": 11.33064},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 53901 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-prato",
      name: "Prato",
      coordinates: {"lat": 43.8805, "lng": 11.09699},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 195089 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-pisa",
      name: "Pisa",
      coordinates: {"lat": 43.70853, "lng": 10.4036},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 109960 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-mantua",
      name: "Mantua",
      coordinates: {"lat": 45.16031, "lng": 10.79784},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39260 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-lido",
      name: "Lido",
      coordinates: {"lat": 45.4105, "lng": 12.36649},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15719 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-lecce",
      name: "Lecce",
      coordinates: {"lat": 40.35481, "lng": 18.17244},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 80695 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-gorizia",
      name: "Gorizia",
      coordinates: {"lat": 45.94088, "lng": 13.62167},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 34428 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-como",
      name: "Como",
      coordinates: {"lat": 45.80819, "lng": 9.0832},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84808 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-colleferro",
      name: "Colleferro",
      coordinates: {"lat": 41.72722, "lng": 13.00481},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 20736 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-chieti",
      name: "Chieti",
      coordinates: {"lat": 42.34827, "lng": 14.16494},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 44444 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-cattolica",
      name: "Cattolica",
      coordinates: {"lat": 43.96182, "lng": 12.73631},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16189 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-brindisi",
      name: "Brindisi",
      coordinates: {"lat": 40.63215, "lng": 17.93607},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 87141 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-bolzano",
      name: "Bolzano",
      coordinates: {"lat": 46.49067, "lng": 11.33982},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 107436 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-bergamo",
      name: "Bergamo",
      coordinates: {"lat": 45.69601, "lng": 9.66721},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 121200 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-bari",
      name: "Bari",
      coordinates: {"lat": 41.12066, "lng": 16.86982},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 316491 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-spinaceto",
      name: "Spinaceto",
      coordinates: {"lat": 41.77861, "lng": 12.44236},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24219 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-brera",
      name: "Brera",
      coordinates: {"lat": 45.47154, "lng": 9.18763},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18492 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-campo-di-marte",
      name: "Campo di Marte",
      coordinates: {"lat": 43.77693, "lng": 11.27707},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 88588 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-pendino",
      name: "Pendino",
      coordinates: {"lat": 40.84708, "lng": 14.26321},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16848 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "italia-montecalvario",
      name: "Montecalvario",
      coordinates: {"lat": 40.84436, "lng": 14.24555},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23050 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Italy",
  capital: "Rome",
  currency: "EUR",
  language: "italiano",
  continent: "Europa",
  population: 58915656,
  cities,
  // Las universidades no van aqui: viven en ./universities/italia.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 93,
  aliases: ["italia", "italy"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
