// Japón — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "japon";
const countryName = "Japón";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/japon.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "japon-kamigyo-ku",
      name: "Kamigyō-ku",
      coordinates: {"lat": 35.02954, "lng": 135.75666},
      isCapital: false,
      universityCount: 19,
      statistics: { population: 83000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sapporo",
      name: "Sapporo",
      coordinates: {"lat": 43.06667, "lng": 141.35},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 1973832 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kyoto",
      name: "Kyoto",
      coordinates: {"lat": 35.02107, "lng": 135.75385},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 1463723 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nagoya",
      name: "Nagoya",
      coordinates: {"lat": 35.18147, "lng": 136.90641},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 2332176 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nonoichi",
      name: "Nonoichi",
      coordinates: {"lat": 36.53333, "lng": 136.61667},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 57238 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-niigata",
      name: "Niigata",
      coordinates: {"lat": 37.92259, "lng": 139.04125},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 797591 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kobe",
      name: "Kobe",
      coordinates: {"lat": 34.6913, "lng": 135.183},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 1525152 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sendai",
      name: "Sendai",
      coordinates: {"lat": 38.26667, "lng": 140.86667},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 1096704 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-asahikawa",
      name: "Asahikawa",
      coordinates: {"lat": 43.77063, "lng": 142.36489},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 333530 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-akashi",
      name: "Akashi",
      coordinates: {"lat": 34.65524, "lng": 135.00687},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 303601 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-akihabara",
      name: "Akihabara",
      coordinates: {"lat": 35.69848, "lng": 139.77253},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 77200 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-shizuoka",
      name: "Shizuoka",
      coordinates: {"lat": 34.98333, "lng": 138.38333},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 693389 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-okayama",
      name: "Okayama",
      coordinates: {"lat": 34.65, "lng": 133.93333},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 724691 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-miyazaki",
      name: "Miyazaki",
      coordinates: {"lat": 31.91667, "lng": 131.41667},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 401339 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hiroshima",
      name: "Hiroshima",
      coordinates: {"lat": 34.4, "lng": 132.45},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 1200754 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-gion",
      name: "Gion",
      coordinates: {"lat": 34.43333, "lng": 132.46667},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 68713 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-aihara",
      name: "Aihara",
      coordinates: {"lat": 35.6, "lng": 139.31667},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 725493 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-chiyoda",
      name: "Chiyoda",
      coordinates: {"lat": 35.68449, "lng": 139.75056},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 66680 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tokyo",
      name: "Tokyo",
      coordinates: {"lat": 35.6895, "lng": 139.69171},
      isCapital: true,
      universityCount: 8,
      statistics: { population: 9733276 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-takasaki",
      name: "Takasaki",
      coordinates: {"lat": 36.33333, "lng": 139.01667},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 372973 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kurashiki",
      name: "Kurashiki",
      coordinates: {"lat": 34.58333, "lng": 133.76667},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 483576 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ashiya",
      name: "Ashiya",
      coordinates: {"lat": 34.72807, "lng": 135.30264},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 93922 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-akita",
      name: "Akita",
      coordinates: {"lat": 39.71667, "lng": 140.11667},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 307672 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-dazaifu",
      name: "Dazaifu",
      coordinates: {"lat": 33.51278, "lng": 130.52389},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 73164 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nagakute",
      name: "Nagakute",
      coordinates: {"lat": 35.17325, "lng": 137.05667},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 60162 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-suita",
      name: "Suita",
      coordinates: {"lat": 34.76143, "lng": 135.51567},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 385567 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-shingu",
      name: "Shingū",
      coordinates: {"lat": 33.71399, "lng": 130.4313},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 32927 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kitakyushu",
      name: "Kitakyushu",
      coordinates: {"lat": 33.85181, "lng": 130.85034},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 940978 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kagoshima",
      name: "Kagoshima",
      coordinates: {"lat": 31.56667, "lng": 130.55},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 595049 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ebara",
      name: "Ebara",
      coordinates: {"lat": 35.61298, "lng": 139.70315},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 21232 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-takamatsu",
      name: "Takamatsu",
      coordinates: {"lat": 34.33333, "lng": 134.05},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 418994 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nara-shi",
      name: "Nara-shi",
      coordinates: {"lat": 34.68505, "lng": 135.80485},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 367353 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nagano",
      name: "Nagano",
      coordinates: {"lat": 36.65, "lng": 138.18333},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 372760 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-muko",
      name: "Mukō",
      coordinates: {"lat": 34.96545, "lng": 135.70415},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 56859 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-matsubara",
      name: "Matsubara",
      coordinates: {"lat": 34.56667, "lng": 135.55},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 130855 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-maebashi",
      name: "Maebashi",
      coordinates: {"lat": 36.4, "lng": 139.08333},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 332149 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ibaraki",
      name: "Ibaraki",
      coordinates: {"lat": 34.81641, "lng": 135.56828},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 287730 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-aobadai",
      name: "Aobadai",
      coordinates: {"lat": 35.54651, "lng": 139.51723},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 39500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-katanawa",
      name: "Katanawa",
      coordinates: {"lat": 33.52111, "lng": 130.42444},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 50112 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-taito",
      name: "Taito",
      coordinates: {"lat": 35.70749, "lng": 139.7788},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 211444 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-utsunomiya",
      name: "Utsunomiya",
      coordinates: {"lat": 36.56667, "lng": 139.88333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 518757 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyohashi",
      name: "Toyohashi",
      coordinates: {"lat": 34.76667, "lng": 137.38333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 377453 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-oita",
      name: "Ōita",
      coordinates: {"lat": 33.23333, "lng": 131.6},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 477715 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-obita",
      name: "Obita",
      coordinates: {"lat": 32.81667, "lng": 129.88333},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 45293 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nagaoka",
      name: "Nagaoka",
      coordinates: {"lat": 37.45, "lng": 138.85},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 266936 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-moriguchi",
      name: "Moriguchi",
      coordinates: {"lat": 34.73333, "lng": 135.56667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 143096 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-machida",
      name: "Machida",
      coordinates: {"lat": 35.54028, "lng": 139.45083},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 431079 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kawasaki",
      name: "Kawasaki",
      coordinates: {"lat": 35.52056, "lng": 139.71722},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1538262 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kashihara-shi",
      name: "Kashihara-shi",
      coordinates: {"lat": 34.50896, "lng": 135.7929},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 124521 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ichinomiya",
      name: "Ichinomiya",
      coordinates: {"lat": 35.3, "lng": 136.8},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 380073 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hino",
      name: "Hino",
      coordinates: {"lat": 35.67306, "lng": 139.40028},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 190435 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-fukuoka",
      name: "Fukuoka",
      coordinates: {"lat": 33.6, "lng": 130.41667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1612392 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tsukuba",
      name: "Tsukuba",
      coordinates: {"lat": 36.08333, "lng": 140.11667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 241656 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-makuhari",
      name: "Makuhari",
      coordinates: {"lat": 35.65, "lng": 140.05},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 28729 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hakodate",
      name: "Hakodate",
      coordinates: {"lat": 41.77583, "lng": 140.73667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 275730 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ebetsu",
      name: "Ebetsu",
      coordinates: {"lat": 43.10806, "lng": 141.55056},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 133953 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yamagata-6822213",
      name: "Yamagata",
      coordinates: {"lat": 35.47619, "lng": 136.7721},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 27356 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-otsuka",
      name: "Ōtsuka",
      coordinates: {"lat": 35.72403, "lng": 139.72868},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 19081 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-shibuya",
      name: "Shibuya",
      coordinates: {"lat": 35.6589, "lng": 139.70665},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 230609 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yokohama",
      name: "Yokohama",
      coordinates: {"lat": 35.43333, "lng": 139.65},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 3777491 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tsu",
      name: "Tsu",
      coordinates: {"lat": 34.73333, "lng": 136.51667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 274537 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyosu",
      name: "Toyosu",
      coordinates: {"lat": 35.65087, "lng": 139.79163},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 40424 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sasebo",
      name: "Sasebo",
      coordinates: {"lat": 33.16834, "lng": 129.72502},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 243223 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sakai-1853195",
      name: "Sakai",
      coordinates: {"lat": 34.58216, "lng": 135.46653},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 826161 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-okazaki",
      name: "Okazaki",
      coordinates: {"lat": 34.95, "lng": 137.16667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 384654 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nagasaki-1856177",
      name: "Nagasaki",
      coordinates: {"lat": 32.75, "lng": 129.88333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 409118 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-matsumoto",
      name: "Matsumoto",
      coordinates: {"lat": 36.23333, "lng": 137.96667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 241145 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kurume",
      name: "Kurume",
      coordinates: {"lat": 33.31667, "lng": 130.51667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 303579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kumamoto",
      name: "Kumamoto",
      coordinates: {"lat": 32.80589, "lng": 130.69181},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 738907 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kochi",
      name: "Kochi",
      coordinates: {"lat": 33.55, "lng": 133.53333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 332059 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kameda-honcho",
      name: "Kameda-honchō",
      coordinates: {"lat": 37.87214, "lng": 139.1099},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 32765 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-higashiosaka",
      name: "Higashiosaka",
      coordinates: {"lat": 34.66667, "lng": 135.58333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 493940 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hatsukaichi",
      name: "Hatsukaichi",
      coordinates: {"lat": 34.35, "lng": 132.33333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 114173 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hamakita",
      name: "Hamakita",
      coordinates: {"lat": 34.8, "lng": 137.78333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 86502 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hachioji",
      name: "Hachiōji",
      coordinates: {"lat": 35.65583, "lng": 139.32389},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 579355 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-fukui-shi",
      name: "Fukui-shi",
      coordinates: {"lat": 36.06443, "lng": 136.22257},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 262328 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-akasaka",
      name: "Akasaka",
      coordinates: {"lat": 35.67135, "lng": 139.73442},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 17603 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-matsuyama",
      name: "Matsuyama",
      coordinates: {"lat": 33.83916, "lng": 132.76574},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 511192 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yotsukaido",
      name: "Yotsukaidō",
      coordinates: {"lat": 35.65, "lng": 140.16667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 95266 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yamagata-2110556",
      name: "Yamagata",
      coordinates: {"lat": 38.23333, "lng": 140.36667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 248772 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-morioka",
      name: "Morioka",
      coordinates: {"lat": 39.7, "lng": 141.15},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 290700 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-fukushima",
      name: "Fukushima",
      coordinates: {"lat": 37.75, "lng": 140.46667},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 294237 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-otaru",
      name: "Otaru",
      coordinates: {"lat": 43.18944, "lng": 141.00222},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 115333 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kitami",
      name: "Kitami",
      coordinates: {"lat": 43.80306, "lng": 143.89083},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 119135 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hirosaki",
      name: "Hirosaki",
      coordinates: {"lat": 40.59306, "lng": 140.4725},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 168739 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hachinohe",
      name: "Hachinohe",
      coordinates: {"lat": 40.5, "lng": 141.5},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 239046 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-aomori",
      name: "Aomori",
      coordinates: {"lat": 40.81667, "lng": 140.73333},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 298394 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-owariasahi",
      name: "Owariasahi",
      coordinates: {"lat": 35.208, "lng": 137.03},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 83144 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-imizu",
      name: "Imizu",
      coordinates: {"lat": 36.76835, "lng": 137.12572},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 90742 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nisshin",
      name: "Nisshin",
      coordinates: {"lat": 35.13676, "lng": 137.05238},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 91795 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyoake",
      name: "Toyoake",
      coordinates: {"lat": 35.038, "lng": 136.99931},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 69295 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-joetsu",
      name: "Jōetsu",
      coordinates: {"lat": 37.14828, "lng": 138.23642},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 189430 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hirai",
      name: "Hirai",
      coordinates: {"lat": 35.70768, "lng": 139.8425},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 40373 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sendagi",
      name: "Sendagi",
      coordinates: {"lat": 35.72812, "lng": 139.76017},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 20906 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-bunkyo",
      name: "Bunkyo",
      coordinates: {"lat": 35.5331, "lng": 139.4217},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 240069 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-chuo",
      name: "Chūō",
      coordinates: {"lat": 35.67004, "lng": 139.77544},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 169179 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-minato-city",
      name: "Minato City",
      coordinates: {"lat": 35.6581, "lng": 139.7515},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 260486 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yono",
      name: "Yono",
      coordinates: {"lat": 35.88333, "lng": 139.63333},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 102364 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ube",
      name: "Ube",
      coordinates: {"lat": 33.94306, "lng": 131.25111},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 173733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tsuruga",
      name: "Tsuruga",
      coordinates: {"lat": 35.653, "lng": 136.06331},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 68482 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyama",
      name: "Toyama",
      coordinates: {"lat": 36.7, "lng": 137.21667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 415844 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tokuyama",
      name: "Tokuyama",
      coordinates: {"lat": 34.05, "lng": 131.81667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 101133 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tokushima",
      name: "Tokushima",
      coordinates: {"lat": 34.06667, "lng": 134.56667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 267345 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tenri",
      name: "Tenri",
      coordinates: {"lat": 34.58333, "lng": 135.83333},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 71052 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-takatsuki",
      name: "Takatsuki",
      coordinates: {"lat": 34.84833, "lng": 135.61678},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 354468 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-takarazuka",
      name: "Takarazuka",
      coordinates: {"lat": 34.79936, "lng": 135.35697},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 226432 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-takanawa",
      name: "Takanawa",
      coordinates: {"lat": 35.63212, "lng": 139.73423},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 22731 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tagawa",
      name: "Tagawa",
      coordinates: {"lat": 33.63333, "lng": 130.8},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 51608 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-shimonoseki",
      name: "Shimonoseki",
      coordinates: {"lat": 33.95548, "lng": 130.93713},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 265684 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-osaka",
      name: "Osaka",
      coordinates: {"lat": 34.69379, "lng": 135.50107},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 2753862 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-okubo-naka",
      name: "Ōkubo-naka",
      coordinates: {"lat": 34.4045, "lng": 135.34087},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 43763 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-matsue",
      name: "Matsue",
      coordinates: {"lat": 35.48333, "lng": 133.05},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 203616 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kofu",
      name: "Kofu",
      coordinates: {"lat": 35.66667, "lng": 138.56667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 189591 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kasugai",
      name: "Kasugai",
      coordinates: {"lat": 35.24762, "lng": 136.97229},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 308681 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kashiwa",
      name: "Kashiwa",
      coordinates: {"lat": 35.86224, "lng": 139.97732},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 433436 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kamirenjaku",
      name: "Kamirenjaku",
      coordinates: {"lat": 35.69423, "lng": 139.55495},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 195391 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hirakata",
      name: "Hirakata",
      coordinates: {"lat": 34.81352, "lng": 135.64914},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 406331 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hamamatsu",
      name: "Hamamatsu",
      coordinates: {"lat": 34.7, "lng": 137.73333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 791707 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-higashigotanda",
      name: "Higashigotanda",
      coordinates: {"lat": 35.62506, "lng": 139.72841},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15550 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-godo",
      name: "Gōdo",
      coordinates: {"lat": 35.41667, "lng": 136.6},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 19361 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-fukuchiyama",
      name: "Fukuchiyama",
      coordinates: {"lat": 35.3, "lng": 135.11667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 77306 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-beppu",
      name: "Beppu",
      coordinates: {"lat": 33.27945, "lng": 131.49751},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 122643 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-shinjo",
      name: "Shinjō",
      coordinates: {"lat": 38.75861, "lng": 140.30083},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 41140 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-mito",
      name: "Mito",
      coordinates: {"lat": 36.35, "lng": 140.45},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 270685 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-katsuura",
      name: "Katsuura",
      coordinates: {"lat": 35.14621, "lng": 140.31507},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 16927 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-chiba",
      name: "Chiba",
      coordinates: {"lat": 35.6, "lng": 140.11667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 979768 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-abiko",
      name: "Abiko",
      coordinates: {"lat": 35.86667, "lng": 140.01667},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 131771 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ishikari",
      name: "Ishikari",
      coordinates: {"lat": 43.23972, "lng": 141.35389},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 58755 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-musashimurayama",
      name: "Musashimurayama",
      coordinates: {"lat": 35.74242, "lng": 139.42635},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 70829 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sayama",
      name: "Sayama",
      coordinates: {"lat": 34.51685, "lng": 135.56298},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 58435 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ikebukuro",
      name: "Ikebukuro",
      coordinates: {"lat": 35.73681, "lng": 139.70711},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 19930 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sekimachi-minami",
      name: "Sekimachi-minami",
      coordinates: {"lat": 35.72138, "lng": 139.58077},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 16504 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-koga",
      name: "Koga",
      coordinates: {"lat": 33.86429, "lng": 130.68709},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 18723 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-azamino",
      name: "Azamino",
      coordinates: {"lat": 35.5699, "lng": 139.54482},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 17682 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-minami-oi",
      name: "Minami-ōi",
      coordinates: {"lat": 35.59283, "lng": 139.73367},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 27201 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-shimo-ochiai",
      name: "Shimo’ochiai",
      coordinates: {"lat": 35.72018, "lng": 139.702},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15583 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ebisu",
      name: "Ebisu",
      coordinates: {"lat": 35.64595, "lng": 139.7155},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15112 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-inokashira",
      name: "Inokashira",
      coordinates: {"lat": 35.69313, "lng": 139.5834},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15853 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-koto",
      name: "Kotō",
      coordinates: {"lat": 32.77856, "lng": 130.74537},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 543730 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kunitachi",
      name: "Kunitachi",
      coordinates: {"lat": 35.6833, "lng": 139.43848},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 77130 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nantan",
      name: "Nantan",
      coordinates: {"lat": 35.1098, "lng": 135.49164},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 31629 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-koganei",
      name: "Koganei",
      coordinates: {"lat": 35.70014, "lng": 139.51109},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 126074 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-komae",
      name: "Komae",
      coordinates: {"lat": 35.63424, "lng": 139.57546},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 84772 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-oharu",
      name: "Ōharu",
      coordinates: {"lat": 35.17457, "lng": 136.82014},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32399 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-atsugi",
      name: "Atsugi",
      coordinates: {"lat": 35.44272, "lng": 139.36931},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 223960 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-zushi",
      name: "Zushi",
      coordinates: {"lat": 35.29483, "lng": 139.57812},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 60055 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yao",
      name: "Yao",
      coordinates: {"lat": 34.61667, "lng": 135.6},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 273213 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yamaguchi",
      name: "Yamaguchi",
      coordinates: {"lat": 34.18333, "lng": 131.46667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 193966 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-uji",
      name: "Uji",
      coordinates: {"lat": 34.89044, "lng": 135.80325},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 192925 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tsuyama",
      name: "Tsuyama",
      coordinates: {"lat": 35.05215, "lng": 133.99885},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 102294 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tsurusaki",
      name: "Tsurusaki",
      coordinates: {"lat": 33.24528, "lng": 131.69165},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 76968 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tsurugi-asahimachi",
      name: "Tsurugi-asahimachi",
      coordinates: {"lat": 36.45, "lng": 136.63333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22042 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyota",
      name: "Toyota",
      coordinates: {"lat": 35.08333, "lng": 137.15},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 426162 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyooka",
      name: "Toyooka",
      coordinates: {"lat": 35.54008, "lng": 134.82038},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 78348 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyoda",
      name: "Toyoda",
      coordinates: {"lat": 35.01667, "lng": 136.66667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15123 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tottori-shi",
      name: "Tottori-shi",
      coordinates: {"lat": 35.5, "lng": 134.23333},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 188465 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tondabayashicho",
      name: "Tondabayashichō",
      coordinates: {"lat": 34.50065, "lng": 135.60211},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 132873 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tokorozawa",
      name: "Tokorozawa",
      coordinates: {"lat": 35.79916, "lng": 139.46903},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 344194 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-takahashi",
      name: "Takahashi",
      coordinates: {"lat": 34.78333, "lng": 133.61667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31556 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-suzuka",
      name: "Suzuka",
      coordinates: {"lat": 34.88333, "lng": 136.58333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 195670 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sumida",
      name: "Sumida",
      coordinates: {"lat": 35.73289, "lng": 139.82085},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 287766 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-shinshiro",
      name: "Shinshiro",
      coordinates: {"lat": 34.9, "lng": 137.5},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 44355 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sekimachi",
      name: "Sekimachi",
      coordinates: {"lat": 35.48333, "lng": 136.91667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 85283 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-saku",
      name: "Saku",
      coordinates: {"lat": 36.21667, "lng": 138.48333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 99131 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-saga",
      name: "Saga",
      coordinates: {"lat": 33.23333, "lng": 130.3},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 233301 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-otsu",
      name: "Ōtsu",
      coordinates: {"lat": 35.0, "lng": 135.86667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 345070 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ogori-shimogo",
      name: "Ogōri-shimogō",
      coordinates: {"lat": 34.1, "lng": 131.4},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23516 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nishitawara",
      name: "Nishitawara",
      coordinates: {"lat": 34.95556, "lng": 134.76835},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19377 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-narutocho-mitsuishi",
      name: "Narutochō-mitsuishi",
      coordinates: {"lat": 34.19933, "lng": 134.60932},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 64082 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nago",
      name: "Nago",
      coordinates: {"lat": 26.61502, "lng": 127.98543},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 63554 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-morohongo",
      name: "Morohongō",
      coordinates: {"lat": 35.93556, "lng": 139.30444},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39693 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-minamirinkan",
      name: "Minamirinkan",
      coordinates: {"lat": 35.49527, "lng": 139.44279},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 224015 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-matsuto",
      name: "Matsutō",
      coordinates: {"lat": 36.51667, "lng": 136.56667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 110408 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-maruoka",
      name: "Maruoka",
      coordinates: {"lat": 36.1534, "lng": 136.27029},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33563 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kure",
      name: "Kure",
      coordinates: {"lat": 34.23222, "lng": 132.56658},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 214592 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-komatsu",
      name: "Komatsu",
      coordinates: {"lat": 36.40263, "lng": 136.45088},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 108509 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kitahama",
      name: "Kitahama",
      coordinates: {"lat": 35.16667, "lng": 135.91667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23836 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kisarazu",
      name: "Kisarazu",
      coordinates: {"lat": 35.38329, "lng": 139.93254},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 136166 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kawanishi",
      name: "Kawanishi",
      coordinates: {"lat": 34.81667, "lng": 135.41667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 155165 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kawagoe",
      name: "Kawagoe",
      coordinates: {"lat": 35.90861, "lng": 139.48528},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 354571 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kashiwazaki",
      name: "Kashiwazaki",
      coordinates: {"lat": 37.36667, "lng": 138.55},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 86183 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kashihara",
      name: "Kashihara",
      coordinates: {"lat": 34.58333, "lng": 135.61667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 79058 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kasamatsucho",
      name: "Kasamatsuchō",
      coordinates: {"lat": 35.36667, "lng": 136.76667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22273 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kamakura",
      name: "Kamakura",
      coordinates: {"lat": 35.31085, "lng": 139.54698},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 172929 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kakamigahara",
      name: "Kakamigahara",
      coordinates: {"lat": 35.41667, "lng": 136.86667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 144521 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kaitaichi",
      name: "Kaitaichi",
      coordinates: {"lat": 34.36667, "lng": 132.53333},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 29636 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-izumo",
      name: "Izumo",
      coordinates: {"lat": 35.36667, "lng": 132.76667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 172775 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-iwata",
      name: "Iwata",
      coordinates: {"lat": 34.7, "lng": 137.85},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 166672 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-itami",
      name: "Itami",
      coordinates: {"lat": 34.78427, "lng": 135.40126},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 198138 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-itabashi",
      name: "Itabashi",
      coordinates: {"lat": 35.74893, "lng": 139.71497},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 584483 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-isogo",
      name: "Isogo",
      coordinates: {"lat": 35.4082, "lng": 139.61906},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16706 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ise",
      name: "Ise",
      coordinates: {"lat": 34.48333, "lng": 136.7},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 123533 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-isawa",
      name: "Isawa",
      coordinates: {"lat": 35.65, "lng": 138.63333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 29616 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-inazawa",
      name: "Inazawa",
      coordinates: {"lat": 35.25, "lng": 136.78333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 134751 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hikone",
      name: "Hikone",
      coordinates: {"lat": 35.25, "lng": 136.25},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 113647 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-okubo",
      name: "Ōkubo",
      coordinates: {"lat": 35.70307, "lng": 139.70436},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16302 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hagi",
      name: "Hagi",
      coordinates: {"lat": 34.4, "lng": 131.41667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 44626 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ginowan",
      name: "Ginowan",
      coordinates: {"lat": 26.26265, "lng": 127.76147},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 100125 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-gamagori",
      name: "Gamagōri",
      coordinates: {"lat": 34.83333, "lng": 137.23333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 80063 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-fukuyama",
      name: "Fukuyama",
      coordinates: {"lat": 34.48333, "lng": 133.36667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 468812 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-fukayacho",
      name: "Fukayachō",
      coordinates: {"lat": 36.2, "lng": 139.28333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 141268 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-toyo",
      name: "Tōyō",
      coordinates: {"lat": 35.6698, "lng": 139.81456},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25870 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-den-enchofu",
      name: "Den’enchōfu",
      coordinates: {"lat": 35.59548, "lng": 139.66535},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18952 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-daito",
      name: "Daitō",
      coordinates: {"lat": 34.71378, "lng": 135.62033},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 119367 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-amagasaki",
      name: "Amagasaki",
      coordinates: {"lat": 34.71667, "lng": 135.41667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 459593 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-wakayama",
      name: "Wakayama",
      coordinates: {"lat": 34.23333, "lng": 135.16667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 356729 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hojo",
      name: "Hōjō",
      coordinates: {"lat": 33.97661, "lng": 132.77767},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27992 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tendo",
      name: "Tendō",
      coordinates: {"lat": 38.35361, "lng": 140.36972},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 65393 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ryugasaki",
      name: "Ryūgasaki",
      coordinates: {"lat": 35.9, "lng": 140.18333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 85761 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-koriyama",
      name: "Kōriyama",
      coordinates: {"lat": 37.4, "lng": 140.38333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 327692 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kamogawa",
      name: "Kamogawa",
      coordinates: {"lat": 35.0969, "lng": 140.1003},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32116 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-iwaki",
      name: "Iwaki",
      coordinates: {"lat": 37.05, "lng": 140.88333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 357309 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kushiro",
      name: "Kushiro",
      coordinates: {"lat": 42.975, "lng": 144.37472},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 167875 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kitahiroshima",
      name: "Kitahiroshima",
      coordinates: {"lat": 42.97583, "lng": 141.56722},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 58918 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-neyagawa",
      name: "Neyagawa",
      coordinates: {"lat": 34.76615, "lng": 135.62759},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 238549 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tama",
      name: "Tama",
      coordinates: {"lat": 35.6436, "lng": 139.46844},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 148285 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-aizu-wakamatsu",
      name: "Aizu-Wakamatsu",
      coordinates: {"lat": 37.49142, "lng": 139.94546},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 118159 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tsurugashima",
      name: "Tsurugashima",
      coordinates: {"lat": 35.95996, "lng": 139.40283},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 70117 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-hashima",
      name: "Hashima",
      coordinates: {"lat": 35.329, "lng": 136.68051},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 67909 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-habikino",
      name: "Habikino",
      coordinates: {"lat": 34.55276, "lng": 135.59097},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 109479 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kirishima",
      name: "Kirishima",
      coordinates: {"lat": 31.74087, "lng": 130.76288},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 123205 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-arashiyama",
      name: "Arashiyama",
      coordinates: {"lat": 35.01481, "lng": 135.67755},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sakai-8572855",
      name: "Sakai",
      coordinates: {"lat": 35.70571, "lng": 139.54381},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15594 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sakuradai",
      name: "Sakuradai",
      coordinates: {"lat": 35.74405, "lng": 139.66071},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25537 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-nagasaki-8573184",
      name: "Nagasaki",
      coordinates: {"lat": 35.72983, "lng": 139.68857},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 18260 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yotsuya",
      name: "Yotsuya",
      coordinates: {"lat": 35.68972, "lng": 139.71641},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 74800 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-yoyogi",
      name: "Yoyogi",
      coordinates: {"lat": 35.67855, "lng": 139.69146},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24125 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-takizawa",
      name: "Takizawa",
      coordinates: {"lat": 39.8028, "lng": 141.13466},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 55579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-munakata",
      name: "Munakata",
      coordinates: {"lat": 33.7957, "lng": 130.55895},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 97095 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-sakai-11611626",
      name: "Sakai",
      coordinates: {"lat": 36.1473, "lng": 136.19408},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 92210 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kodaira",
      name: "Kodaira",
      coordinates: {"lat": 35.72603, "lng": 139.48508},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 198739 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-etajima",
      name: "Etajima",
      coordinates: {"lat": 34.23863, "lng": 132.47967},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24596 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-miyoshi",
      name: "Miyoshi",
      coordinates: {"lat": 35.08971, "lng": 137.08998},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 61952 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-inagi",
      name: "Inagi",
      coordinates: {"lat": 35.63295, "lng": 139.49967},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 93151 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-tokai",
      name: "Tokai",
      coordinates: {"lat": 36.47396, "lng": 140.56355},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 37891 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-setagaya",
      name: "Setagaya",
      coordinates: {"lat": 35.64188, "lng": 139.64715},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 940071 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-ichikawa",
      name: "Ichikawa",
      coordinates: {"lat": 35.73413, "lng": 139.9065},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 496676 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-oguchi",
      name: "Ōguchi",
      coordinates: {"lat": 35.34146, "lng": 136.91108},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 24305 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "japon-kumano",
      name: "Kumano",
      coordinates: {"lat": 34.33284, "lng": 132.56967},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22834 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Japan",
  capital: "Tokyo",
  currency: "JPY",
  language: "japonés",
  continent: "Asia",
  population: 123366734,
  cities,
  // Las universidades no van aqui: viven en ./universities/japon.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 572,
  aliases: ["japan", "japon"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
