// Nigeria — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "nigeria";
const countryName = "Nigeria";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/nigeria.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "nigeria-ilorin",
      name: "Ilorin",
      coordinates: {"lat": 8.49664, "lng": 4.54214},
      isCapital: false,
      universityCount: 50,
      statistics: { population: 1080000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-abuja",
      name: "Abuja",
      coordinates: {"lat": 9.05785, "lng": 7.49508},
      isCapital: true,
      universityCount: 27,
      statistics: { population: 2690000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kano",
      name: "Kano",
      coordinates: {"lat": 12.00012, "lng": 8.51672},
      isCapital: false,
      universityCount: 20,
      statistics: { population: 4910000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-enugu",
      name: "Enugu",
      coordinates: {"lat": 6.44132, "lng": 7.49883},
      isCapital: false,
      universityCount: 17,
      statistics: { population: 950000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-owerri",
      name: "Owerri",
      coordinates: {"lat": 5.48363, "lng": 7.03325},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 545000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kaduna",
      name: "Kaduna",
      coordinates: {"lat": 10.52641, "lng": 7.43879},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 1850000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-benin-city",
      name: "Benin City",
      coordinates: {"lat": 6.33815, "lng": 5.62575},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 1782000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-aba",
      name: "Aba",
      coordinates: {"lat": 5.10658, "lng": 7.36667},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 1160000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-yenagoa",
      name: "Yenagoa",
      coordinates: {"lat": 4.92675, "lng": 6.26764},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 365000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kuje",
      name: "Kuje",
      coordinates: {"lat": 8.87952, "lng": 7.22756},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 97367 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ikot-ekpene",
      name: "Ikot Ekpene",
      coordinates: {"lat": 5.18194, "lng": 7.71481},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 254806 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ibadan",
      name: "Ibadan",
      coordinates: {"lat": 7.37756, "lng": 3.90591},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 3649000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ado-ekiti",
      name: "Ado-Ekiti",
      coordinates: {"lat": 7.62329, "lng": 5.22087},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 435000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-sokoto",
      name: "Sokoto",
      coordinates: {"lat": 13.06269, "lng": 5.24322},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 1040000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-katsina",
      name: "Katsina",
      coordinates: {"lat": 12.99082, "lng": 7.60177},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 670000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-umuahia",
      name: "Umuahia",
      coordinates: {"lat": 5.52491, "lng": 7.49461},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 370000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-offa",
      name: "Offa",
      coordinates: {"lat": 8.14911, "lng": 4.72074},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 113830 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-maiduguri",
      name: "Maiduguri",
      coordinates: {"lat": 11.84692, "lng": 13.15712},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 1110000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ondo",
      name: "Ondo",
      coordinates: {"lat": 7.09316, "lng": 4.83528},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 375000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-oke-ila",
      name: "Oke Ila",
      coordinates: {"lat": 7.95, "lng": 4.98333},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 35000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-iwo",
      name: "Iwo",
      coordinates: {"lat": 7.63527, "lng": 4.18156},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 250443 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ebute-ikorodu",
      name: "Ebute Ikorodu",
      coordinates: {"lat": 6.60086, "lng": 3.48818},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 535619 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-calabar",
      name: "Calabar",
      coordinates: {"lat": 4.95893, "lng": 8.32695},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 540000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-bauchi",
      name: "Bauchi",
      coordinates: {"lat": 10.31032, "lng": 9.84388},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 693700 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-awka",
      name: "Awka",
      coordinates: {"lat": 6.21269, "lng": 7.07199},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 167738 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-port-harcourt",
      name: "Port Harcourt",
      coordinates: {"lat": 4.77742, "lng": 7.0134},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 2120000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-oyo",
      name: "Oyo",
      coordinates: {"lat": 7.85367, "lng": 3.93235},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 736072 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-minna",
      name: "Minna",
      coordinates: {"lat": 9.61524, "lng": 6.54776},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 425000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-epe",
      name: "Epe",
      coordinates: {"lat": 6.58412, "lng": 3.98336},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 84711 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ede",
      name: "Ede",
      coordinates: {"lat": 7.73635, "lng": 4.43536},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 159866 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-azare",
      name: "Azare",
      coordinates: {"lat": 11.67478, "lng": 10.19069},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 105687 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-abeokuta",
      name: "Abeokuta",
      coordinates: {"lat": 7.15571, "lng": 3.34509},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 735000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ughelli",
      name: "Ughelli",
      coordinates: {"lat": 5.48956, "lng": 6.00407},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 79986 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-shagamu",
      name: "Shagamu",
      coordinates: {"lat": 6.8485, "lng": 3.64633},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 214558 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-sapele",
      name: "Sapele",
      coordinates: {"lat": 5.89405, "lng": 5.67666},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 305000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-osogbo",
      name: "Osogbo",
      coordinates: {"lat": 7.77104, "lng": 4.55698},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 645000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ogwashi-uku",
      name: "Ogwashi-Uku",
      coordinates: {"lat": 6.17811, "lng": 6.52461},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 26137 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-keffi",
      name: "Keffi",
      coordinates: {"lat": 8.84651, "lng": 7.87354},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 85911 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-igbara-odo",
      name: "Igbara-Odo",
      coordinates: {"lat": 7.50251, "lng": 5.06258},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 74121 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-gbongan",
      name: "Gbongan",
      coordinates: {"lat": 7.47734, "lng": 4.35351},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 139485 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-gboko",
      name: "Gboko",
      coordinates: {"lat": 7.32275, "lng": 9.00108},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 365000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-gashua",
      name: "Gashua",
      coordinates: {"lat": 12.87398, "lng": 11.04057},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 125817 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-birnin-kebbi",
      name: "Birnin Kebbi",
      coordinates: {"lat": 12.45389, "lng": 4.1975},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 108164 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-alasia",
      name: "Alasia",
      coordinates: {"lat": 6.47489, "lng": 3.16914},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 100000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-akure",
      name: "Akure",
      coordinates: {"lat": 7.25256, "lng": 5.19312},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 730000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-agege",
      name: "Agege",
      coordinates: {"lat": 6.61563, "lng": 3.33337},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 683600 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-zaria",
      name: "Zaria",
      coordinates: {"lat": 11.11128, "lng": 7.7227},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 980000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-wukari",
      name: "Wukari",
      coordinates: {"lat": 7.87139, "lng": 9.77786},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 92933 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-suleja",
      name: "Suleja",
      coordinates: {"lat": 9.18059, "lng": 7.17939},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 162135 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-patigi",
      name: "Patigi",
      coordinates: {"lat": 8.72851, "lng": 5.75561},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 28285 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-okigwe",
      name: "Okigwe",
      coordinates: {"lat": 5.82917, "lng": 7.35056},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 115499 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-nkpor",
      name: "Nkpor",
      coordinates: {"lat": 6.15038, "lng": 6.83042},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 103733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-makoko",
      name: "Makoko",
      coordinates: {"lat": 6.49611, "lng": 3.38778},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 85840 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-lokoja",
      name: "Lokoja",
      coordinates: {"lat": 7.79688, "lng": 6.74048},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 60579 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-jalingo",
      name: "Jalingo",
      coordinates: {"lat": 8.89367, "lng": 11.3596},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 117757 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-iperu",
      name: "Iperu",
      coordinates: {"lat": 6.91002, "lng": 3.66557},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 15935 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-gombe",
      name: "Gombe",
      coordinates: {"lat": 10.28969, "lng": 11.16729},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 560000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-bukuru",
      name: "Bukuru",
      coordinates: {"lat": 9.79399, "lng": 8.86397},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 15540 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-auchi",
      name: "Auchi",
      coordinates: {"lat": 7.06756, "lng": 6.2636},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 62907 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-warri",
      name: "Warri",
      coordinates: {"lat": 5.51737, "lng": 5.75006},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 910000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-uyo",
      name: "Uyo",
      coordinates: {"lat": 5.05127, "lng": 7.9335},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 436606 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-owo",
      name: "Owo",
      coordinates: {"lat": 7.1962, "lng": 5.58681},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 276574 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ogbomoso",
      name: "Ogbomoso",
      coordinates: {"lat": 8.13373, "lng": 4.24014},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 433030 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-nkwerre",
      name: "Nkwerre",
      coordinates: {"lat": 5.75917, "lng": 7.10384},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 62973 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-makurdi",
      name: "Makurdi",
      coordinates: {"lat": 7.73375, "lng": 8.52139},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 390000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-river-atuwara",
      name: "River Atuwara",
      coordinates: {"lat": 6.68194, "lng": 3.14306},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15937 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ijebu-ode",
      name: "Ijebu Ode",
      coordinates: {"lat": 6.81944, "lng": 3.91731},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 360000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-idah",
      name: "Idah",
      coordinates: {"lat": 7.11345, "lng": 6.73866},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 68703 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-gusau",
      name: "Gusau",
      coordinates: {"lat": 12.17024, "lng": 6.66412},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 226857 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-elele",
      name: "Elele",
      coordinates: {"lat": 5.1009, "lng": 6.81411},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 20620 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ekpoma",
      name: "Ekpoma",
      coordinates: {"lat": 6.743, "lng": 6.14029},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 59618 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-agbor",
      name: "Agbor",
      coordinates: {"lat": 6.25375, "lng": 6.1942},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 67610 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-abakaliki",
      name: "Abakaliki",
      coordinates: {"lat": 6.32485, "lng": 8.11368},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 134102 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-yola",
      name: "Yola",
      coordinates: {"lat": 9.20839, "lng": 12.48146},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 460000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-wudil",
      name: "Wudil",
      coordinates: {"lat": 11.80937, "lng": 8.84422},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23066 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-wamba",
      name: "Wamba",
      coordinates: {"lat": 8.94153, "lng": 8.60315},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27137 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-uromi",
      name: "Uromi",
      coordinates: {"lat": 6.7, "lng": 6.33333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 108608 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-talata-mafara",
      name: "Talata Mafara",
      coordinates: {"lat": 12.56841, "lng": 6.06225},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39045 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-surulere",
      name: "Surulere",
      coordinates: {"lat": 6.50153, "lng": 3.35808},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 191920 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-saki",
      name: "Saki",
      coordinates: {"lat": 8.66762, "lng": 3.39393},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 178677 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ota",
      name: "Ota",
      coordinates: {"lat": 6.68867, "lng": 3.23202},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 251546 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-okene",
      name: "Okene",
      coordinates: {"lat": 7.55122, "lng": 6.23589},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 479178 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ogaminana",
      name: "Ogaminana",
      coordinates: {"lat": 7.59383, "lng": 6.21798},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 84373 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-obudu",
      name: "Obudu",
      coordinates: {"lat": 6.66819, "lng": 9.16453},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19668 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-nsukka",
      name: "Nsukka",
      coordinates: {"lat": 6.85783, "lng": 7.39577},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 111017 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-nasarawa",
      name: "Nasarawa",
      coordinates: {"lat": 8.53895, "lng": 7.70821},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 30949 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-mubi",
      name: "Mubi",
      coordinates: {"lat": 10.26858, "lng": 13.26701},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 225705 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-lapai",
      name: "Lapai",
      coordinates: {"lat": 9.04439, "lng": 6.57089},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16442 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-lafia",
      name: "Lafia",
      coordinates: {"lat": 8.4939, "lng": 8.51532},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 127236 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kwale",
      name: "Kwale",
      coordinates: {"lat": 5.70773, "lng": 6.43402},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20226 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kontagora",
      name: "Kontagora",
      coordinates: {"lat": 10.40319, "lng": 5.4708},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 98754 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kagoro",
      name: "Kagoro",
      coordinates: {"lat": 9.60776, "lng": 8.39043},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 77008 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kafanchan",
      name: "Kafanchan",
      coordinates: {"lat": 9.58126, "lng": 8.2926},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 79522 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kachia",
      name: "Kachia",
      coordinates: {"lat": 9.87342, "lng": 7.95407},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 30893 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-kabba",
      name: "Kabba",
      coordinates: {"lat": 7.82719, "lng": 6.07502},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 49869 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-jos",
      name: "Jos",
      coordinates: {"lat": 9.92849, "lng": 8.89212},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1040000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-jimeta",
      name: "Jimeta",
      coordinates: {"lat": 9.27949, "lng": 12.45819},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 248148 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-iyesi",
      name: "Iyesi",
      coordinates: {"lat": 6.66056, "lng": 3.1798},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17220 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ilaro",
      name: "Ilaro",
      coordinates: {"lat": 6.88901, "lng": 3.01416},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 46999 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ila-orangun",
      name: "Ila Orangun",
      coordinates: {"lat": 8.01714, "lng": 4.90421},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 179192 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ikirun",
      name: "Ikirun",
      coordinates: {"lat": 7.91283, "lng": 4.66741},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 134240 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ijebu-igbo",
      name: "Ijebu-Igbo",
      coordinates: {"lat": 6.97198, "lng": 3.99938},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 109261 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ihiala",
      name: "Ihiala",
      coordinates: {"lat": 5.85475, "lng": 6.85944},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 83265 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-ile-ife",
      name: "Ile-Ife",
      coordinates: {"lat": 7.4824, "lng": 4.56032},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 560000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-geidam",
      name: "Geidam",
      coordinates: {"lat": 12.89439, "lng": 11.92649},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 41367 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-fiditi",
      name: "Fiditi",
      coordinates: {"lat": 7.71393, "lng": 3.91665},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 71461 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-eruwa",
      name: "Eruwa",
      coordinates: {"lat": 7.53906, "lng": 3.42453},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 34802 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-enugu-ukwu",
      name: "Enugu-Ukwu",
      coordinates: {"lat": 6.17146, "lng": 7.00525},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 68785 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-dutse",
      name: "Dutse",
      coordinates: {"lat": 11.75618, "lng": 9.33896},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17129 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-daura",
      name: "Daura",
      coordinates: {"lat": 13.03299, "lng": 8.32351},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25289 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-damaturu",
      name: "Damaturu",
      coordinates: {"lat": 11.74697, "lng": 11.96083},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 46000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-biu",
      name: "Biu",
      coordinates: {"lat": 10.61285, "lng": 12.19458},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 95005 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-biliri",
      name: "Biliri",
      coordinates: {"lat": 9.86709, "lng": 11.22594},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15976 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-bida",
      name: "Bida",
      coordinates: {"lat": 9.08044, "lng": 6.0099},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 400000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-beli",
      name: "Beli",
      coordinates: {"lat": 7.85868, "lng": 10.97187},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17467 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-awgu",
      name: "Awgu",
      coordinates: {"lat": 6.07278, "lng": 7.47739},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 23175 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-asaba",
      name: "Asaba",
      coordinates: {"lat": 6.19824, "lng": 6.73187},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 73374 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "nigeria-aku",
      name: "Aku",
      coordinates: {"lat": 6.70902, "lng": 7.31826},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 73742 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Nigeria",
  capital: "Abuja",
  currency: "NGN",
  language: "inglés",
  continent: "África",
  population: 237527782,
  cities,
  // Las universidades no van aqui: viven en ./universities/nigeria.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 115,
  aliases: ["nigeria"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
