// Pakistán — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "pakistan";
const countryName = "Pakistán";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/pakistan.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "pakistan-pakistan-employees-cooperative-housing-society",
      name: "Pakistan Employees Cooperative Housing Society",
      coordinates: {"lat": 24.87417, "lng": 67.06419},
      isCapital: false,
      universityCount: 19,
      statistics: { population: 19500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-islamabad",
      name: "Islamabad",
      coordinates: {"lat": 33.72148, "lng": 73.04329},
      isCapital: true,
      universityCount: 15,
      statistics: { population: 601600 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-rawalpindi",
      name: "Rawalpindi",
      coordinates: {"lat": 33.59733, "lng": 73.0479},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 3357612 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-multan",
      name: "Multan",
      coordinates: {"lat": 30.19679, "lng": 71.47824},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 2169915 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-faisalabad",
      name: "Faisalabad",
      coordinates: {"lat": 31.41554, "lng": 73.08969},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 3800193 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-peshawar",
      name: "Peshawar",
      coordinates: {"lat": 34.008, "lng": 71.57849},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 4758762 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-model-town",
      name: "Model Town",
      coordinates: {"lat": 31.48104, "lng": 74.32563},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 100000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-karachi",
      name: "Karachi",
      coordinates: {"lat": 24.8608, "lng": 67.0104},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 11624219 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-kotri",
      name: "Kotri",
      coordinates: {"lat": 25.36566, "lng": 68.30831},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 106615 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-karachi-university-employees-co-operative-housing-society",
      name: "Karachi University Employees Co-operative Housing Society",
      coordinates: {"lat": 24.96281, "lng": 67.11937},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 41000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-raiwind",
      name: "Raiwind",
      coordinates: {"lat": 31.24895, "lng": 74.21534},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 31592 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-nawabshah",
      name: "Nawabshah",
      coordinates: {"lat": 26.23939, "lng": 68.40369},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 363138 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-mardan",
      name: "Mardan",
      coordinates: {"lat": 34.19794, "lng": 72.04965},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 300424 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-alipur",
      name: "Alipur",
      coordinates: {"lat": 33.64894, "lng": 73.17787},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 17566 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-wah-cantt",
      name: "Wah Cantt",
      coordinates: {"lat": 33.77094, "lng": 72.75116},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 400733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-sialkot",
      name: "Sialkot",
      coordinates: {"lat": 32.49268, "lng": 74.53134},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 911817 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-sargodha",
      name: "Sargodha",
      coordinates: {"lat": 32.08586, "lng": 72.67418},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 975886 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-jamrud",
      name: "Jamrud",
      coordinates: {"lat": 34.00152, "lng": 71.38007},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 56642 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-jalalpur-jattan",
      name: "Jalalpur Jattan",
      coordinates: {"lat": 32.64118, "lng": 74.20561},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 146743 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-abbottabad",
      name: "Abbottabad",
      coordinates: {"lat": 34.1463, "lng": 73.21168},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 275890 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-risalpur-cantonment",
      name: "Risalpur Cantonment",
      coordinates: {"lat": 34.06048, "lng": 71.99276},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 36074 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-rawalakot",
      name: "Rawalakot",
      coordinates: {"lat": 33.85782, "lng": 73.76043},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-uthal",
      name: "Uthal",
      coordinates: {"lat": 25.80722, "lng": 66.62194},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16483 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-topi",
      name: "Topi",
      coordinates: {"lat": 34.07034, "lng": 72.62147},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 74867 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-tando-jam",
      name: "Tando Jam",
      coordinates: {"lat": 25.42813, "lng": 68.52923},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 71760 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-skardu",
      name: "Skardu",
      coordinates: {"lat": 35.29787, "lng": 75.63372},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 260000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-sharqpur-sharif",
      name: "Sharqpur Sharif",
      coordinates: {"lat": 31.46116, "lng": 74.10091},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31855 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-renala-khurd",
      name: "Renala Khurd",
      coordinates: {"lat": 30.87878, "lng": 73.59857},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 100054 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-quetta",
      name: "Quetta",
      coordinates: {"lat": 30.18414, "lng": 67.00141},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1565546 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-new-mirpur-city",
      name: "New Mirpur City",
      coordinates: {"lat": 33.14782, "lng": 73.75187},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 124352 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-narowal",
      name: "Narowal",
      coordinates: {"lat": 32.10197, "lng": 74.87303},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 130692 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-nankana-sahib",
      name: "Nankana Sahib",
      coordinates: {"lat": 31.4501, "lng": 73.70653},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 130041 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-murree",
      name: "Murree",
      coordinates: {"lat": 33.90836, "lng": 73.3903},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 25186 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-mandi-bahauddin",
      name: "Mandi Bahauddin",
      coordinates: {"lat": 32.58704, "lng": 73.49123},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 129733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-lahore",
      name: "Lahore",
      coordinates: {"lat": 31.558, "lng": 74.35071},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 13004135 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-kot-malik-barkhurdar",
      name: "Kot Malik Barkhurdar",
      coordinates: {"lat": 30.20379, "lng": 66.98723},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 69359 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-khuzdar",
      name: "Khuzdar",
      coordinates: {"lat": 27.81193, "lng": 66.61096},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 218112 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-jhang-sadr",
      name: "Jhang Sadr",
      coordinates: {"lat": 31.26981, "lng": 72.31687},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 606533 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-hyderabad",
      name: "Hyderabad",
      coordinates: {"lat": 25.39689, "lng": 68.37718},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1921275 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-havelian",
      name: "Havelian",
      coordinates: {"lat": 34.05348, "lng": 73.15993},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 37509 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-haripur",
      name: "Haripur",
      coordinates: {"lat": 33.99783, "lng": 72.93493},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56977 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-gwadar",
      name: "Gwadar",
      coordinates: {"lat": 25.12163, "lng": 62.32541},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 70852 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-gilgit",
      name: "Gilgit",
      coordinates: {"lat": 35.91869, "lng": 74.31245},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 216760 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-gharo",
      name: "Gharo",
      coordinates: {"lat": 24.74182, "lng": 67.58534},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 19524 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-bat-khela",
      name: "Bat Khela",
      coordinates: {"lat": 34.6178, "lng": 71.97247},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 73525 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-bahawalpur",
      name: "Bahawalpur",
      coordinates: {"lat": 29.39779, "lng": 71.6752},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 903795 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-bagh",
      name: "Bāgh",
      coordinates: {"lat": 33.98111, "lng": 73.77608},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 33548 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-baffa",
      name: "Baffa",
      coordinates: {"lat": 34.4377, "lng": 73.22368},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17556 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Pakistan",
  capital: "Islamabad",
  currency: "PKR",
  language: "urdu",
  continent: "Asia",
  population: 255219554,
  cities,
  // Las universidades no van aqui: viven en ./universities/pakistan.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 136,
  aliases: ["pakistan"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
