// Pakistán — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "pakistan";
const countryName = "Pakistán";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/pakistan.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "pakistan-karachi",
      name: "Karachi",
      coordinates: {"lat": 24.8608, "lng": 67.0104},
      isCapital: false,
      universityCount: 30,
      statistics: { population: 11624219 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-lahore",
      name: "Lahore",
      coordinates: {"lat": 31.558, "lng": 74.35071},
      isCapital: false,
      universityCount: 28,
      statistics: { population: 13004135 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-islamabad",
      name: "Islamabad",
      coordinates: {"lat": 33.72148, "lng": 73.04329},
      isCapital: true,
      universityCount: 23,
      statistics: { population: 601600 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-rawalpindi",
      name: "Rawalpindi",
      coordinates: {"lat": 33.59733, "lng": 73.0479},
      isCapital: false,
      universityCount: 15,
      statistics: { population: 3357612 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-pakistan-employees-cooperative-housing-society",
      name: "Pakistan Employees Cooperative Housing Society",
      coordinates: {"lat": 24.87417, "lng": 67.06419},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 19500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-peshawar",
      name: "Peshawar",
      coordinates: {"lat": 34.008, "lng": 71.57849},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 4758762 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-faisalabad",
      name: "Faisalabad",
      coordinates: {"lat": 31.41554, "lng": 73.08969},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 3800193 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-multan",
      name: "Multan",
      coordinates: {"lat": 30.19679, "lng": 71.47824},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 2169915 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-model-town",
      name: "Model Town",
      coordinates: {"lat": 31.48104, "lng": 74.32563},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 100000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-nawabshah",
      name: "Nawabshah",
      coordinates: {"lat": 26.23939, "lng": 68.40369},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 363138 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-quetta",
      name: "Quetta",
      coordinates: {"lat": 30.18414, "lng": 67.00141},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1565546 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-sialkot",
      name: "Sialkot",
      coordinates: {"lat": 32.49268, "lng": 74.53134},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 911817 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-raiwind",
      name: "Raiwind",
      coordinates: {"lat": 31.24895, "lng": 74.21534},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 31592 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-mardan",
      name: "Mardan",
      coordinates: {"lat": 34.19794, "lng": 72.04965},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 300424 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-kotri",
      name: "Kotri",
      coordinates: {"lat": 25.36566, "lng": 68.30831},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 106615 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-abbottabad",
      name: "Abbottabad",
      coordinates: {"lat": 34.1463, "lng": 73.21168},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 275890 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-karachi-university-employees-co-operative-housing-society",
      name: "Karachi University Employees Co-operative Housing Society",
      coordinates: {"lat": 24.96281, "lng": 67.11937},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 41000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-khairpur-mir-s",
      name: "Khairpur Mir’s",
      coordinates: {"lat": 27.52948, "lng": 68.75915},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 191044 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-alipur",
      name: "Alipur",
      coordinates: {"lat": 33.64894, "lng": 73.17787},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 17566 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-risalpur-cantonment",
      name: "Risalpur Cantonment",
      coordinates: {"lat": 34.06048, "lng": 71.99276},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 36074 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-skardu",
      name: "Skardu",
      coordinates: {"lat": 35.29787, "lng": 75.63372},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 260000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-sargodha",
      name: "Sargodha",
      coordinates: {"lat": 32.08586, "lng": 72.67418},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 975886 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-rahim-yar-khan",
      name: "Rahim Yar Khan",
      coordinates: {"lat": 28.41987, "lng": 70.30345},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 517000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-mandi-bahauddin",
      name: "Mandi Bahauddin",
      coordinates: {"lat": 32.58704, "lng": 73.49123},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 129733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-kohat",
      name: "Kohat",
      coordinates: {"lat": 33.58196, "lng": 71.44929},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 151427 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-kalabagh",
      name: "Kalabagh",
      coordinates: {"lat": 32.96164, "lng": 71.54638},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15976 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-jhang-sadr",
      name: "Jhang Sadr",
      coordinates: {"lat": 31.26981, "lng": 72.31687},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 606533 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-jamrud",
      name: "Jamrud",
      coordinates: {"lat": 34.00152, "lng": 71.38007},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 56642 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-jalalpur-jattan",
      name: "Jalalpur Jattan",
      coordinates: {"lat": 32.64118, "lng": 74.20561},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 146743 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-gujranwala",
      name: "Gujranwala",
      coordinates: {"lat": 32.15567, "lng": 74.18705},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 2511118 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-dera-ghazi-khan",
      name: "Dera Ghazi Khan",
      coordinates: {"lat": 30.04587, "lng": 70.64029},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 494464 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-bahawalpur",
      name: "Bahawalpur",
      coordinates: {"lat": 29.39779, "lng": 71.6752},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 903795 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "pakistan-wah-cantt",
      name: "Wah Cantt",
      coordinates: {"lat": 33.77094, "lng": 72.75116},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 400733 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Pakistan",
  capital: "Islamabad",
  currency: "PKR",
  language: "urdu",
  continent: "Asia",
  population: 255219554,
  cities,
  // Las universidades no van aqui: viven en ./universities/pakistan.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 136,
  aliases: ["pakistan"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
