// Polonia — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "polonia";
const countryName = "Polonia";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/polonia.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "polonia-krakow",
      name: "Kraków",
      coordinates: {"lat": 50.06143, "lng": 19.93658},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 816614 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-poznan",
      name: "Poznań",
      coordinates: {"lat": 52.40692, "lng": 16.92993},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 536151 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-lublin",
      name: "Lublin",
      coordinates: {"lat": 51.25058, "lng": 22.57009},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 336339 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-odz",
      name: "Łódź",
      coordinates: {"lat": 51.77058, "lng": 19.47395},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 639890 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-srodmiescie-758470",
      name: "Śródmieście",
      coordinates: {"lat": 52.22904, "lng": 21.01644},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 99950 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-katowice",
      name: "Katowice",
      coordinates: {"lat": 50.2597, "lng": 19.02173},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 286960 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-kielce",
      name: "Kielce",
      coordinates: {"lat": 50.87033, "lng": 20.62752},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 192468 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-bia-ystok",
      name: "Białystok",
      coordinates: {"lat": 53.13333, "lng": 23.16433},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 295683 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-czestochowa",
      name: "Częstochowa",
      coordinates: {"lat": 50.79646, "lng": 19.12409},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 248125 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-ursynow",
      name: "Ursynów",
      coordinates: {"lat": 52.15051, "lng": 21.05041},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 149775 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-wola",
      name: "Wola",
      coordinates: {"lat": 52.23477, "lng": 20.96004},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 140958 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-warsaw",
      name: "Warsaw",
      coordinates: {"lat": 52.22977, "lng": 21.01178},
      isCapital: true,
      universityCount: 3,
      statistics: { population: 1702139 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-olsztyn",
      name: "Olsztyn",
      coordinates: {"lat": 53.78376, "lng": 20.49272},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 169793 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-ochota",
      name: "Ochota",
      coordinates: {"lat": 52.22096, "lng": 20.98526},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 82774 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-gdynia",
      name: "Gdynia",
      coordinates: {"lat": 54.51889, "lng": 18.53188},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 257000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-bydgoszcz",
      name: "Bydgoszcz",
      coordinates: {"lat": 53.1235, "lng": 18.00762},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 330038 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-bielany",
      name: "Bielany",
      coordinates: {"lat": 52.29242, "lng": 20.93531},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 131910 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-zielona-gora",
      name: "Zielona Góra",
      coordinates: {"lat": 51.93548, "lng": 15.50643},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 118433 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-szczecin",
      name: "Szczecin",
      coordinates: {"lat": 53.42894, "lng": 14.55302},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 395513 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-opole",
      name: "Opole",
      coordinates: {"lat": 50.67119, "lng": 17.92604},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 127676 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-rejon-placu-swietego-macieja",
      name: "Rejon placu Świętego Macieja",
      coordinates: {"lat": 51.12056, "lng": 17.03761},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 44090 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-zoliborz",
      name: "Żoliborz",
      coordinates: {"lat": 52.26896, "lng": 20.98644},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50934 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-targowek",
      name: "Targówek",
      coordinates: {"lat": 52.29185, "lng": 21.04845},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 124279 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-rzeszow",
      name: "Rzeszów",
      coordinates: {"lat": 50.04132, "lng": 21.99901},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 198317 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-rembertow",
      name: "Rembertów",
      coordinates: {"lat": 52.26059, "lng": 21.16355},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21893 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-radom",
      name: "Radom",
      coordinates: {"lat": 51.40253, "lng": 21.14714},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 226794 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-mokotow",
      name: "Mokotów",
      coordinates: {"lat": 52.1934, "lng": 21.03487},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 217683 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-jaros-aw",
      name: "Jarosław",
      coordinates: {"lat": 50.01623, "lng": 22.67776},
      isCapital: false,
      universityCount: 0,
      statistics: { population: 35475 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-wrzeszcz",
      name: "Wrzeszcz",
      coordinates: {"lat": 54.37648, "lng": 18.60753},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 65000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-wroc-aw",
      name: "Wrocław",
      coordinates: {"lat": 51.10286, "lng": 17.03006},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 672545 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-torun",
      name: "Toruń",
      coordinates: {"lat": 53.01375, "lng": 18.59814},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 196935 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-s-upsk",
      name: "Słupsk",
      coordinates: {"lat": 54.46405, "lng": 17.02872},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 98608 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-mys-owice",
      name: "Mysłowice",
      coordinates: {"lat": 50.20745, "lng": 19.16668},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 72124 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-grzegorzki",
      name: "Grzegórzki",
      coordinates: {"lat": 50.06423, "lng": 19.96761},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 28960 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-bielsko-biala",
      name: "Bielsko-Biala",
      coordinates: {"lat": 49.82245, "lng": 19.04686},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 176515 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-praga-po-noc",
      name: "Praga Północ",
      coordinates: {"lat": 52.25443, "lng": 21.03472},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 93192 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-swierczewo",
      name: "Świerczewo",
      coordinates: {"lat": 53.4273, "lng": 14.51303},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 16034 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-rejon-placu-grunwaldzkiego",
      name: "Rejon placu Grunwaldzkiego",
      coordinates: {"lat": 51.11669, "lng": 17.06126},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27030 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "polonia-srodmiescie-13562332",
      name: "Śródmieście",
      coordinates: {"lat": 51.11316, "lng": 17.08145},
      isCapital: false,
      universityCount: 1,
      statistics: { population: 99088 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Poland",
  capital: "Warsaw",
  currency: "PLN",
  language: "polaco",
  continent: "Europa",
  population: 36435861,
  cities,
  // Las universidades no van aqui: viven en ./universities/polonia.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 138,
  aliases: ["poland", "polonia"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
