// Reino Unido — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "reino-unido";
const countryName = "Reino Unido";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/reino-unido.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "reino-unido-soho",
      name: "Soho",
      coordinates: {"lat": 51.5144, "lng": -0.13535},
      isCapital: false,
      universityCount: 10,
      statistics: { population: 19634 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-london",
      name: "London",
      coordinates: {"lat": 51.50853, "lng": -0.12574},
      isCapital: true,
      universityCount: 7,
      statistics: { population: 8961989 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-glasgow",
      name: "Glasgow",
      coordinates: {"lat": 55.86515, "lng": -4.25763},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 626410 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-birmingham",
      name: "Birmingham",
      coordinates: {"lat": 52.48142, "lng": -1.89983},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 1157603 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-oxford",
      name: "Oxford",
      coordinates: {"lat": 51.75222, "lng": -1.25596},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 162100 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-liverpool",
      name: "Liverpool",
      coordinates: {"lat": 53.41058, "lng": -2.97794},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 496770 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-edinburgh",
      name: "Edinburgh",
      coordinates: {"lat": 55.95206, "lng": -3.19648},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 514990 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-cambridge",
      name: "Cambridge",
      coordinates: {"lat": 52.2, "lng": 0.11667},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 145674 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-manchester",
      name: "Manchester",
      coordinates: {"lat": 53.48095, "lng": -2.23743},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 568996 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-cardiff",
      name: "Cardiff",
      coordinates: {"lat": 51.48, "lng": -3.18},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 372089 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-plymouth",
      name: "Plymouth",
      coordinates: {"lat": 50.37153, "lng": -4.14305},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 260203 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-durham",
      name: "Durham",
      coordinates: {"lat": 54.77676, "lng": -1.57566},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 47785 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-dundee",
      name: "Dundee",
      coordinates: {"lat": 56.46913, "lng": -2.97489},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 148210 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-canterbury",
      name: "Canterbury",
      coordinates: {"lat": 51.27904, "lng": 1.07992},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 55087 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-bristol",
      name: "Bristol",
      coordinates: {"lat": 51.45523, "lng": -2.59665},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 479024 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-bath",
      name: "Bath",
      coordinates: {"lat": 51.3751, "lng": -2.36172},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 101557 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-bayswater",
      name: "Bayswater",
      coordinates: {"lat": 51.51116, "lng": -0.18426},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 17500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-southampton",
      name: "Southampton",
      coordinates: {"lat": 50.90395, "lng": -1.40428},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 269781 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-saint-andrews",
      name: "Saint Andrews",
      coordinates: {"lat": 56.33871, "lng": -2.79902},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 18410 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-plumstead",
      name: "Plumstead",
      coordinates: {"lat": 51.48333, "lng": 0.08333},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 16736 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-lincoln",
      name: "Lincoln",
      coordinates: {"lat": 53.22683, "lng": -0.53792},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 103813 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-leicester",
      name: "Leicester",
      coordinates: {"lat": 52.6386, "lng": -1.13169},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 368600 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-islington",
      name: "Islington",
      coordinates: {"lat": 51.53622, "lng": -0.10304},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 319143 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-guildford",
      name: "Guildford",
      coordinates: {"lat": 51.23536, "lng": -0.57427},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 71873 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-gillingham",
      name: "Gillingham",
      coordinates: {"lat": 51.38914, "lng": 0.54863},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 101187 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-chelsea",
      name: "Chelsea",
      coordinates: {"lat": 51.48755, "lng": -0.16936},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 60000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-brighton",
      name: "Brighton",
      coordinates: {"lat": 50.82838, "lng": -0.13947},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 283870 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-belfast",
      name: "Belfast",
      coordinates: {"lat": 54.59682, "lng": -5.92541},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 348005 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-aberdeen",
      name: "Aberdeen",
      coordinates: {"lat": 57.14369, "lng": -2.09814},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 198590 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-shadwell",
      name: "Shadwell",
      coordinates: {"lat": 51.51135, "lng": -0.05663},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 15110 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-york",
      name: "York",
      coordinates: {"lat": 53.95763, "lng": -1.08271},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 156135 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-swansea",
      name: "Swansea",
      coordinates: {"lat": 51.62079, "lng": -3.94323},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 300352 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-stratford",
      name: "Stratford",
      coordinates: {"lat": 51.53333, "lng": 0.0},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 36666 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-shepherds-bush",
      name: "Shepherds Bush",
      coordinates: {"lat": 51.505, "lng": -0.2211},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39724 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-sheffield",
      name: "Sheffield",
      coordinates: {"lat": 53.38297, "lng": -1.4659},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 556500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-roehampton",
      name: "Roehampton",
      coordinates: {"lat": 51.45165, "lng": -0.24393},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 16132 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-nottingham",
      name: "Nottingham",
      coordinates: {"lat": 52.9536, "lng": -1.15047},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 323632 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-new-cross",
      name: "New Cross",
      coordinates: {"lat": 51.47534, "lng": -0.03837},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15756 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-newcastle-upon-tyne",
      name: "Newcastle upon Tyne",
      coordinates: {"lat": 54.97328, "lng": -1.61396},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 300125 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-middlesbrough",
      name: "Middlesbrough",
      coordinates: {"lat": 54.57623, "lng": -1.23483},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 142707 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-mangotsfield",
      name: "Mangotsfield",
      coordinates: {"lat": 51.4878, "lng": -2.50403},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 36427 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-leeds",
      name: "Leeds",
      coordinates: {"lat": 53.79648, "lng": -1.54785},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 536280 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-lancaster",
      name: "Lancaster",
      coordinates: {"lat": 54.04649, "lng": -2.79988},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 47162 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-huddersfield",
      name: "Huddersfield",
      coordinates: {"lat": 53.64904, "lng": -1.78416},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 149017 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-highbury",
      name: "Highbury",
      coordinates: {"lat": 51.55, "lng": -0.1},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 26664 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-greenwich",
      name: "Greenwich",
      coordinates: {"lat": 51.47785, "lng": -0.01176},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 30578 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-gloucester",
      name: "Gloucester",
      coordinates: {"lat": 51.86568, "lng": -2.2431},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 132416 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-falmouth",
      name: "Falmouth",
      coordinates: {"lat": 50.15441, "lng": -5.07113},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31988 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-exmouth",
      name: "Exmouth",
      coordinates: {"lat": 50.61723, "lng": -3.40233},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 36204 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-coventry",
      name: "Coventry",
      coordinates: {"lat": 52.40656, "lng": -1.51217},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 345324 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-chichester",
      name: "Chichester",
      coordinates: {"lat": 50.83673, "lng": -0.78003},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 31654 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-chatham",
      name: "Chatham",
      coordinates: {"lat": 51.37891, "lng": 0.52786},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 80596 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-bradford",
      name: "Bradford",
      coordinates: {"lat": 53.79391, "lng": -1.75206},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 366187 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-bangor",
      name: "Bangor",
      coordinates: {"lat": 53.22752, "lng": -4.12936},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18322 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-aston",
      name: "Aston",
      coordinates: {"lat": 52.5, "lng": -1.88333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 32286 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-aberystwyth",
      name: "Aberystwyth",
      coordinates: {"lat": 52.41548, "lng": -4.08292},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 18749 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-surbiton",
      name: "Surbiton",
      coordinates: {"lat": 51.39148, "lng": -0.29825},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 38158 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-bartley-green",
      name: "Bartley Green",
      coordinates: {"lat": 52.43532, "lng": -1.99707},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22670 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "reino-unido-ealing-common",
      name: "Ealing Common",
      coordinates: {"lat": 51.50686, "lng": -0.29546},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 15945 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "United Kingdom",
  capital: "London",
  currency: "GBP",
  language: "inglés",
  continent: "Europa",
  population: 69487000,
  cities,
  // Las universidades no van aqui: viven en ./universities/reino-unido.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 193,
  aliases: ["reino-unido", "united-kingdom"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
