// Rusia — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "rusia";
const countryName = "Rusia";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/rusia.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "rusia-moscow",
      name: "Moscow",
      coordinates: {"lat": 55.75204, "lng": 37.61781},
      isCapital: true,
      universityCount: 32,
      statistics: { population: 10381222 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-saint-petersburg",
      name: "Saint Petersburg",
      coordinates: {"lat": 59.93863, "lng": 30.31413},
      isCapital: false,
      universityCount: 20,
      statistics: { population: 5351935 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-yekaterinburg",
      name: "Yekaterinburg",
      coordinates: {"lat": 56.85733, "lng": 60.61529},
      isCapital: false,
      universityCount: 18,
      statistics: { population: 1495066 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-kazan",
      name: "Kazan",
      coordinates: {"lat": 55.78874, "lng": 49.12214},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 1243500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-novosibirsk",
      name: "Novosibirsk",
      coordinates: {"lat": 55.02259, "lng": 82.93175},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 1612833 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-omsk",
      name: "Omsk",
      coordinates: {"lat": 54.99244, "lng": 73.36859},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 1172070 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-admiralteisky",
      name: "Admiralteisky",
      coordinates: {"lat": 59.923, "lng": 30.3},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 157897 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-saratov",
      name: "Saratov",
      coordinates: {"lat": 51.54048, "lng": 45.9901},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 844858 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-voronezh",
      name: "Voronezh",
      coordinates: {"lat": 51.66833, "lng": 39.19204},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 1047549 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-nizhniy-novgorod",
      name: "Nizhniy Novgorod",
      coordinates: {"lat": 56.32867, "lng": 44.00205},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 1259013 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-zamoskvorech-ye",
      name: "Zamoskvorech’ye",
      coordinates: {"lat": 55.73333, "lng": 37.63333},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 55000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-samara",
      name: "Samara",
      coordinates: {"lat": 53.20767, "lng": 50.13553},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 1163399 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-rostov-on-don",
      name: "Rostov-on-Don",
      coordinates: {"lat": 47.21997, "lng": 39.70769},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 1130305 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-makhachkala",
      name: "Makhachkala",
      coordinates: {"lat": 42.97782, "lng": 47.50027},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 596356 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-tomsk",
      name: "Tomsk",
      coordinates: {"lat": 56.50049, "lng": 84.98216},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 574002 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-irkutsk",
      name: "Irkutsk",
      coordinates: {"lat": 52.29566, "lng": 104.29076},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 623869 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-lefortovo",
      name: "Lefortovo",
      coordinates: {"lat": 55.76667, "lng": 37.7},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 91000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-kaliningrad",
      name: "Kaliningrad",
      coordinates: {"lat": 54.70639, "lng": 20.51102},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 475056 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-krasnoyarsk",
      name: "Krasnoyarsk",
      coordinates: {"lat": 56.03742, "lng": 92.93136},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1090811 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-chelyabinsk",
      name: "Chelyabinsk",
      coordinates: {"lat": 55.1611, "lng": 61.42877},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1202371 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-vladivostok",
      name: "Vladivostok",
      coordinates: {"lat": 43.10562, "lng": 131.87353},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 604901 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-volgograd",
      name: "Volgograd",
      coordinates: {"lat": 48.71378, "lng": 44.4976},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 1013533 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-troparevo",
      name: "Troparëvo",
      coordinates: {"lat": 55.65625, "lng": 37.48496},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 118000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-sokol",
      name: "Sokol",
      coordinates: {"lat": 55.8, "lng": 37.51667},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 57000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-ryazan",
      name: "Ryazan’",
      coordinates: {"lat": 54.62696, "lng": 39.70415},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 538962 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-perm",
      name: "Perm",
      coordinates: {"lat": 58.01046, "lng": 56.25017},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 982419 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-krasnodar",
      name: "Krasnodar",
      coordinates: {"lat": 45.04534, "lng": 38.98178},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 899541 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-ivanovo",
      name: "Ivanovo",
      coordinates: {"lat": 56.99988, "lng": 40.97257},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 406113 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-petrogradka",
      name: "Petrogradka",
      coordinates: {"lat": 59.96567, "lng": 30.31154},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 130455 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-vasyl-evsky-ostrov",
      name: "Vasyl'evsky Ostrov",
      coordinates: {"lat": 59.94091, "lng": 30.25377},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 203058 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-ulyanovsk",
      name: "Ulyanovsk",
      coordinates: {"lat": 54.32824, "lng": 48.38657},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 626540 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-ufa",
      name: "Ufa",
      coordinates: {"lat": 54.74306, "lng": 55.96779},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 1120547 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-tver",
      name: "Tver",
      coordinates: {"lat": 56.85836, "lng": 35.90057},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 420065 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-stavropol",
      name: "Stavropol",
      coordinates: {"lat": 45.03442, "lng": 41.9642},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 433931 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-orenburg",
      name: "Orenburg",
      coordinates: {"lat": 51.76712, "lng": 55.09883},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 564773 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-izhevsk",
      name: "Izhevsk",
      coordinates: {"lat": 56.85225, "lng": 53.19862},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 648213 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-dorogomilovo",
      name: "Dorogomilovo",
      coordinates: {"lat": 55.7418, "lng": 37.54706},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 68000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-bryansk",
      name: "Bryansk",
      coordinates: {"lat": 53.27096, "lng": 34.32143},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 427236 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-tyumen",
      name: "Tyumen",
      coordinates: {"lat": 57.15222, "lng": 65.52722},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 768358 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-barnaul",
      name: "Barnaul",
      coordinates: {"lat": 53.36199, "lng": 83.72786},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 632372 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-khabarovsk",
      name: "Khabarovsk",
      coordinates: {"lat": 48.46204, "lng": 135.0971},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 618150 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-centralniy",
      name: "Centralniy",
      coordinates: {"lat": 59.93111, "lng": 30.36072},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 214625 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-yaroslavl",
      name: "Yaroslavl",
      coordinates: {"lat": 57.62987, "lng": 39.87368},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 608722 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-vatutino",
      name: "Vatutino",
      coordinates: {"lat": 55.88441, "lng": 37.69055},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-tambov",
      name: "Tambov",
      coordinates: {"lat": 52.73632, "lng": 41.44102},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 293661 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-pushkin",
      name: "Pushkin",
      coordinates: {"lat": 59.71417, "lng": 30.39642},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 92889 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-penza",
      name: "Penza",
      coordinates: {"lat": 53.19568, "lng": 45.01075},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 523553 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-novocherkassk",
      name: "Novocherkassk",
      coordinates: {"lat": 47.4222, "lng": 40.09373},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 166974 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-presnenskiy",
      name: "Presnenskiy",
      coordinates: {"lat": 55.75894, "lng": 37.55816},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 122000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-grozny",
      name: "Grozny",
      coordinates: {"lat": 43.31195, "lng": 45.68895},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 297137 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-belgorod",
      name: "Belgorod",
      coordinates: {"lat": 50.60343, "lng": 36.58091},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 345289 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-astrakhan",
      name: "Astrakhan",
      coordinates: {"lat": 46.34968, "lng": 48.04076},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 533925 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-arkhangel-sk",
      name: "Arkhangel’sk",
      coordinates: {"lat": 64.5461, "lng": 40.55183},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 349742 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-zheleznogorsk",
      name: "Zheleznogorsk",
      coordinates: {"lat": 56.25109, "lng": 93.53142},
      isCapital: false,
      universityCount: 0,
      statistics: { population: 93834 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-chita",
      name: "Chita",
      coordinates: {"lat": 52.04311, "lng": 113.49171},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 349005 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-blagoveshchensk",
      name: "Blagoveshchensk",
      coordinates: {"lat": 50.27593, "lng": 127.52637},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 225091 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-vladikavkaz",
      name: "Vladikavkaz",
      coordinates: {"lat": 43.04101, "lng": 44.66986},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 306258 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-veshnyaki",
      name: "Veshnyaki",
      coordinates: {"lat": 55.72393, "lng": 37.81952},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 122000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-tula",
      name: "Tula",
      coordinates: {"lat": 54.19609, "lng": 37.61822},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 482873 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-taganskiy",
      name: "Taganskiy",
      coordinates: {"lat": 55.73333, "lng": 37.66667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 116000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-smolensk",
      name: "Smolensk",
      coordinates: {"lat": 54.77826, "lng": 32.05088},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 330025 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-saransk",
      name: "Saransk",
      coordinates: {"lat": 54.18485, "lng": 45.17166},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 318841 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-peterhof",
      name: "Peterhof",
      coordinates: {"lat": 59.88333, "lng": 29.9},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 73199 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-orel",
      name: "Orël",
      coordinates: {"lat": 52.96879, "lng": 36.0791},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 303696 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-nikol-skoye",
      name: "Nikol’skoye",
      coordinates: {"lat": 55.68333, "lng": 37.48333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-nalchik",
      name: "Nalchik",
      coordinates: {"lat": 43.49806, "lng": 43.61889},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 239300 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-yaroslavskiy",
      name: "Yaroslavskiy",
      coordinates: {"lat": 55.88333, "lng": 37.71667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 91000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-lipetsk",
      name: "Lipetsk",
      coordinates: {"lat": 52.5876, "lng": 39.55151},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 509735 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-likhobory",
      name: "Likhobory",
      coordinates: {"lat": 55.85, "lng": 37.56667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-kursk",
      name: "Kursk",
      coordinates: {"lat": 51.72689, "lng": 36.18457},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 448733 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-kirov",
      name: "Kirov",
      coordinates: {"lat": 58.59809, "lng": 49.65783},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 507155 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-cheboksary",
      name: "Cheboksary",
      coordinates: {"lat": 56.13218, "lng": 47.246},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 492331 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-surgut",
      name: "Surgut",
      coordinates: {"lat": 61.25757, "lng": 73.41775},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 300367 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-kemerovo",
      name: "Kemerovo",
      coordinates: {"lat": 55.35417, "lng": 86.10435},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 558973 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-akademgorodok",
      name: "Akademgorodok",
      coordinates: {"lat": 54.8523, "lng": 83.106},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 50000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-yakutsk",
      name: "Yakutsk",
      coordinates: {"lat": 62.03114, "lng": 129.72288},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 235600 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-ulan-ude",
      name: "Ulan-Ude",
      coordinates: {"lat": 51.82648, "lng": 107.59979},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 360278 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-petropavlovsk-kamchatsky",
      name: "Petropavlovsk-Kamchatsky",
      coordinates: {"lat": 53.06393, "lng": 158.62751},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 181216 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-kalininskiy",
      name: "Kalininskiy",
      coordinates: {"lat": 59.99675, "lng": 30.3899},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 504641 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-finlyandskiy",
      name: "Finlyandskiy",
      coordinates: {"lat": 59.96824, "lng": 30.36415},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 72292 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "rusia-sampsonievskiy",
      name: "Sampsonievskiy",
      coordinates: {"lat": 59.98499, "lng": 30.34295},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 39318 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Russia",
  capital: "Moscow",
  currency: "RUB",
  language: "ruso",
  continent: "Europa",
  population: 143513328,
  cities,
  // Las universidades no van aqui: viven en ./universities/rusia.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 308,
  aliases: ["rusia", "russia"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
