// Tailandia — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "tailandia";
const countryName = "Tailandia";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/tailandia.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "tailandia-khlong-luang",
      name: "Khlong Luang",
      coordinates: {"lat": 14.06467, "lng": 100.64578},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 118551 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-chiang-mai",
      name: "Chiang Mai",
      coordinates: {"lat": 18.79038, "lng": 98.98468},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 127240 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-thon-buri",
      name: "Thon Buri",
      coordinates: {"lat": 13.725, "lng": 100.48511},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 119708 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-thawi-watthana",
      name: "Thawi Watthana",
      coordinates: {"lat": 13.78316, "lng": 100.37805},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 76351 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-sam-sen-nai",
      name: "Sam Sen Nai",
      coordinates: {"lat": 13.77714, "lng": 100.55082},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 30476 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-songkhla",
      name: "Songkhla",
      coordinates: {"lat": 7.19882, "lng": 100.5951},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 61758 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-nakhon-ratchasima",
      name: "Nakhon Ratchasima",
      coordinates: {"lat": 14.97066, "lng": 102.10196},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 126391 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-bang-yi-khan",
      name: "Bang Yi Khan",
      coordinates: {"lat": 13.76327, "lng": 100.48982},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 24745 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-lat-yao",
      name: "Lat Yao",
      coordinates: {"lat": 13.84725, "lng": 100.56373},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 41238 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-surat-thani",
      name: "Surat Thani",
      coordinates: {"lat": 9.14011, "lng": 99.33311},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 132040 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-nakhon-si-thammarat",
      name: "Nakhon Si Thammarat",
      coordinates: {"lat": 8.43333, "lng": 99.96667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 102152 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-lampang",
      name: "Lampang",
      coordinates: {"lat": 18.29232, "lng": 99.49277},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 156139 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-yala",
      name: "Yala",
      coordinates: {"lat": 6.53995, "lng": 101.28128},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 93558 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-phitsanulok",
      name: "Phitsanulok",
      coordinates: {"lat": 16.82481, "lng": 100.25858},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 62584 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-nakhon-sawan",
      name: "Nakhon Sawan",
      coordinates: {"lat": 15.70472, "lng": 100.13717},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 82305 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-nakhon-pathom",
      name: "Nakhon Pathom",
      coordinates: {"lat": 13.8196, "lng": 100.04427},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 117927 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-nakhon-nayok",
      name: "Nakhon Nayok",
      coordinates: {"lat": 14.20463, "lng": 101.21295},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21309 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-maha-sarakham",
      name: "Maha Sarakham",
      coordinates: {"lat": 16.18483, "lng": 103.30067},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 51584 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-kaeng-khoi",
      name: "Kaeng Khoi",
      coordinates: {"lat": 14.58617, "lng": 100.99758},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 30332 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-hat-yai",
      name: "Hat Yai",
      coordinates: {"lat": 7.00836, "lng": 100.47668},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 191696 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-dusit",
      name: "Dusit",
      coordinates: {"lat": 13.77706, "lng": 100.51958},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 107655 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-ban-lam-luk-ka",
      name: "Ban Lam Luk Ka",
      coordinates: {"lat": 13.97738, "lng": 100.77776},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 60700 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-ban-bang-kadi",
      name: "Ban Bang Kadi",
      coordinates: {"lat": 13.99904, "lng": 100.54962},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 27911 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-lat-krabang",
      name: "Lat Krabang",
      coordinates: {"lat": 13.72197, "lng": 100.78473},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 163175 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-lak-si",
      name: "Lak Si",
      coordinates: {"lat": 13.88724, "lng": 100.5792},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 109770 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-pathum-wan",
      name: "Pathum Wan",
      coordinates: {"lat": 13.73698, "lng": 100.52329},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 53263 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-suan-luang",
      name: "Suan Luang",
      coordinates: {"lat": 13.73028, "lng": 100.65138},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 115658 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-khwaeng-bang-plat",
      name: "Khwaeng Bang Plat",
      coordinates: {"lat": 13.78775, "lng": 100.49469},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 21953 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "tailandia-sena-nikhom",
      name: "Sena Nikhom",
      coordinates: {"lat": 13.83655, "lng": 100.57727},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20393 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Thailand",
  capital: "Bangkok",
  currency: "THB",
  language: "tailandés",
  continent: "Asia",
  population: 71619863,
  cities,
  // Las universidades no van aqui: viven en ./universities/tailandia.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 67,
  aliases: ["tailandia", "thailand"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
