// Taiwán — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "taiwan";
const countryName = "Taiwán";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/taiwan.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "taiwan-taipei",
      name: "Taipei",
      coordinates: {"lat": 25.05306, "lng": 121.52639},
      isCapital: true,
      universityCount: 15,
      statistics: { population: 7871900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-kaohsiung",
      name: "Kaohsiung",
      coordinates: {"lat": 22.61626, "lng": 120.31333},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 2737660 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-tainan",
      name: "Tainan",
      coordinates: {"lat": 22.99083, "lng": 120.21333},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 1856642 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-neihu",
      name: "Neihu",
      coordinates: {"lat": 25.0815, "lng": 121.58809},
      isCapital: false,
      universityCount: 9,
      statistics: { population: 274538 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-taichung",
      name: "Taichung",
      coordinates: {"lat": 24.1469, "lng": 120.6839},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 2850285 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-fengshan",
      name: "Fengshan",
      coordinates: {"lat": 22.62659, "lng": 120.36126},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 356463 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-hsinchu",
      name: "Hsinchu",
      coordinates: {"lat": 24.80361, "lng": 120.96861},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 453536 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-danshui",
      name: "Danshui",
      coordinates: {"lat": 25.17196, "lng": 121.4429},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 189271 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-chaozhou",
      name: "Chaozhou",
      coordinates: {"lat": 22.54987, "lng": 120.54067},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 53338 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-neili",
      name: "Neili",
      coordinates: {"lat": 24.9725, "lng": 121.26139},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 112845 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-chiayi-city",
      name: "Chiayi City",
      coordinates: {"lat": 23.47917, "lng": 120.44889},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 263188 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-new-taipei-city",
      name: "New Taipei City",
      coordinates: {"lat": 25.06199, "lng": 121.45703},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 4004367 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-yongkang",
      name: "Yongkang",
      coordinates: {"lat": 23.02444, "lng": 120.25556},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 233730 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-banqiao",
      name: "Banqiao",
      coordinates: {"lat": 25.01427, "lng": 121.46719},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 551221 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-hualien-city",
      name: "Hualien City",
      coordinates: {"lat": 23.97694, "lng": 121.60444},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 99458 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-douliu",
      name: "Douliu",
      coordinates: {"lat": 23.70944, "lng": 120.54333},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 107924 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-wufeng",
      name: "Wufeng",
      coordinates: {"lat": 24.0637, "lng": 120.698},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 65567 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-xinying",
      name: "Xinying",
      coordinates: {"lat": 23.30694, "lng": 120.31056},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 74972 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-shulin",
      name: "Shulin",
      coordinates: {"lat": 24.99085, "lng": 121.42199},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 180044 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-sanzhi",
      name: "Sanzhi",
      coordinates: {"lat": 25.25782, "lng": 121.50182},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 23452 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-buzi",
      name: "Buzi",
      coordinates: {"lat": 24.21013, "lng": 120.5725},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 40467 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-yuanlin",
      name: "Yuanlin",
      coordinates: {"lat": 23.95671, "lng": 120.57608},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 124725 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-bade",
      name: "Bade",
      coordinates: {"lat": 24.92981, "lng": 121.28372},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 209148 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-yilan",
      name: "Yilan",
      coordinates: {"lat": 24.757, "lng": 121.753},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 94188 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-keelung",
      name: "Keelung",
      coordinates: {"lat": 25.13089, "lng": 121.74094},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 362487 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "taiwan-taoyuan",
      name: "Taoyuan",
      coordinates: {"lat": 24.99368, "lng": 121.29696},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 475798 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Taiwan",
  capital: "Taipei",
  currency: "TWD",
  language: "chino",
  continent: "Asia",
  population: null,
  cities,
  // Las universidades no van aqui: viven en ./universities/taiwan.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 86,
  aliases: ["taiwan"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
