// Turquía — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "turquia";
const countryName = "Turquía";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/turquia.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "turquia-ankara",
      name: "Ankara",
      coordinates: {"lat": 39.91987, "lng": 32.85427},
      isCapital: true,
      universityCount: 11,
      statistics: { population: 3517182 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-golbas",
      name: "Gölbaşı",
      coordinates: {"lat": 39.79043, "lng": 32.80903},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 165201 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-gebze",
      name: "Gebze",
      coordinates: {"lat": 40.80276, "lng": 29.43068},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 281436 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-konya",
      name: "Konya",
      coordinates: {"lat": 37.87135, "lng": 32.48464},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 1433861 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-istinye",
      name: "İstinye",
      coordinates: {"lat": 41.11008, "lng": 29.05094},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 15721 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-sisli",
      name: "Şişli",
      coordinates: {"lat": 41.06046, "lng": 28.98717},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 314684 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-uskudar",
      name: "Üsküdar",
      coordinates: {"lat": 41.02274, "lng": 29.01366},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 524452 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-eminonu",
      name: "Eminönü",
      coordinates: {"lat": 41.01754, "lng": 28.97101},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 55548 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-talas",
      name: "Talas",
      coordinates: {"lat": 38.6908, "lng": 35.5538},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 36890 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-gaziantep",
      name: "Gaziantep",
      coordinates: {"lat": 37.05944, "lng": 37.3825},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 2222415 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-eskisehir",
      name: "Eskişehir",
      coordinates: {"lat": 39.77667, "lng": 30.52056},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 921630 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-adana",
      name: "Adana",
      coordinates: {"lat": 36.98615, "lng": 35.32531},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 1816750 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-batikent",
      name: "Batikent",
      coordinates: {"lat": 39.96833, "lng": 32.73083},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 300000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-kucukcekmece",
      name: "Küçükçekmece",
      coordinates: {"lat": 40.99104, "lng": 28.77123},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 792030 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-bahcelievler",
      name: "Bahçelievler",
      coordinates: {"lat": 41.00231, "lng": 28.8598},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 576799 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-urla",
      name: "Urla",
      coordinates: {"lat": 38.32292, "lng": 26.76403},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 62989 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-sivas",
      name: "Sivas",
      coordinates: {"lat": 39.74833, "lng": 37.01611},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 264022 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-malatya",
      name: "Malatya",
      coordinates: {"lat": 38.35018, "lng": 38.31667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 750491 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-kutahya",
      name: "Kütahya",
      coordinates: {"lat": 39.42417, "lng": 29.98333},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 185008 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-konak",
      name: "Konak",
      coordinates: {"lat": 38.4, "lng": 27.1},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 332277 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-kayseri",
      name: "Kayseri",
      coordinates: {"lat": 38.73222, "lng": 35.48528},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 1452458 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-zekeriya",
      name: "Zekeriya",
      coordinates: {"lat": 41.19806, "lng": 29.03028},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 22558 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-tarabya",
      name: "Tarabya",
      coordinates: {"lat": 41.13361, "lng": 29.04639},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 17852 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-sinop",
      name: "Sinop",
      coordinates: {"lat": 42.02683, "lng": 35.16253},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 34834 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-kars",
      name: "Kars",
      coordinates: {"lat": 40.59825, "lng": 43.08548},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 91450 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-giresun",
      name: "Giresun",
      coordinates: {"lat": 40.91698, "lng": 38.38741},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 125682 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-fatih",
      name: "Fatih",
      coordinates: {"lat": 41.0225, "lng": 28.94083},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 356025 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-band-rma",
      name: "Bandırma",
      coordinates: {"lat": 40.35222, "lng": 27.97667},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 107631 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-atasehir",
      name: "Ataşehir",
      coordinates: {"lat": 40.9833, "lng": 29.1167},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 361615 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-sultanbeyli",
      name: "Sultanbeyli",
      coordinates: {"lat": 40.96072, "lng": 29.27067},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 358201 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-cubuklu",
      name: "Çubuklu",
      coordinates: {"lat": 41.10419, "lng": 29.08331},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20698 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "turquia-evka-uc",
      name: "Evka-Üç",
      coordinates: {"lat": 38.47071, "lng": 27.25094},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 20600 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Turkey",
  capital: "Ankara",
  currency: "TRY",
  language: "turco",
  continent: "Asia",
  population: 85878556,
  cities,
  // Las universidades no van aqui: viven en ./universities/turquia.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 188,
  aliases: ["turkey", "turquia"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
