// Ucrania — importado, no curado.
//
// Trae lo que las fuentes abiertas pueden verificar: nombre, capital, moneda,
// idioma, poblacion, las ciudades con universidad y las universidades con su
// sitio oficial. Todo lo demas (costo de vida, salarios, cultura) esta vacio
// a proposito. Ver web/scripts/import_world.py.
//
// Generado. No editar a mano: se sobrescribe. Para curar este pais, muevelo a
// countries/americas/ o su continente y quitale el dataStatus de importado.

import { defineCity, defineCountry } from "../schema.js";

const countryId = "ucrania";
const countryName = "Ucrania";

// Ciudades con al menos 2 universidades situadas por coordenadas (GeoNames x
// Wikidata, ver censo_ciudades.py). Solo el resumen: que
// universidades tiene cada una vive en ./cities/ucrania.js
// y se pide al abrir la ciudad. Sin costo de vida ni cultura.
const cities = [
    defineCity({
      id: "ucrania-odesa",
      name: "Odesa",
      coordinates: {"lat": 46.48572, "lng": 30.74383},
      isCapital: false,
      universityCount: 14,
      statistics: { population: 1010537 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-lviv",
      name: "Lviv",
      coordinates: {"lat": 49.83826, "lng": 24.02324},
      isCapital: false,
      universityCount: 13,
      statistics: { population: 717273 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-dnipro",
      name: "Dnipro",
      coordinates: {"lat": 48.46664, "lng": 35.04066},
      isCapital: false,
      universityCount: 12,
      statistics: { population: 968502 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-stare-misto",
      name: "Stare Misto",
      coordinates: {"lat": 50.44759, "lng": 30.52635},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 41800 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-kharkiv",
      name: "Kharkiv",
      coordinates: {"lat": 49.98177, "lng": 36.25475},
      isCapital: false,
      universityCount: 11,
      statistics: { population: 1421125 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-shevchenkivskyi",
      name: "Shevchenkivskyi",
      coordinates: {"lat": 50.02021, "lng": 36.22468},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 220660 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-zaporizhzhya",
      name: "Zaporizhzhya",
      coordinates: {"lat": 47.85167, "lng": 35.11714},
      isCapital: false,
      universityCount: 8,
      statistics: { population: 710052 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-simferopol",
      name: "Simferopol",
      coordinates: {"lat": 44.95719, "lng": 34.11079},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 336460 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-poltava",
      name: "Poltava",
      coordinates: {"lat": 49.58925, "lng": 34.55367},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 279593 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-zhuravlivka",
      name: "Zhuravlivka",
      coordinates: {"lat": 50.0125, "lng": 36.27214},
      isCapital: false,
      universityCount: 7,
      statistics: { population: 20000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-kryvyy-rih",
      name: "Kryvyy Rih",
      coordinates: {"lat": 47.90572, "lng": 33.39404},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 603904 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-ivano-frankivsk",
      name: "Ivano-Frankivsk",
      coordinates: {"lat": 48.92312, "lng": 24.71248},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 238196 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-horlivka",
      name: "Horlivka",
      coordinates: {"lat": 48.29986, "lng": 38.01709},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 239828 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-klov",
      name: "Klov",
      coordinates: {"lat": 50.4349, "lng": 30.53807},
      isCapital: false,
      universityCount: 6,
      statistics: { population: 18000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-vinnytsya",
      name: "Vinnytsya",
      coordinates: {"lat": 49.2322, "lng": 28.46871},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 430091 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-ternopil",
      name: "Ternopil",
      coordinates: {"lat": 49.55404, "lng": 25.59067},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 225238 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-mykolayiv",
      name: "Mykolayiv",
      coordinates: {"lat": 46.97625, "lng": 31.99296},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 470011 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-kyiv",
      name: "Kyiv",
      coordinates: {"lat": 50.45466, "lng": 30.5238},
      isCapital: true,
      universityCount: 4,
      statistics: { population: 2952301 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-pechersk",
      name: "Pechersk",
      coordinates: {"lat": 50.44441, "lng": 30.52348},
      isCapital: false,
      universityCount: 5,
      statistics: { population: 100900 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-sevastopol",
      name: "Sevastopol",
      coordinates: {"lat": 44.60795, "lng": 33.52134},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 547820 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-rivne",
      name: "Rivne",
      coordinates: {"lat": 50.62036, "lng": 26.23695},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 243873 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-kamyanets-podilskyi",
      name: "Kamyanets-Podilskyi",
      coordinates: {"lat": 48.67882, "lng": 26.58516},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 97908 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-demiyivka",
      name: "Demiyivka",
      coordinates: {"lat": 50.40206, "lng": 30.51564},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 29200 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-shulyavka",
      name: "Shulyavka",
      coordinates: {"lat": 50.45356, "lng": 30.4531},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 62200 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-zarichnyi",
      name: "Zarichnyi",
      coordinates: {"lat": 50.90376, "lng": 34.80933},
      isCapital: false,
      universityCount: 4,
      statistics: { population: 150694 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-zhytomyr",
      name: "Zhytomyr",
      coordinates: {"lat": 50.26235, "lng": 28.67913},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 261624 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-uzhhorod",
      name: "Uzhhorod",
      coordinates: {"lat": 48.6242, "lng": 22.2947},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 115449 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-kherson",
      name: "Kherson",
      coordinates: {"lat": 46.63695, "lng": 32.61458},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 66000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-drohobych",
      name: "Drohobych",
      coordinates: {"lat": 49.35196, "lng": 23.51121},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 73682 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-chernivtsi",
      name: "Chernivtsi",
      coordinates: {"lat": 48.29045, "lng": 25.93241},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 264298 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-cheremushky",
      name: "Cheremushky",
      coordinates: {"lat": 46.43251, "lng": 30.71151},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 120000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-solomyanka",
      name: "Solomyanka",
      coordinates: {"lat": 50.42838, "lng": 30.45211},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 32500 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-novyi-lviv",
      name: "Novyi Lviv",
      coordinates: {"lat": 49.81519, "lng": 24.03171},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 40000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-lukyanivka",
      name: "Lukyanivka",
      coordinates: {"lat": 50.46642, "lng": 30.47591},
      isCapital: false,
      universityCount: 3,
      statistics: { population: 31400 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-yalta",
      name: "Yalta",
      coordinates: {"lat": 44.50218, "lng": 34.16624},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 77003 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-uman",
      name: "Uman",
      coordinates: {"lat": 48.7501, "lng": 30.21944},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 81525 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-melitopol",
      name: "Melitopol",
      coordinates: {"lat": 46.84735, "lng": 35.38196},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 148851 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-lutsk",
      name: "Lutsk",
      coordinates: {"lat": 50.75784, "lng": 25.35024},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 215986 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-kropyvnytskyi",
      name: "Kropyvnytskyi",
      coordinates: {"lat": 48.50834, "lng": 32.26618},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 219676 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-khmelnytskyi",
      name: "Khmelnytskyi",
      coordinates: {"lat": 49.41835, "lng": 26.97936},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 274452 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-donetsk",
      name: "Donetsk",
      coordinates: {"lat": 48.023, "lng": 37.80224},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 901645 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-cherkasy",
      name: "Cherkasy",
      coordinates: {"lat": 49.44452, "lng": 32.05738},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 269836 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-svyatoshyn",
      name: "Svyatoshyn",
      coordinates: {"lat": 50.46341, "lng": 30.34612},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 53000 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-nyvky",
      name: "Nyvky",
      coordinates: {"lat": 50.46461, "lng": 30.40593},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 71700 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-vidradnyi",
      name: "Vidradnyi",
      coordinates: {"lat": 50.43194, "lng": 30.42231},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 69800 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-oleksandrivska-slobidka",
      name: "Oleksandrivska Slobidka",
      coordinates: {"lat": 50.41827, "lng": 30.47807},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 34100 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-desnyanskyi",
      name: "Desnyanskyi",
      coordinates: {"lat": 51.50631, "lng": 31.3168},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 179600 },
      countryId,
      countryName,
    }),
    defineCity({
      id: "ucrania-nova-zabudova",
      name: "Nova Zabudova",
      coordinates: {"lat": 50.42811, "lng": 30.5153},
      isCapital: false,
      universityCount: 2,
      statistics: { population: 49000 },
      countryId,
      countryName,
    }),
];

export default defineCountry({
  id: countryId,
  name: countryName,
  nameEn: "Ukraine",
  capital: "Kyiv",
  currency: "UAH",
  language: "ucraniano",
  continent: "Europa",
  population: 38980376,
  cities,
  // Las universidades no van aqui: viven en ./universities/ucrania.js
  // y se cargan solo al abrir el pais (ver getNationalUniversities).
  universityCount: 75,
  aliases: ["ucrania", "ukraine"],
  dataStatus: "source-open-dataset",
  sources: ["Hipo/university-domains-list (MIT)", "GeoNames (CC BY 4.0)", "Wikidata (CC0)", "Banco Mundial, SP.POP.TOTL"],
});
